### ISSUE TITLE
Redirects with 'special' characters currently fail hard

### ISSUE THREAD

**Issue by niektenhoopen** [nystudio107/craft-retour#101]
Due to this breaking change the redirects to URLs with special characters are redirected incorrectly: https://github.com/nystudio107/craft-retour/commit/4f79d96ec25b3846d4d7450b7f2503b60b5404f5#diff-e1489ecc9a7cd6ebfbd894742c007890R261

For example:
/übersetzung-foo should redirect to /übersetzung-bar but now redirects to /bersetzung-bar which causes a 404.

I could not find any tests in this repo. Are there any?

**Comment by khalwat** [comment]
As noted there, it's technically doing the right thing:

https://bugs.php.net/bug.php?id=65630&edit=3

But this should be addressed in: https://github.com/nystudio107/craft-retour/commit/8466d5a682344f25d8a9bbe751bcb74bbfd05d4c

**Comment by niektenhoopen** [comment]
Sorry, was not able to respond earlier. I just checked it. It's fixed. Thank you!
