### ISSUE TITLE
Double trailing slashes on redirects

### ISSUE THREAD

**Issue by robmcfadden** [nystudio107/craft-retour#102]
`addTrailingSlashesToUrls` is set to true. I'm sure that's why it's not letting me remove the trailing slash on the Destination URL. In instances, though, where Legacy URL Pattern ends in a trailing slash, I end up with double slashes. /gear/category/test/ becomes /gear/test//

Any way around this? There may be a way strip it from the regex, but my brain broke when I realized I need to allow for slashes in the capture group because the pages can be nested like /gear/category/page1/page2/. In that case, I do need the first slash preserved in the capture group.

![Screen Shot 2020-03-09 at 3 50 08 PM](https://user-images.githubusercontent.com/435632/76251908-3f5fb800-621e-11ea-8c6f-2eb0f8693256.png)

**Comment by timkelty** [comment]
I'm sure you could do it with some nested/lookahead regex magic…but certainly doesn't seem like the "right" answer.

@khalwat The easiest way to fix this might be to just reduce double slashes on the parsed URL, since you'd never want that.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/ccdd6449d97fedb94ca4ead30eb2bddd2bb0b473
