### ISSUE TITLE
Using Retour be redirect urls with underscores to urls with dashes

### ISSUE THREAD

**Issue by samueljonasson** [nystudio107/craft-retour#103]
I bought Retour to help me transition to a new URL structure.   One of the changes is dashes instead of underscores.

```
Old: /news/some_article
New /news/some-article
```

I can't figure out how, or if, Retour can handle these redirect.  Should I just use .htaccess redirects instead since I need all urls under /news and /work to use dashes instead of underscores on my new site.

**Comment by khalwat** [comment]
So you can do this, but it'll require a little work from a custom module or the like to listen for redirects, and respond to them:

https://nystudio107.com/docs/retour/Advanced.html#resolve-redirect-events

**Comment by AMandujano-BI** [comment]
@samueljonasson Were you able to achieve this? Could you share your solution?

**Comment by khalwat** [comment]
I'm guessing you could also do it with a RegEx

**Comment by samueljonasson** [comment]
I ended up using a rewrite rule.  The solution was supposed to be a temporary one - but it is still in use.  Ooops.  
`RewriteRule ^news/(.+?)_(.+) /news/$1-$2 [R=301,L]`
`RewriteRule ^work/(.+?)_(.+) /work/$1-$2 [R=301,L]`
