### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft-retour#104]
Bug found in the latest version 3.1.34.

Downgraded to previous one to keep it working.

**Comment by siebird** [comment]
I'm having the same issue.

**Comment by rellafella** [comment]
I had the same issue, downgraded for now

**Comment by Collinvdv** [comment]
have the same issue

**Comment by nettum** [comment]
Probably hitting the same bug.  
Trying to setup a regex redirect:  
Legacy URL Pattern: `/old-secion/(.*$)`
Destination URL: `/new-section/$1`

Result is too many redirects. It always redirect to itself (from Legacy URL to Legacy URL)

**Comment by khalwat** [comment]
Fixed via the PR from @mmikkel https://github.com/nystudio107/craft-retour/pull/105 -- thank you!

Released in 3.1.35: https://github.com/nystudio107/craft-retour/releases/tag/3.1.35
