### ISSUE TITLE
Can't get past 3.1.5, even with composer.json on ^3.1

### ISSUE THREAD

**Issue by frontedbe** [nystudio107/craft-retour#108]
Hi,

I've been having a number of available updates lately, higher than version 3.1.5. Even though the craft-retour package is set to ^3.1 in composer.json

Any ideas what I'm missing here?

Screenshot of the available updates, composer.json and composer.lock
[view screenshot](https://share.getcloudapp.com/9ZuAOqny)

Thanks!

**Comment by khalwat** [comment]
If I had to guess, it's probably some other plugin/package that has a mutual dependency that's preventing it from updating.

Try watching the output of `composer update` carefully, or set Retour's semver to something higher explicitly, and see what error.s out, like `^3.1.20`
