### ISSUE TITLE
Header may not contain more than a single header (regression)

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-retour#110]
We are seeing a regression on our site where Retour is no longer handling new lines within a URL (in our case this is due to our security scanning solution).

![image](https://user-images.githubusercontent.com/3185073/77896757-a64a1d00-7270-11ea-97f4-7611901159e1.png)

This has been resolved in a previous PR (https://github.com/nystudio107/craft-retour/commit/8466d5a682344f25d8a9bbe751bcb74bbfd05d4c) but I believe version 3.1.34 caused the regression (https://github.com/nystudio107/craft-retour/commit/8466d5a682344f25d8a9bbe751bcb74bbfd05d4c)

**Comment by niektenhoopen** [comment]
@lukebailey Hi Luke, I was the one who raised an issue with German characters not working after the fix of your original issue. I will be following this issue as well. I am just curious: why would the URL contain new lines? Is dat the original URL or the URL that should be redirected to?

**Comment by khalwat** [comment]
@niektenhoopen it's an issue with their penetration testing tool. I'm having a look now to see how this regression could have happened.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-retour/commit/c63270475f09e9f377a325bcf4e38f7a87657024

@lukebailey can you set your `semVer` to `dev-develop` and confirm this fixes the regression for you?

**Comment by baileydoestech** [comment]
Thanks for the quick fix, will need to get this into our dev environment and test against a scan this evening. @niektenhoopen yes this is our security solution (Detectify) which periodically scans our sites against community discovered and OWASP Top 10 vunerlabilities. So there would be the original URL which is likely some horrible construct to try and find a backdoor into the site or injected something malicious into the page.

**Comment by baileydoestech** [comment]
That appears to be working although our nightly scans are not guarenteed to be equivilant, its possible that an issue may be encountered in due course. Could this be a good candidate for a unit test to prevent future regressions?

**Comment by khalwat** [comment]
@lukebailey great, I will cut a release.

You're 100% right that this would be a great place for a unit test. I have it on my to do list to adopt testing with my plugins in general.

**Comment by khalwat** [comment]
A unit test has been added to verify this on every push to the GitHub repo -> https://github.com/nystudio107/craft-retour/commit/521b3c03a344be5bf1bbd8d63ec172562a55e8eb
