### ISSUE TITLE
Use URL-parameter in legacy URL

### ISSUE THREAD

**Issue by olsp** [nystudio107/craft-retour#113]
I tried to enter www.domain.com/?page=contact with full URL as the match type but this doesn't work. I also tried /?page=contact with path only and it doesn't work either.
How can I use URL-parameter in the legacy url?

What I'm trying to achieve is domain.com/?page=contact getting redirected to domain.com/contact

**Comment by evanwarner** [comment]
URL parameters are considered during matching. If you are doing a RegEx match type, make sure you're escaping the `?` in your Legacy URL Pattern. Also pretty sure you need to include the protocol for full URLs. So `/\?page=contact` or `https?://www.domain.com/\?page=contact`

**Comment by olsp** [comment]
Thanks for your reply!I tried so many different possibilities just to realise, that the problem is, that the request isn't a 404.
