### ISSUE TITLE
[FR] Enable export of ALL redirects as JSON for ElementAPI and GraphQL

### ISSUE THREAD

**Issue by kayqq** [nystudio107/craft-retour#114]
Hello we are working on a fully serverless static build of our site and we require the ability the query Retour for a full list of redirects (similar to the csv export). We plan to use a Lambda and Cloudfront to handle redirects.

**Comment by khalwat** [comment]
Sounds like a good idea. I'm assuming you're want both a GraphQL query for all of the redirects as well as a JSON endpoint?

How will you be handling the regex redirects?

**Comment by richardgorman** [comment]
I also need this feature. Is this realistically going to arrive in the next few weeks? @khalwat 
If not then I need to know in order to migrate away from this plugin.

**Comment by khalwat** [comment]
It's certainly doable, but it'd be up to you to make sure you handle regex redirects correctly.

**Comment by richardgorman** [comment]
That sounds good to me. I would rather have the control than give it up.

**Comment by kayqq** [comment]
> 
> 
> Sounds like a good idea. I'm assuming you're want both a GraphQL query for all of the redirects as well as a JSON endpoint?
> 
> How will you be handling the regex redirects?

Yep both options would be nice, in reality I would be only using the Element API for my use case but I'd assume other people would want it for GraphQL.

I would be handling the regex redirects via something custom that includes AWS.

**Comment by richardgorman** [comment]
@khalwat Sorry to bring it up again but can you give an estimation for this feature?

**Comment by khalwat** [comment]
@richardgorman It's on the docket for this week

**Comment by richardgorman** [comment]
@khalwat Thank you kindly :)

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-retour/commit/1a26a58fd31c2e876b9b357ef8ec7101b311dddd

<img width="948" alt="Screen Shot 2020-06-06 at 12 24 38 AM" src="https://user-images.githubusercontent.com/7570798/83936298-6fbce100-a790-11ea-91b7-807d442f8afa.png">

**Comment by richardgorman** [comment]
@khalwat Is it possible to query for all redirects via GraphQL?

**Comment by khalwat** [comment]
@richardgorman Currently there's just the endpoint mentioned above, but I'd be open to doing it via GraphQL as well if you want to file a new Feature Request for that!

**Comment by richardgorman** [comment]
@khalwat From what I understand this was part of the feature request for this ticket. It mentions GraphQL in the title.
