### ISSUE TITLE
Bug: Retour does not override Route settings

### ISSUE THREAD

**Issue by kayqq** [nystudio107/craft-retour#115]
I have page that takes routing tokens in as such:
/resources/<tag>
/resources/<tag>/<slug>

We now want to do a redirect for /resources/podcast to www.newUrl.com, but we are running into the issue where the redirect does not work. The redirect only works if we disable tag and slug tokens.

is there a workaround for redirecting route token matches?

**Comment by khalwat** [comment]
This is not a bug. Retour only operates once Craft throws a 404. It works this way so that it is performant.

In order for Retour to do anything, the route you're redirecting from must throw a 404 -- if it is handled by Craft, Retour never sees it.
