### ISSUE TITLE
Images not redirecting

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft-retour#117]
Using Retour for the first time and while my page redirects work great, asset redirects don't seem to be doing anything. For example, I've created several redirects like this, and when putting in the legacy URL into a browser, it just loads a blank page at the legacy URL. 

<img width="1196" alt="Screenshot 2020-05-29 08 25 46" src="https://user-images.githubusercontent.com/2390/83276883-1f3cf680-a186-11ea-8a7b-9815737b1eff.png">

I've tested the destination URL and it is also correct - but for some reason Retour isn't actually redirecting my browser to the new URL. Am I missing something simple here or is this a bug?

**Comment by khalwat** [comment]
Retour only does anything when a 404 is thrown by Craft.

Are the URLs you're entering here actually throwing a 404 error?

From Retour's point of view, it doesn't care whether it's a HTML page or an image or whatever that it's redirecting -- but your webserver might be configured in a way that's causing a 404 to not be thrown with image URLs.

**Comment by jonlongnecker** [comment]
@khalwat Correct, I didn't know these were 404 errors until I switched from the now defunct Redirect add-on to Retour and it showed me the issues on the dashboard. I thought I'd try to fix them, but no luck. 

So they are throwing a 404, but file based redirects aren't working (directory based are). You mentioned server configuration - this is for the server you helped me setup (Forge + NGNIX) - maybe there's something in there blocking it?

**Comment by khalwat** [comment]
Certainly possible that there's something in the Nginx config that's causing the issue.

There's a difference between a 404 coming from Craft, and a 404 coming from your webserver.

But if Retour is logging them, they must be coming from Craft, which is very puzzling.

**Comment by jonlongnecker** [comment]
@khalwat Any other thoughts here? I have a few important images that need the redirect to work...

**Comment by khalwat** [comment]
I don't have enough information. All I can tell you is that it's not a bug in Retour; here's Retour from my live nystudio107.com site:

<img width="1275" alt="Screen Shot 2020-06-14 at 12 10 55 PM" src="https://user-images.githubusercontent.com/7570798/84598380-41966b80-ae38-11ea-81f1-993fe142173a.png">

So we have a `.jpg` file that's being redirected, and has `1060` successful hits (redirects). I also set up a local test environment, and it worked fine.

So it's going to end up being some kind of server config issue or other local setup issue. Feel free to ping me on Discord.
