### ISSUE TITLE
Full match with and without trailing slash

### ISSUE THREAD

**Issue by jakepm** [nystudio107/craft-retour#119]
Please could you advise on the best way to configure redirects on an exact match, but including an *optional* trailing slash? Ideally I would like this to be a setting for the plugin, so that exact matches are triggered regardless of the trailing slash, which we are not enforcing yet (but are used in many backlinks).

If this isn't possible, could you advise on the regex solution, as the ones I tried didn't work.

If you have any general recommendations that apply to this scenario, that would be greatly appreciated. I may ask our SEO partner if it's worth enforcing a trailing slash on the entire site via .htaccess, then we can just ensure that trailing slashes are added to all of the Retour redirect rules.

Great plugin! :)

**Comment by khalwat** [comment]
Yeah probably you'd need to do this with a regex, or you could just add two redirects (one with a `/` and one without).

For a RegEx you can try something like:
```
^\/woof((\/\w+)+|\/?)$
```

https://regexr.com/57sq6
