### ISSUE TITLE
[FR] Allow proxies to cache redirects and 404s

### ISSUE THREAD

**Issue by devinellis** [nystudio107/craft-retour#120]
A decent percentage of our uncached backend hits are 301 and 404 responses. Retour could allow us to set a custom `Cache-Control` response header, allowing us to tell proxies like Varnish or Cloudflare to cache the response.

As an example, our 200 respones set the following header: 
`Cache-Control: max-age=0, s-maxage=86400`

**Comment by khalwat** [comment]
Would you want this to be a global setting @devinellis or on a per-redirect basis?

**Comment by devinellis** [comment]
I was picturing a global setting, could even just be a headers array. 

The only use case I can think of for customizing it is for something like a blog. If an entry exists but is disabled, or not published yet, then we’d want to cache for only a few minutes. But we can also just make sure to clear the cache for the URL, so I don’t think customizing is necessary.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-retour/commit/c60fcdc9d1c1da93519126ee2cc80662b03b48e3
