### ISSUE TITLE
Import CSV layout not aligned

### ISSUE THREAD

**Issue by bymayo** [nystudio107/craft-retour#121]
I'm using Retour 3.1.39 with Craft 3.4.25, but before I upgraded to latest versions, this was an issue (Previously 3.1.37)

When I click 'Import CSV File' it's difficult to match the columns:

![Screenshot 2020-06-25 at 12 01 07](https://user-images.githubusercontent.com/522877/85708047-ad4fc280-b6db-11ea-8be7-83d9833f02a5.png)

**Comment by khalwat** [comment]
I think this is just because you have a super-long column name in the CSV file.

**Comment by khalwat** [comment]
Apparently in addition to being very long, the titles also must BE IN ALL CAPS for this issue to happen. Fixed in https://github.com/nystudio107/craft-retour/commit/1fc4bd7bea1af742f71198d5023dfba52848f3f0

**Comment by bymayo** [comment]
@khalwat Thanks! (Not how I would format the CSV, but one from a client!)
