### ISSUE TITLE
[FR] Add event EVENT_REDIRECT_RESOLVED for matched redirects

### ISSUE THREAD

**Issue by markdrzy** [nystudio107/craft-retour#122]
When the redirect service resolves redirects, if a match is found the `return` prevents the `EVENT_AFTER_RESOLVE_REDIRECT` event from being thrown.

```php
    // Iterate through the redirects
    foreach ($redirects as $redirect) {
        …
        // If there's a match…
        return $redirect;
        …
    }
    // Throw the Redirects::EVENT_AFTER_RESOLVE_REDIRECT event
    $event = new ResolveRedirectEvent([
        'fullUrl' => $fullUrl,
        'pathOnly' => $pathOnly,
        'redirectDestUrl' => $result !== null ? $result['redirectDestUrl'] : null,
        'redirectHttpCode' => $result !== null ? $result['redirectHttpCode'] : 301,
    ]);
    $this->trigger(self::EVENT_AFTER_RESOLVE_REDIRECT, $event);
    if ($event->redirectDestUrl !== null) {
        return $this->resolveEventRedirect($event);
    }
```

I've taken a stab at "fixing" this: https://github.com/markdrzy/craft-retour/commit/7dc8c8d87f35e6f2dbafeff75999fef83b51e600

**Comment by markdrzy** [comment]
Just a bit of background here to explain _why_ I'm looking to use the `EVENT_AFTER_RESOLVE_REDIRECT` to modify a redirect that has already been resolved. I'm using an alternate subdomain to serve a "live" version of the site that is used to produce a mostly-static version of the site for deployment on a CDN. Our CDN is configured to use the site's primary domain, and is in turn configured to route any 404 to the "live" subdomain, where we expect Retour to handle the redirects. Unless we enforce a "full URL in the redirect destination" rule for our clients, whenever a "path-only" redirect is used, Retour will use the Craft Base URL config setting to redirect to the "live" subdomain instead of to the CDN version of the site.

I can understand why `EVENT_AFTER_RESOLVE_REDIRECT` might be limited in scope only to 404s that are not handled by the resolver. From one perspective, `EVENT_AFTER_RESOLVE_REDIRECT` could be viewed as purely a method for developers to add a supplemental layer of redirect resolution that defers to the native resolver as primary. However, with my use-case needing to modify _all_ resolved redirects:

```php
Event::on(Redirects::class, Redirects::EVENT_AFTER_RESOLVE_REDIRECT, function (ResolveRedirectEvent $e) {
    if ( getenv('CRAFT_BLITZED_DOMAIN') ) {
        $e->redirectDestUrl = 'https://' . getenv('CRAFT_BLITZED_DOMAIN') . $e->redirectDestUrl;
    }
    return $e;
});
```

you can see why I'm looking to `EVENT_AFTER_RESOLVE_REDIRECT` to modify resolved redirects. While the existing implementation is limited to adding a supplemental layer of redirect resolution for URLs that the built-in resolver can't match, my addition allows for the option of modifying already-resolved redirects.

Now I have written a lot of words, and many of them are probably dumb. Let me know if I can clarify anything or attempt further justification of hacking apart your fine plugin.

**Comment by khalwat** [comment]
Yeah so I think `EVENT_AFTER_RESOLVE_REDIRECT` should fire only after failed attempts to resolve a redirect, because there is functionality in custom modules/plugins others have written that depends on this.

Instead, I think another event should be added... `EVENT_REDIRECT_RESOLVED` where you get a chance to modify the resolved event or the like.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-retour/commit/2ad657e6af74f927c6fd42215004ea95369a1288
