### ISSUE TITLE
[FR] Import hits via CSV

### ISSUE THREAD

**Issue by Coysh** [nystudio107/craft-retour#123]
I'm currently the `dolphiq/craft3-plugin-redirect` redirect plugin, and have built up a very useful amount of redirects.
It would be useful to import the redirects and how many times they have been hit into retour.

For reference, the dolphiq plugin:
![image](https://user-images.githubusercontent.com/5764356/86343260-a16e7e00-bc50-11ea-997f-5f3aac7e0101.png)

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-retour/commit/2c752a98aed621346efea993e95fb2bb5019a42f
