### ISSUE TITLE
passing variable in the shortlink

### ISSUE THREAD

**Issue by therealelyayo** [nystudio107/craft-retour#126]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.

### Additional context
Add any other context or screenshots about the support request here.

would it be possible to append ?email=jackson@be.com to these redirect and then using the domain of the email to redirect somewhere ,
example?email=t@gmail.com would goto gmail.com

and t@yahoo.com shuld got yahoo.com

would that be possible

**Comment by khalwat** [comment]
If I'm understanding you correctly, yes, you could do this with a regular expression redirect.
