### ISSUE TITLE
[refs #77] Using Retour for subdomains

### ISSUE THREAD

**Issue by OneMohrTime** [nystudio107/craft-retour#131]
### Question
In #77, I saw an approach that handled subdomain redirects by creating an additional site. However, my own attempt at that wasn't so successful. Craft/Retour march through any 301 redirects that match a subdomain, which is a bummer.

However, given that Retour waits for a 404 to occur, is redirecting an old subdomain to a new site _actually_ doable? If the site url is `{{ siteUrl }}`, wouldn't they always find the correct page? I'd love to avoid editing an `.htaccess` file if I can make Retour do the ugly lifting, I'm just not sure that's not possible...or maybe not recommended.

### Additional context
I did try using multiple variations of both `http` and `https`, Full URL vs Path, and using Regex (admittedly I know next to nothing of regex).

**Comment by khalwat** [comment]
It's not entirely clear to me what you're attempting to do here, but yes, if no 404 is thrown for a given URL, Retour will never be invoked.
