### ISSUE TITLE
Question about expected regex input

### ISSUE THREAD

**Issue by caseyalee** [nystudio107/craft-retour#133]
Does this plugin expect full PCRE RegEx or are there some exceptions where slashes aren't needed?

For example, if I add a regex URL pattern of `\/blog\/\?topic=(.*)` with a destination of `/blog/topic/$1`.
I have other more simple regex patterns that appear to work so I'm unsure if this is a bug, limitation, or something I'm doing wrong. Thanks!

**Comment by khalwat** [comment]
The plugin uses the PHP function `preg_replace` for the regular expression parsing:

https://github.com/nystudio107/craft-retour/blob/v3/src/services/Redirects.php#L468

You can see here for the details here:

https://www.php.net/manual/en/function.preg-replace.php
