### ISSUE TITLE
Extra / added to redirect with capture group

### ISSUE THREAD

**Issue by paddling** [nystudio107/craft-retour#134]
### Describe the bug
When creating a new redirect where the `destinationUrl` contains a capture group like `$1` an extra `/` is appended to the `destinationUrl` upon save.

### To reproduce
Steps to reproduce the behaviour:
1. Create a new redirect with the following values:   
    `legacyUrlPattern`: `^/foo/bar/(.*)`   
    `UrlMatchType`: Path Only   
`destinationURL`: `/foo/$1`   
`matchType`: Regex Match
`redirectType`: 301
2. Edit entry and an extra `/` is added to the destination URL

### Expected behaviour
No additional `/` should be added.

### Screenshots
Redirect prior to save:   
![image](https://user-images.githubusercontent.com/58182286/94170579-3f43a480-fe5e-11ea-8aa7-c93cca122a36.png)

Redirect after save:   
![image](https://user-images.githubusercontent.com/58182286/94170659-54203800-fe5e-11ea-9649-3fc5411dd81e.png)

### Versions
- Plugin version: 3.1.41
- Craft version: 3.5.8

**Comment by khalwat** [comment]
I'm not able to reproduce this here... is it possible you have the [addTrailingSlashesToUrls](https://craftcms.com/docs/3.x/config/config-settings.html#addtrailingslashestourls) Craft CMS general config setting on?

I fixed an issue that could cause this if you have that config setting set to `true`: https://github.com/nystudio107/craft-retour/commit/6d663314b5da48fbc022b63dc32d93c3144a87c7

**Comment by paddling** [comment]
Pretty sure we do have that enabled so your latest fix should address it.
