### ISSUE TITLE
redirect dont work with æøå anymore 

### ISSUE THREAD

**Issue by OleOldhoj** [nystudio107/craft-retour#135]
![image](https://user-images.githubusercontent.com/907322/94231572-da0fb200-ff36-11ea-9b99-b7a18acce3c7.png)

so 
https://www.xn--hndvrker-9zan.dk/dokument/inspiration-til-kvalitetssikringsh%C3%A5ndbog-murer-t%C3%B8mrer-og-gulv

should redirect to 
https://www.xn--hndvrker-9zan.dk/dokument/inspiration-til-kvalitetssikringshaandbog-murer-toemrer-og-gulv

previous it worked ... but now it is not working .... WHAT TO DO ? ( other than report and crying :D ?  )

**Comment by khalwat** [comment]
So I think it was technically wrong that it ever worked, because according to the spec, it's not a valid URL. 

RFC3986 says no, that is, URIs cannot contain unicode characters, only ASCII. https://tools.ietf.org/html/rfc3986#section-2

Craft CMS has a config setting for this: https://craftcms.com/docs/3.x/config/config-settings.html#limitautoslugstoascii

I'm not sure why it defaults to `false` though.

**Comment by khalwat** [comment]
Potentially related: https://github.com/craftcms/cms/issues/6923

**Comment by khalwat** [comment]
Here's what it does to the incoming URL before attempting to match it: 

```php
    public static function sanitizeUrl(string $url): string
    {
        // HTML decode the entities, then strip out any tags
        $url = html_entity_decode($url, ENT_NOQUOTES, 'UTF-8');
        $url = urldecode($url);
        $url = strip_tags($url);
        // Remove any Twig tags that somehow are present in the incoming URL
        /** @noinspection CallableParameterUseCaseInTypeContextInspection */
        $url = preg_replace('/{.*}/', '', $url);
        // Remove any linebreaks that may be errantly in the URL
        $url = (string)str_replace([
            PHP_EOL,
                "\r",
                "\n",
            ]
            , '', $url
        );

        return $url;
    }
```

What does your URL look like after being run through similar code? Maybe you need to paste the decoded URL into the **Legacy URL Pattern** field?

**Comment by khalwat** [comment]
Maybe you need to paste the decoded URL into the Legacy URL Pattern field? Are you sure it isn't trying to match:

```
/dokument/inspiration-til-kvalitetssikringsh%C3%A5ndbog-murer-t%C3%B8mrer-og-gulv
```
ie, with the "special" characters already encoded?

**Comment by OleOldhoj** [comment]
thanks fort your answer ... 

I tried both ... nothing worked ... 

/dokument/inspiration-til-kvalitetssikringsh%C3%A5ndbog-murer-t%C3%B8mrer-og-gulv
/dokument/inspiration-til-kvalitetssikringshåndbog-murer-tømrer-og-gulv

I can share screen with you one hangout ?  ool@haandvaerker.dk

**Comment by OleOldhoj** [comment]
Hmmm I did something that just works .... BUT I FEEL CHEAP and USED  ... BUT IT WORKS 

{% set url = craft.app.request.getSegment(-1) %}

{% if ["æ","ø","å"] in url %}
{% set url = app.request.uri | replace({'å': 'aa', 'æ': 'ae','ø': 'oe'}) %}  %}  
{% craft.Hdvk.Redirect(url) %}
{% endif %}
