### ISSUE TITLE
Dashboard icon not showing fully

### ISSUE THREAD

**Issue by Coysh** [nystudio107/craft-retour#136]
### Describe the bug
When at it's smallest width of 1 column, the pie chart in the dashboard cuts off the left hand side.
<img width="391" alt="Screenshot 2020-09-25 at 10 38 59" src="https://user-images.githubusercontent.com/5764356/94252187-7d52ce00-ff1b-11ea-8fb7-47946ca9eb59.png">

### Versions
- Plugin version:  3.1.41
- Craft version: Craft Pro 3.5.9

**Comment by khalwat** [comment]
I'll see if the charting library I'm using can account for this, thanks
