### ISSUE TITLE
GQL query returning results for sites not specified in query

### ISSUE THREAD

**Issue by jamesirving** [nystudio107/craft-retour#138]
### Describe the bug
When querying a redirect with the site id specified, a result is returned with a site id other than what was specified.

e.g. 

query:

``` 
{
      retour(siteId: 1, uri: "/help") {
    	siteId
        enabled
        redirectDestUrl
        redirectHttpCode
      }
    }
```

result

```
{
  "data": {
    "retour": {
      "siteId": 2,
      "enabled": true,
      "redirectDestUrl": "/",
      "redirectHttpCode": 301
    }
  }
}
```

### To reproduce
Steps to reproduce the behaviour:
1. Create a craft instance with at least 2 sites (I have just 2)
2. set up a redirect for site 2
3. query redirect for the same slug but for site 1
4. the redirect for site 2 (with siteId: 2) will be returned

### Expected behaviour
No redirects for site 2 should be returned if site 1 is specified in the query

### Screenshots
![image](https://user-images.githubusercontent.com/7563520/95142339-28d30c80-07bf-11eb-91c9-037a3564888e.png)

### Versions
- Plugin version: 3.1.39
- Craft version: Craft Pro 3.4.27

**Comment by khalwat** [comment]
I tried reproducing this here, but cannot.

Here's my query:

```gql
{
  retour(siteId: 4, uri: "/blog/stuffer") {
    siteId
    enabled
    redirectDestUrl
    redirectHttpCode
  }
}
```

This redirect exists only for siteId `4`, and this result is returned:

```
{
  "data": {
    "retour": {
      "siteId": 4,
      "enabled": true,
      "redirectDestUrl": "/blog/stuffer-to-to",
      "redirectHttpCode": 301
    }
  }
}
```

if I change it to siteId `1` (or anything else), nothing is returned:

Query:

```gql
{
  retour(siteId: 1, uri: "/blog/stuffer") {
    siteId
    enabled
    redirectDestUrl
    redirectHttpCode
  }
}
```

result:

```
{
  "data": {
    "retour": null
  }
}
```

**Comment by jamesirving** [comment]
What info would you like?

**Comment by khalwat** [comment]
@jamesirving can you give me the `id`s of your sites? I'm wondering if what is happening is the passed in `siteId` doesn't exist, so it defaults to `null` which is all sites.

**Comment by jamesirving** [comment]
yea it's 1 and 2. I also noticed a few more things:

- I've only ever been able to replicate this issue with a redirect for site 2 returning for site 1 (sometimes) but not vice versa.
- This does not happen for all redirects set up for site 2
- I can replicate this on both my local and on our hosted staging site for several different redirects
- It doesn't seem to matter if they were manually added or auto generated

#### This behaves correctly (redirect for site 1 from `/help` to`/`)
![image](https://user-images.githubusercontent.com/7563520/97506041-2afb4600-19ce-11eb-8b87-50bd9b2c8478.png)
![image](https://user-images.githubusercontent.com/7563520/97506086-40707000-19ce-11eb-981f-d061d9964754.png)

#### This is unexpected (redirect for site 2 from `/home-1` to`/home`)
![image](https://user-images.githubusercontent.com/7563520/97506141-5bdb7b00-19ce-11eb-9122-fc6308c60650.png)
![image](https://user-images.githubusercontent.com/7563520/97506193-77df1c80-19ce-11eb-92d2-a74f660543ae.png)

**Comment by khalwat** [comment]
@jamesirving So if you want to try a screen share to debug it, feel free to ping me on Discord. I need to be able to reproduce it to fix it!

**Comment by khalwat** [comment]
Will re-open if more information is provided
