### ISSUE TITLE
Redirect going to 404 instead of expected url

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-retour#139]
### Describe the bug

Client is adding a new static redirect with the **legacy pattern** set to `/congress` and the **destination url** set to _full url_ and this link `https://hub.ihrsa.org/ihrsa-european-congress-2020`

quote from client:

> We've cleared the **Sucuri Cache**, **Cache Flag**, and **Retour cache** but nothing has worked. It's currently bringing us to a 404 page (just refreshing the URL).
> 
> We've added, removed, and changed the redirect URL (added an ending / - e.g. /congress/) and Destination path but still, nothing has worked.
> 
> Side note, we don't add ending / on the URLs on the site. 

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Expected behaviour

When visiting the /congress link it should redirect to the expected offsite url rather than a 404 page.

### Versions
- Plugin version: 3.1.40
- Craft version: 3.4.27

**Comment by CreateSean** [comment]
Any update on this?

**Comment by khalwat** [comment]
Can you give me an actual URL to look at here @CreateSean ?

**Comment by khalwat** [comment]
I can guess as to what is wrong here tho -- you've set it to "Full URL" which applies to the original URL -- so it's trying to match `/congress` against something like `https://example.com/congress` and failing.

Set it to Path (not Full URL) or write a RegEx that will match properly.

**Comment by CreateSean** [comment]
@khalwat 

It's still not working.

From the client:

#I tried these settings (attached) with RegEx as my Match Type  but no luck. So I tried with Exact Match and still no luck.

https://www.ihrsa.org/congress

![⚙-Retour-Redirects-Edit-Redirect-Ihrs (1)](https://user-images.githubusercontent.com/6899490/96599014-78383300-12bd-11eb-8a8a-563fc01667be.png)

**Comment by khalwat** [comment]
They have "Regex Match" selected as the type, but what they put in there isn't a regular expression.

Also the URL you gave me to click on redirects to https://www.ihrsa.org/congress/ (with a trailing slash) which won't match either.

I'd suggest having them change it to something like this:

https://regexr.com/5egt4
