### ISSUE TITLE
Rewritten destination URLs only work once

### ISSUE THREAD

**Issue by markdrzy** [nystudio107/craft-retour#142]
When using the `EVENT_REDIRECT_RESOLVED` event to rewrite a redirect destination URL, the modified destination only applies the first time the redirect is executed — subsequent redirects are served from the redirect cache, which doesn't appear to take the modified destination into account. I assume this is caused because the redirect is cached _before_ the `EVENT_REDIRECT_RESOLVED` is triggered. (Example: lines [#448](https://github.com/nystudio107/craft-retour/blob/v3/src/services/Redirects.php#L448) and [#482](https://github.com/nystudio107/craft-retour/blob/v3/src/services/Redirects.php#L482) of the redirects service)

**Comment by khalwat** [comment]
Are you saying that the destination is modified to be different each time through, thus the cached result is wrong?

Or do you mean that what gets cached is simply wrong?

**Comment by khalwat** [comment]
Ah right never mind, I see it. Yep that's wrong. I will have it cache it after the event fires.

Fixed in https://github.com/nystudio107/craft-retour/commit/af3a055f8ac7a7ace5ca7d9785172d4d6bfdb989
