### ISSUE TITLE
Uses deprecated check for live preview mode

### ISSUE THREAD

**Issue by elivz** [nystudio107/craft-retour#143]
### Describe the bug
The `handle404()` function currently uses the deprecated `$request->getIsLivePreview()` to avoid redirecting in preview mode. On Craft 3.2 and up, that always evaluates to `false` for entries. I believe instead that this: https://github.com/nystudio107/craft-retour/blob/307ae917769f2070bf1311ff508525a6efce6fd2/src/services/Redirects.php#L171 

should change to this:

    if ($request->getIsSiteRequest() && !$request->getIsPreview() && !$request->getIsLivePreview() && !$request->getIsConsoleRequest()) {

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-retour/commit/d9f6f2b26e1ebba0e9b9849e68a29a50a4130a13
