### ISSUE TITLE
No 404 statistics recorded when using GraphQL

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-retour#144]
### Describe the bug

No statistics are recorded are for URIs when sent via the `retour` GraphQL query.

> Whenever you query Retour via GraphQL, it assumes a 404 has already taken place, and records the statistics for it.

### To reproduce

**GQL**

```gql
query QueryRetour($uri: String!) {
  retour(uri: $uri) {
    redirectDestUrl
  }
}
```

**Variables**

```json
{
  "uri": "/this/page/does/not/exist"
}
```

**Response**

```json
{
  "data": {
    "retour": null
  }
}
```

### Versions
- Plugin version: 3.1.42
- Craft version: 3.5.14

**Comment by joshuabaker** [comment]
I’ve checked using GraphiQL too and reset the plugin...

![image](https://user-images.githubusercontent.com/160484/99573302-d562f980-29cd-11eb-88be-0b17e8e0ab08.png)

**Comment by khalwat** [comment]
I think this is actually due to this:

https://github.com/nystudio107/craft-retour/issues/145

...because the code is in place to increment the statistics.

**Comment by joshuabaker** [comment]
Thanks, Andrew! 🙏🏻

**Comment by jaydensmith** [comment]
@khalwat this still seems to be happening in the latest version (3.1.46).

**Comment by khalwat** [comment]
@joshuabaker can you confirm? @jaydensmith can you give me some details on what you're doing that is failing to record stats?

**Comment by jaydensmith** [comment]
Hey @khalwat, nothing special I don't think. I've tried executing the following query from the site and also from the CP GraphiQL:

```graphql
query {
  redirect: retour(uri: "/foo", siteId: 1) {
    redirectDestUrl
    redirectHttpCode
  }
}
```

The response:
```json
{
  "data": {
    "redirect": null
  }
}
````

I cleared the retour statistics beforehand and they're not being logged. I did try with and without `siteId`.

**Comment by khalwat** [comment]
@jaydensmith is it possible that the reason here could be GraphQL caching? Do you have this enabled?

**Comment by jaydensmith** [comment]
Hey @khalwat, this happens locally and in our staging environment where caching is disabled.

**Comment by khalwat** [comment]
@jaydensmith I misunderstood the problem, sorry. It does increment statistics for 404s that resolve to a Retour Redirect, but it does _not_ increment statistics for a 404 that has no redirect in place.

Fixed in https://github.com/nystudio107/craft-retour/commit/f2341083c7436fd000ed0b09cfc7b78e6753d408
