### ISSUE TITLE
siteId parameter is needed for GraphQL to work as documented

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-retour#145]
### Describe the bug

The `siteId` parameter is required when using the `retour` GraphQL query, however, the documentation suggests otherwise.

> You must at least pass in the URI you want metadata for:
> 
> ```{
>   retour(uri: "/stuff") {
>     redirectDestUrl
>   }
> }
> ```
> 
> ...and you can also pass in an optional `siteId`:
> 
> ```{
>   retour(uri: "/stuff", siteId: 1) {
>     redirectDestUrl
>   }
> }
> ```

Leaving this off returns `null` in the response.

### Versions

- Plugin version: 3.1.42
- Craft version: 3.5.14

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/f052e626a912547bf73189ad1d44e7a15aadec79
