### ISSUE TITLE
GraphQL cache not invalidated when saving a static redirect

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-retour#146]
### Describe the bug

I’ve noticed that a manual cache clear is needed after saving a static redirect, instead of Retour initiating that automatically.

### Versions

- Plugin version: 3.1.42
- Craft version: 3.5.14

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-retour/commit/f078a0dcbf85c3de729f41f5dd058c3319b8740d
