### ISSUE TITLE
[FR] Get all redirects from GraphQL

### ISSUE THREAD

**Issue by marjorg** [nystudio107/craft-retour#148]
### Is your feature request related to a problem? Please describe.
I'm using Next.js and static generation of all our CMS pages and in order to build the urls with redirects correctly I need a list of all redirects.

### Describe the solution you would like
I came across issue #114 which fixed this problem for the Element API in 1a26a58. In that issue you requested a FR to add the same feature to GraphQL, but I couldn't find an issue for it so I created this one.

**Comment by khalwat** [comment]
Thanks for that!

**Comment by marjorg** [comment]
@khalwat Great! Any idea when this will be released?

**Comment by khalwat** [comment]
Added in 3.1.67 -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.67

**Comment by howells** [comment]
@marjorg would like to know how you plan to incorporate this into your next project :-)

**Comment by marjorg** [comment]
@howells I'm no longer working at the company where I needed this, so likely I won't use it anymore. (Don't use Craft atm)
