### ISSUE TITLE
Stats table trimming

### ISSUE THREAD

**Issue by croxton** [nystudio107/craft-retour#149]
### Question
I'm finding that on a site that is static cached, and where the editors don't login for a day or so, the stats table can easily grow to 100,000s of rows, I assume because Crafts queue of tasks is not triggered. Left a week or more and we'd have a database GBs in size... not necessarily a problem but alarming when you come across it the first time. Would you agree that running a cron to clear the cache every few hours would be sensible?

```./craft retour/stats/trim```

I'm adding this here as it's probably something that would be good to address in the docs.

### Context
Statistics to Store:1000
Automatically Trim Statistics: Yes (doesn't happen)
Statistics Trimming Rate Limit: Once per hour (doesn't happen).

**Comment by khalwat** [comment]
Yeah if queue jobs are not being run by some mechanism, then you should run that command via cron.

Or you can set up a queue that runs without needing to piggyback off of a web request: https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms
