### ISSUE TITLE
Importing CSVs only renders one redirect

### ISSUE THREAD

**Issue by furioursus** [nystudio107/craft-retour#15]
I'm only getting one redirect (the first one in the list) when I import a CSV. I've made sure I match the field values and still have no luck. I've attached the file I'm using for testing.

[404s.zip](https://github.com/nystudio107/craft-retour/files/2376761/404s.zip)

**Comment by khalwat** [comment]
Fixed in 3.0.1 -> https://github.com/nystudio107/craft-retour/releases/tag/3.0.1
