### ISSUE TITLE
Permissions issue if only redirects enabled

### ISSUE THREAD

**Issue by gavinplatt** [nystudio107/craft-retour#151]
### Description

We have a user account which we want to grant access to only the 'Redirect' section of Retour, not 'Dashboard'. But clicking 'Retour' in the navigation defaults to the dashboard view, so throws a permission denied error.

### To reproduce

1. Assign a user the following permissions: `General → Access Retour` and `Retour → Redirects`. Leave `Retour → Dashboard` unchecked.
2. Log in as that user
3. Click 'Retour' in the sidebar navigation. You'll see a permission denied error.
5. Visit `admin/retour/redirects`. You'll see the redirects view.

### Expected behaviour

I would expect the user to see the 'Redirects' screen by default when clicking 'Retour'.

Or alternatively, to not have the option to disable the `Retour → Dashboard` user permission.

### Versions
- Plugin version: 3.1.45
- Craft version: 3.5.16

**Comment by khalwat** [comment]
It's tricky... what if they don't have permissions for Redirects either? I'll see if I can come up with something reasonable

**Comment by khalwat** [comment]
Fixed via @mmikkel 's PR https://github.com/nystudio107/craft-retour/pull/175
