### ISSUE TITLE
Redirects no longer work for sites with a site base url other than /

### ISSUE THREAD

**Issue by adamseabrook** [nystudio107/craft-retour#152]
### Describe the bug
We have a number of redirects for our non-english sites which sit on base urls of /es /it /fr Retour automatically creates the redirects without the site base url so `/guide/nomi-aziende-riparazione-moto` > `/guide/nomi-officine-riparazione-moto` when in reality it is `/it/guide/nomi-aziende-riparazione-moto` > `/it/guide/nomi-officine-riparazione-moto` but it understands the base url should be evaluated as it correctly tags the redirects to the specific Italian site not `all sites`.

These worked fine previously but now only our English redirects work as they are all using the root base url `/`

If I manually edit the redirect and insert the base url they work. For example:
`/it/guide/nomi-aziende-riparazione-moto` -> `/it/guide/nomi-per-officine-di-riparazione-per-moto` under the Italian site
vs
`/guide/nomi-aziende-riparazione-moto` -> `/guide/nomi-per-officine-di-riparazione-per-moto` under the Italian site which no longer works.

### To reproduce
Steps to reproduce the behaviour:
1. Set up Craft with two sites and put one with a base URL of /it
2. Change the slug for any /it entry and confirm retour automatically created the redirect
3. The old slug will now get a 404 as it does not include `/it/` in the redirect evaluation

### Expected behaviour
Redirects should include the base url for the site the entry is on or understand that the base url needs to be evaluated for any redirect.

### Versions
- Plugin version: 3.1.44
- Craft version: 3.5.16

**Comment by adamseabrook** [comment]
I believe this issue appeared in 3.1.43 or 3.1.44 as we upgraded from 3.1.42 to 3.1.44 in one step

**Comment by khalwat** [comment]
So technically the `/it/` is part of the Site URL, and not the URI when a request comes in.

I'm not seeing anything in changelog or commits for 3.1.43 or 3.1.44 that seem like they would affect this https://github.com/nystudio107/craft-retour/blob/v3/CHANGELOG.md#3144---20201208

Are you sure something else didn't change in terms of the site in the interim?

**Comment by adamseabrook** [comment]
Yes. We also tried downgrading both Retour and Craft but the issue persists so I believe it is just a coincidence it only got noticed after the upgrade. We recently changed a bunch of our non-English urls so the number of 404 spiked which was why we started looking.

We managed to fix this by manually changing all the auto created redirects to Regex so the legacy url `/guías/tnombres-para-empresas-de-teñidos` became `/guías/tnombres-para-empresas-de-teñidos($|#|\?|\/)` and the destination url `/guías/nombres-para-empresas-de-teñidos$1`

This now works so `https://www.domain.com/es/guías/tnombres-para-empresas-de-teñidos` redirects to `https://www.domain.com/es/guías/nombres-para-empresas-de-teñidos`

There are no other settings we can see that could be causing this.

**Comment by khalwat** [comment]
You'll want to use the **Legacy URL Match Type** set to **Full URL** since the `/it/` is actually part of the Site URL prefix, and not the URI:

<img width="580" alt="Screen Shot 2020-12-14 at 10 33 01 AM" src="https://user-images.githubusercontent.com/7570798/102100840-e4d03980-3df7-11eb-9a5f-c503a6766443.png">

There is also a ** Entry Redirects URL Match Type** you will want to set to **Full URL** as well:

<img width="957" alt="Screen Shot 2020-12-14 at 10 34 53 AM" src="https://user-images.githubusercontent.com/7570798/102100970-11845100-3df8-11eb-9f63-5c0fa8e17691.png">

**Comment by adamseabrook** [comment]
Yes, we also tried this but the domain where our content team works is different to the production server so we end up with the redirect being created as staging.domain.com/es/something vs www.domain.com/es/something is there somewhere we should be using an environment variable so it uses the production domain in the automatically created redirects?

**Comment by khalwat** [comment]
Unfortunately no such feature exists

**Comment by adamseabrook** [comment]
Happy to pay to get this fix in. Our only alternative is having to manually fix every automatically created redirect which is costly and time consuming.

Rather than using an environment variable it just needs to properly support path only match for non-default sites so if you are interested in this can you email me the cost on adam@betterteam.com

**Comment by khalwat** [comment]
@adamseabrook Can you file a new FR for this? Sorry if it seems like busywork but it's separate from this issue. Shouldn't be too bad to do (hopefully)
