### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry 'plugin:retour-Install' 

### ISSUE THREAD

**Issue by dillonbailey** [nystudio107/craft-retour#153]
### Describe the bug
When running project-config/apply an error is produced of:

```
Installing plugin "retour" ... error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'plugin:retour-Install' for key 'migrations.migrations_track_name_unq_idx'
The SQL being executed was: INSERT INTO `migrations` (`track`, `name`, `applyTime`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('plugin:retour', 'Install', '2020-12-17 00:04:17', '2020-12-17 00:04:17', '2020-12-17 00:04:17', '40637084-9c46-4e45-a56d-974fbd79863e')
Aborting config apply process
```

### To reproduce
Steps to reproduce the behaviour:
Unable to provide steps as this emerged after deploying our application to production, the only thing that we can figure out is that the plugin was uninstalled, re-installed and on subsequent deployments the migration table still contained references to plugin:retour

### Expected behaviour
The project-config/apply to complete successfully

### Screenshots
![Screen Shot 2020-12-17 at 5 02 25 pm](https://user-images.githubusercontent.com/1067872/102450030-b1a4d900-4089-11eb-8723-5aa3f6e95883.png)

### Versions
- Plugin version: 3.1.45
- Craft version: 3.5.16

**Comment by khalwat** [comment]
So this isn't going to be a bug in Retour itself, but rather some kind of an issue with Craft CMS and Project Config.

Retour doesn't handle updating anything in the `migrations` table. I realize this may be happening for you _only_ with Retour, so it may seem like it's an issue with the plugin, but I'm reasonably sure it's not.

**Comment by dillonbailey** [comment]
Thanks @khalwat - I thought that may be the case but wanted to start here. Will escalate with the Craft team!
