### ISSUE TITLE
What would cause a page to show up in retour when it's live?

### ISSUE THREAD

**Issue by sunscreem** [nystudio107/craft-retour#158]
### Question
This is almost definitely an issue with a handful of older sites we've inherited, but I wondered if anyone has any guesses why a live page would trigger retour to think it's offline?

**Comment by khalwat** [comment]
Can you be a bit more specific, maybe show me the errors / statuses you're seeing?

Basically, if Craft throws a 404 error for a page, Retour will log it as such. So if you're seeing 404s for pages that exist on the frontend, then you need to figure out why Craft is throwing a 404 for said pages.

**Comment by sunscreem** [comment]
Yeah - that's exactly the problem @khalwat. It's happening on multiple pages and there's nothing too obvious as to why. Any tips on where you would start with debugging this?

**Comment by khalwat** [comment]
So this isn't going to be a problem with Retour, it's just reporting that a 404 happened. Craft is what is throwing the 404.

I'd suggest starting by going through your log files to figure out what is wrong; Craft will log information in `web.log` and `404s.log` -- more info is here:

https://nystudio107.com/blog/zen-and-the-art-of-craft-cms-log-file-reading

**Comment by sunscreem** [comment]
Thanks @khalwat - Appreciate that.
