### ISSUE TITLE
Site's Base URL isn't honoured in Retour control panel UI

### ISSUE THREAD

**Issue by howells** [nystudio107/craft-retour#159]
### Describe the bug
I use Retour for a headless site whereby Craft is set up on a different subdomain to the actual site. However, in Retour's CP UI, the small arrow icon that should open the source/destination URLs use the CMS's base url rather than the base url specified in my Site's settings.

### To reproduce
Steps to reproduce the behaviour:
1. Set up Craft on a subdomain e.g. cms.domain.com
2. Set default site's base url the actual client, e.g. www.domain.com
3. Create a redirect, e.g. /source to /destination
4. Click the source open icon. URL that is opened is cms.domain.com/source

### Expected behaviour
The source/destination URL should be www.domain.com/source

### Versions
- Plugin version: 3.1.47
- Craft version: 3.6.7

**Comment by khalwat** [comment]
@howells does the redirect itself work as expect though, and only the GUI click that opens the page fail?

**Comment by howells** [comment]
@khalwat yeah it works totally fine - it's purely a GUI issue I think

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/61663fccc8059fd10e0f00d0feaefed76a7a1128
