### ISSUE TITLE
Redirects stop at 1000?

### ISSUE THREAD

**Issue by furioursus** [nystudio107/craft-retour#16]
We installed the plugin yesterday (what a godsend, btw) but we noticed that our results are capping at 1000 items under the dashboard. Is this by design? I can't imagine we've stopped at exactly 1k results.

**Comment by khalwat** [comment]
This is just for the statistics... and yes, this is by design, but you can control the setting in Retour -> Settings. Adjust the **Statistics to Store** to whatever you want
