### ISSUE TITLE
craft/resave/entries doesn't appear to trigger auto-created redirects

### ISSUE THREAD

**Issue by mattbloomfield** [nystudio107/craft-retour#162]
### Describe the bug
If you manually change a slug on an entry and save it - this plugin will auto-create a redirect. Great! 

If you use that slug in the slug of other entries, it will not auto-create redirects for those. This is reasonable. In fact, CraftCMS doesn't change the slugs until those get resaved.

If you run craft/resave/entries from the CLI, the slugs will all change, but Retour doesn't auto-create redirects. It seems to be totally unaware of the change in slug. 

If you instead manually open each entry and click save (within the control panel) the redirects will be auto-created. 

### To reproduce
Steps to reproduce the behaviour:
1. Create an entry type (Entry Type 1)
2. Add a field that is relational to a different entry type (Entry Type 2)
3. For the Entry Type 1, modify the URL to reference the relational field. e.g. 
```
my-path/{relationalField.first().slug}/{slug}
```
4. Create a new Entry Type 1 entry, make sure to fill the field that references Entry Type 2. 
5. Modify the slug of the referenced Entry Type 2. 
6. Note that Entry Type 1's entry still loads under the same slug
7. In the CP, navigate to Entry Type 1's entry. Click Save
8. Note that Entry Type 1's entry now loads under the new slug
9. Navigate to Retour's redirects, note the new redirect for Entry Type 1's entry. 
10. Repeat steps 2-6,
11. In the CLI, run ./craft/resave/entries 
12. Navigate to Retour's redirects, see there is no new redirect for Entry Type 1's entry

### Expected behaviour
./craft/resave/entries should trigger the same behavior for auto-creating redirects as manually saving in the CP

### Versions

PHP version | 7.4.11
OS version | Linux 4.19.121-linuxkit
Craft edition & version | Craft Pro 3.6.8
Retour | 3.1.49

**Comment by khalwat** [comment]
So there's explicitly this comment in the code:

```php
                    // If we're running Craft 3.2 or later, also check that the element isn't bulk
                    // re-saving, and that isn't not a draft or revision
                    if (Retour::$craft32 && (
                            $element->resaving ||
                            ElementHelper::isDraftOrRevision($element)
                        )) {
                        $checkElementSlug = false;
                    }
```

https://github.com/nystudio107/craft-retour/blob/v3/src/Retour.php#L335

...which I'm pretty sure is the reason for this. I want to ensure that changing the behavior here won't break anything however.

**Comment by khalwat** [comment]
Here's the commit: https://github.com/nystudio107/craft-retour/commit/674ca01369d0ad06ec9225013e7e65d2c6e135e2#diff-ad3abc107484bf895abd932d3a346f5be2fadbf39fb51ba0fbd3f5cd147cd7c3

Discussion: https://github.com/craftcms/cms/issues/4589

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/97061dfe3964427b0550e3148019465acf44d25c#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.50”,
```
Then do a `composer update`
