### ISSUE TITLE
Enable per site

### ISSUE THREAD

**Issue by himynameisphil** [nystudio107/craft-retour#165]
Within a multi-site set up, you might not always want the same settings across each one.

Ideally you'd be able to disable things such as 'Create Entry Redirects' on a per site basis.

**Comment by khalwat** [comment]
Which of the settings do you want to be per-site, or all of them?

**Comment by himynameisphil** [comment]
> Which of the settings do you want to be per-site, or all of them?

I'd probably say all of them, yeah.

**Comment by khalwat** [comment]
Dup of https://github.com/nystudio107/craft-retour/issues/59
