### ISSUE TITLE
URL encoded path not redirecting

### ISSUE THREAD

**Issue by hatzipanis** [nystudio107/craft-retour#166]
### Describe the bug
A URL encoded path (`/resources/refreshed-lets-get-real---framework%20overview/892`) did not redirect to the **Destination URL**.

### To reproduce
Steps to reproduce the behaviour:
1. Press **New Static Redirect**
2. Enter `/resources/refreshed-lets-get-real---framework%20overview/892` in the **Legacy URL Pattern** field
3. Press **Save**
4. Visit this page
5. Thank @khalwat for an otherwise excellent plugin

### Expected behaviour
Expected this URL to redirect. Instead it 404'd. Decoding the URL worked but ideally we wouldn't have to do that as the output from another source is an encoded URL.

### Versions
- Plugin version: 3.1.47
- Craft version: Craft Pro 3.5.17.1

**Comment by khalwat** [comment]
hrm. Maybe it should just URL decode the Legacy URL Pattern field before it saves the redirect? It'd need to do that only for Exact Match redirects though, because potentially doing this could screw up some RegEx's

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-retour/commit/fa577883e80b647fa39e4e12c82a0488070b6ab6

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.50”,
```
Then do a `composer clear-cache && composer update`

**Comment by hatzipanis** [comment]
Thanks so much @khalwat 🙂
