### ISSUE TITLE
`Unknown column 'siteId' in 'where clause'` for 404 pages with Retour enabled.

### ISSUE THREAD

**Issue by tyssen** [nystudio107/craft-retour#167]
### Describe the bug
On a site with Retour installed and enabled, when you visit a page that is 404, you get an internal server error. Turning on dev mode, gives:

> Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'siteId' in 'where clause' in /vendor/yiisoft/yii2/db/Command.php:1293
> Stack trace:
> #0 /home/pblog/staging/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
> #1 /home/pblog/staging/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT *\nFROM `...')
> #2 /home/pblog/staging/vendor/yiisoft/yii2/db/Command.php(401): yii\db\Command->queryInternal('fetchAll', NULL)
> #3 /home/pblog/staging/vendor/yiisoft/yii2/db/Query.php(248): yii\db\Command->queryAll()
> #4 /home/pblog/staging/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
> #5 /home/pblog/staging/vendor/nystudio107/craft-retour/src/services/Redirects.php(643): craft\db\Query->all()
> #6 /home/pblog/staging/vendor/nystudio107/craft-retour/src/services/Redirects.php(344): nystudio107\retour\services\Redirects->getAllStaticRedirects(NULL, 1)
> #7 /home/pblog/staging/vendor/nystudio107/craft-retour/src/services/Redirec

### To reproduce
Steps to reproduce the behaviour:
1. Enable Retour
2. Visit a missing page on the front end
3. Get the error above if dev mode is enabled
4. Disable Retour
5. Visit the page again
6. Get normal 404 output

### Versions
- Plugin version: 3.1.49
- Craft version: 3.5.19.1

**Comment by khalwat** [comment]
So... something is amiss with your install here. Do you have any idea why the `siteId` column might be missing from the `retour_static_redirects` ? It's added in the Install migration: https://github.com/nystudio107/craft-retour/blob/v3/src/migrations/Install.php#L117 

I can confirm that this is not a general bug in Retour, I visited a number of 404 pages on several sites without issue. Tell me more about this Craft site, is it a migration of some kind?

**Comment by tyssen** [comment]
I'm late to the party working on this site and it seems like Retour might've been installed on this site when it was still running Craft 2 quite a while back. I guess it wasn't removed properly later on and so the legacy db tables were still in place and migrations weren't run properly. Uninstalling and reinstalling fixes the problem.

**Comment by khalwat** [comment]
If you want to keep the data, manually re-running the migrations should do it too.
