### ISSUE TITLE
Manage .php routes

### ISSUE THREAD

**Issue by AMandujano-BI** [nystudio107/craft-retour#168]
**Question**
I'm trying to make a retour from book.php?code=1234, but Craft is always throwing a Not Found error. I know the solution has to do with my NGINX, but any configuration I've tried hasn't worked. 

Any ideas on how  to achieve this?

**Comment by khalwat** [comment]
Probably you need something like this:

<https://github.com/nystudio107/nginx-craft/blob/master/sites-available/somedomain.com.conf#L128>

But yes, this is an Nginx configuration issue.
