### ISSUE TITLE
Importing CSV File fails silently

### ISSUE THREAD

**Issue by shoored** [nystudio107/craft-retour#169]
### Describe the bug
When importing a CSV file with redirects, no redirects get added to Retour. It fails silently without any errors given.
I have changed the CSV file several times, to have less lines (full list is 1200), to have only exact matches without regex, to have 10 of the simplest lines. This makes no difference. 

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Retour"
2. Click on "Redirects"
3. Click on "Import CSV file"
4. Match the columns
5. Click "Import"
6. Return to Redirects without new rules

### Expected behaviour
When importing redirects with CSV, I expect the new rules to be added. 

### Versions
- Plugin version: 3.1.50
- Craft version: 3.5.19.1

**Comment by khalwat** [comment]
Are you able to get the redirects CSV to me somehow so I can test?

Also in your `composer.lock` file, what version does it list for `league/csv` ?

**Comment by shoored** [comment]
Sure thing, where can I email it to?

`league/csv` is at `9.7.0`

**Comment by khalwat** [comment]
andrew@nystudio107.com or via Discord DM

**Comment by khalwat** [comment]
Was able to confirm that I can import both files locally, after changing the `SiteId` to something that exist in my test environment.

**Comment by khalwat** [comment]
Looks like the issue here is actually the package version detection. I'm using what apparently are Composer 2 APIs, and @shoored has Composer 1.x installed.

The error is:

```
    [*:message] => 'Class \'Composer\\InstalledVersions\' not found'
    [Error:string] => ''
```

here: https://github.com/nystudio107/craft-retour/blob/dc9faecadb57ddb0062a5aae58e5c5521bcebf05/src/helpers/Version.php#L42

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/4200b0b73039f609dcd69a5ad8995216c0bdeb05

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.51”,
```
Then do a `composer clear-cache && composer update`
