### ISSUE TITLE
Issue when trying to composer install on shared hosting that still runs on Composer 1.10.0

### ISSUE THREAD

**Issue by frontedbe** [nystudio107/craft-retour#170]
### Describe the bug
Getting the following error when trying to deploy on a shared hosting that still runs on Composer 1.10.0 (unfortunately I can't change the version as it is a shared hosting)
Locally my server is running composer 2.0 and runs fine.

``` 
Your requirements could not be resolved to an installable set of packages.

    Problem 1
      - Installation request for jean85/pretty-package-versions 2.0.3 -> satisfiable by jean85/pretty-package-versions[2.0.3].
      - jean85/pretty-package-versions 2.0.3 requires composer-runtime-api ^2.0.0 -> no matching package found.
    Problem 2
      - jean85/pretty-package-versions 2.0.3 requires composer-runtime-api ^2.0.0 -> no matching package found.
      - nystudio107/craft-retour 3.1.52 requires jean85/pretty-package-versions ^1.5 || ^2.0 -> satisfiable by jean85/pretty-package-versions[2.0.3].
      - Installation request for nystudio107/craft-retour 3.1.52 -> satisfiable by nystudio107/craft-retour[3.1.52].
```

### To reproduce
Steps to reproduce the behaviour:
1. Install / select composer 1.10.0
2. composer require / install the latest nystudio107/craft-retour package
3. See error message from above

### Versions
- Plugin version: 3.1.52
- Craft version: 3.6.11.2

**Comment by khalwat** [comment]
This isn't something I can resolve for you; but you need to be running the same version of Composer locally that you run in production, if you're going to use the `composer.lock` file 

So either use Composer 1.x locally to write out the `composer.lock` file or  delete the `composer.lock` file entirely, and let the Composer version on your production server resolve the dependencies from scratch.
