### ISSUE TITLE
Feature Request: trim() the values of Legacy URL Pattern and Destination URL

### ISSUE THREAD

**Issue by aaronbushnell** [nystudio107/craft-retour#173]
### Is your feature request related to a problem? Please describe.
On many occasions we're copying/pasting redirect values from documents the client sends us. _Sometimes_ during a copy/paste we get an errant whitespace character at the end and it causes the redirect to not work as expected.

### Describe the solution you would like
It would be fantastic if Retour could automatically trim out the whitespace characters on our behalf on Legacy URL Pattern and Destination URL

### Describe alternatives you have considered
I suppose one option would be to introduce a standardized redirect spreadsheet that a client enters redirects into. However, this could still contain stray whitespace characters.

**Comment by khalwat** [comment]
hrm. I'm thinking of the edge case where they might need to redirect from a (wrong) URL that ends in whitespace, but I suppose they can always just use `%20`

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-retour/commit/8ea876c773ba7b66bc41562417736bd79098e56d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.53”,
```
Then do a `composer clear-cache && composer update`

**Comment by aaronbushnell** [comment]
Woohoo! Thanks so much @khalwat!
