### ISSUE TITLE
Ability to return 410 (Gone) instead of 404 for a URL to tell crawlers to forget about the page

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/craft-retour#178]
### Is your feature request related to a problem? Please describe.
We're going to prune a bunch of content on the site and want to be able to mark it as Gone instead of redirecting it. This will tell Google to no longer serve it up in searches

### Describe the solution you would like
Allow 410 as an option next to 301/302, in the redirect panel

### Describe alternatives you have considered
We could submit this list to Google, but I haven't really had to do that before. It would be great to be able to do on a per page basis as we prune content

**Comment by khalwat** [comment]
mmmmm I'm not sure if this fits in with what Retour does really, but I'll consider it.

In the interim if you need a quick solution, I'd make a new entry type called Pruned or something... and set the template to just an empty Twig page that returns that status code.

**Comment by gbowne-quickbase** [comment]
If I 301 the pruned content to that new pruned.twig, wouldn't we see that 301 in the HTTP chain? Just working to wrap my head around it. I totally realize I'm throwing an edge case into the mix, but I wonder how many other people might want to be able to just say "yeah, that page doesn't exist, and it's not ever going to"

**Comment by khalwat** [comment]
I think most people likely just let it 404, and let Google figure it out :)

**Comment by khalwat** [comment]
Anyway I'll play with it, and if it's something I can easily retrofit, I will.

**Comment by khalwat** [comment]
So... this is a little embarrassing
<img width="458" alt="Screen Shot 2021-06-11 at 11 04 45 PM" src="https://user-images.githubusercontent.com/7570798/121763374-84e9ef80-cb09-11eb-8d83-52abcbda8064.png">
 but... Retour already supports this:

:)
