### ISSUE TITLE
Redirects with unknown directory

### ISSUE THREAD

**Issue by lucosius** [nystudio107/craft-retour#180]
Hello,

Making this type of redirects it's a bit new thing for me and I cannot find the solution. So..

My old URLS was:

first-directory/second-directory/entry-slug

and the new ones:

third-directory/fourth-directory/entry-slug

How can I make redirects if first and second directory is unknown and third and fourth is already provided in the "redirect to" field? I understand that I need to use regex but don't know how to make it...

**Comment by khalwat** [comment]
Yes, you'd need a regular expression. Something like this:

Legacy URL: `.*/.*/(entry\-slug)`

Redirect URL: `third-directory/fourth-directory/$1`

And the match type needs to be RegEx

ref: https://regexr.com/5totk
