### ISSUE TITLE
PHP Notice when creating a new redirect

### ISSUE THREAD

**Issue by JensvdHeydt** [nystudio107/craft-retour#181]
### Describe the bug
It's just a small bug but it prevents me from using this plugin with my site. When I try to create a new redirect the php notice is thrown.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Retour -> Redirects"
2. Click on "New Static redirect"
3. See error message "PHP Notice: iconv(): Wrong charset, conversion from `ASCII' to `UTF-8//IGNORE' is not allowed"

### Versions
- Plugin version: 3.1.53
- Craft version: 3.6.15

**Comment by khalwat** [comment]
Where is your site being hosted? This is almost always an issue with the underlying OS and the `iconv` install.

**Comment by JensvdHeydt** [comment]
HI @khalwat ,

actually it's not hosted yet. I'm getting the notice on my local docker env though I'm also using that docker image on production sites. Any hints on how I should investigate this?

**Comment by khalwat** [comment]
Yeah you need to fix this in your Docker images. Here's how I fixed it in mine:

https://github.com/nystudio107/docker-images/blob/master/php-prod-base/php-8.0-alpine/Dockerfile#L32

&

https://github.com/nystudio107/docker-images/blob/master/php-prod-base/php-8.0-alpine/Dockerfile#L96

ref: https://github.com/docker-library/php/issues/1121

**Comment by JensvdHeydt** [comment]
@khalwat  thx for the quick answer and your help. I already had a similar fix in use but had to update the version of gnu-libiconv. Works great now.
