### ISSUE TITLE
[FR] Possibility to set default settings in the dashboard

### ISSUE THREAD

**Issue by unfolded-development** [nystudio107/craft-retour#185]
We now have the dashboard showing a list of all the incoming traffic both "Handled" and "Not handled". We have seen that in case of a big website with lots of traffic you get lost easily. You add a redirect that you found on page 5, save it, and then it skips back to page 1.

It would be nice if you can set "Not handled" as a default and select a number of results to show (instead of fixed 20 a page)

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/d16c08ab27efde24d2342816b1ef03b866006f2a

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.55”,
```
Then do a `composer clear-cache && composer update`

**Comment by unfolded-development** [comment]
Great, thanks!
