### ISSUE TITLE
Ability to set delimiter for imported scv redirects

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-retour#188]
Importing redirects from CSV works only with comma as delimiter. This causes problems with some URL i import, because these URLs contain commas too. Ability to switch from using comma to semicolon would be very useful.

**Comment by piotrpog** [comment]
Just to add one fact - it appears that ms excel by default generates SCV files with commas and this causes problems when we try to use them with retour.

**Comment by khalwat** [comment]
That's probably a localization thing; the US version of Excel does indeed output comma-separated files by default.

It's very likely a setting in Excel that can be changed.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/dea1363f1a69eceb895345ddcd13032e40c1c2f4

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.55”,
```
Then do a `composer clear-cache && composer update`
