### ISSUE TITLE
"Strip Query String from Statistics" option removes query string from captured 404s on dashboard

### ISSUE THREAD

**Issue by mijewe** [nystudio107/craft-retour#189]
### Describe the bug
When you hit a 404, Retour saves that 404 into the dashboard, which you can then set up a redirect for.

If I have "Strip Query String from Statistics" off, I would expect the 404s listed in the dashboard to still have the query strings on.

This is so that I can capture 404s with unique query strings and handle their redirects separately.

sidenote: the qs redirection functionality works fine, this is just relating to the listing of captured 404s.

### To reproduce
Steps to reproduce the behaviour:
1. Turn off "Strip Query String from Statistics" from the Retour settings
2. Hit a 404 page with a query string (eg site.com/ejwjfjewa?test=123
3. Notice in the Retour dashboard that the captured 404 does not have the query string

### Expected behaviour
I would expect the query string to be preserved with the URL in the dashboard

### Versions
- Plugin version: 3.1.54
- Craft version: Craft Pro 3.6.16

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/bfa654c31bb92028698b08f0963a4d882967f836

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.55”,
```
Then do a `composer clear-cache && composer update`
