### ISSUE TITLE
No indicator of filtered overview page

### ISSUE THREAD

**Issue by jripmeester** [nystudio107/craft-retour#190]
### Describe the bug
When using the search function and return to the overview after viewing the detail page of an redirect item, the overview consists of the filtered results but the search bar is empty. This gives the feeling that the page isn't filtered. My client and myself got into panic mode to realise 10 minutes later the overview was filtered.

### To reproduce
Steps to reproduce the behaviour:
1. Go to the redirects overview page and search something
2. Visit a detail page of a redirect item
3. Return to the redirect overview page.

### Expected behaviour
Overview is still filtered (love this and should work like this everywhere in Craft ;-)) but there is an inidcator that the overview is filtered.

### Screenshots
<img width="1002" alt="Schermafbeelding 2021-07-05 om 20 59 26" src="https://user-images.githubusercontent.com/432051/124510450-1c262800-ddd4-11eb-973c-a833a73c193e.png">

### Versions
- Plugin version: 3.1.55
- Craft version: 3.6.17

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/de79912425cafb06a5ccbbe54a29243ce2dec8b0

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.56”,
```
Then do a `composer clear-cache && composer update`

**Comment by darylknight** [comment]
There is no reset button, as the search bar isn't showing:

![image](https://user-images.githubusercontent.com/1250017/124762589-bce32780-df3b-11eb-8b10-95680f2a36c4.png)

**Comment by khalwat** [comment]
Released as 3.1.56 -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.56
