### ISSUE TITLE
Site's Base URL isn't honoured in Retour dashboard UI

### ISSUE THREAD

**Issue by howells** [nystudio107/craft-retour#192]
### Describe the bug
You fixed a problem I had where the redirection urls weren't honouring a site's base url (#159), but the same issue occurs with the dashboard. 

### To reproduce
Steps to reproduce the behaviour:

1. Set up Craft on a subdomain e.g. cms.domain.com
2. Set default site's base url the actual client, e.g. www.domain.com
3. Click a url in the dashboard: URL that is opened is cms.domain.com/source

### Expected behaviour
The URL should be www.domain.com/source

### Versions
- Plugin version: 3.1.57
- Craft version: 3.6.17

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/2ba46e7638a14c90e39c01b478e5bb7a6bcfcd91

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.58”,
```
Then do a `composer clear-cache && composer update`
