### ISSUE TITLE
Cannot see any redirects in list as throwing error in getting JSON result

### ISSUE THREAD

**Issue by CIPLNitesh** [nystudio107/craft-retour#197]
Hello Team,

We have implemented whole site in Craft CMS 3.x and we have used retour plugin to manage redirects in website. 

We are getting an error in fetching data for retour redirects list. It always shows blank screen but we can add and export redirects. When we have checked in browser console then it shows an error of plugin's get method due to URL have some invalid values. 

Please check attached screenshot for the same. 
In attachment you can see "%257C" and due to that it throws an error. But when we will run that manually by replacing "%257C" to "|" then it gives us proper JSON result. 

Please let us know what we have to do in this as client is facing this issue since long and we have tried to uninstall and install plugin multiple time but no luck to resolve this issue. Now client is getting frustrated with this because client has paid for this and it should not throw such error when the plugin is paid. 

Due to some technical issue we cannot add attachment but it throws an error due to below URL.
`/admin/actions/retour/tables/dashboard?sort=redirectSrcUrl%257Casc&page=1&per_page=20&siteId=0`
In above URL you can see "%257C" and due to that it causes an error. It should be "|"

Can you guys please help us ASAP so we can resolve this issue?

**Versions**

- Craft CMS 3.5.5

- Retour 3.1.41 - Licensed version

**Comment by khalwat** [comment]
@CIPLNitesh can you update to the latest version? The current version is 3.1.57 -- the issue may already be fixed.

**Comment by CIPLNitesh** [comment]
Hey @khalwat 
Thanks for your feedback. 

We have tried to update the plugin but still we are facing the same issue. Cannot see list of redirections in Dashboard due to URL issue. 

Now the plugin version is 3.1.57. Can you please let us know any other way around to overcome this issue? As we are getting frustrating from this issue and client also. 

Thanks in advance for another feedback.

**Comment by khalwat** [comment]
Do you have any rewrite rules in your `.htaccess` or Apache/Nginx config files that could be interfering here?

It looks to me like the string is being doubly encoded.

**Comment by CIPLNitesh** [comment]
Hey @khalwat 
Thanks for your feedback.

We have double check our `.htaccess` file and also providing you here so you can double check it. But there is no anything suspicious which can cause such issue. 

Please have a look [htaccess.htaccess](https://rikin-my.sharepoint.com/:u:/g/personal/kushan_conceptinfoway_com/EYqoehnHlbZMm8onWT_RiY0B4veLPBXGfreN1stAEc3aEA?e=A9Q9dG) 
Provide your thoughts on this. We are still facing an issue and client is now really frustrating.

**Comment by CIPLNitesh** [comment]
Hey @khalwat 
Thanks for your feedback.

We have double check our `.htaccess` file and also providing you here so you can double check it. But there is no anything suspicious which can cause such issue.

Please have a look [htaccess.htaccess](https://rikin-my.sharepoint.com/:u:/g/personal/kushan_conceptinfoway_com/EYqoehnHlbZMm8onWT_RiY0B4veLPBXGfreN1stAEc3aEA?e=A9Q9dG)
Provide your thoughts on this. We are still facing an issue and client is now really frustrating.

**Comment by khalwat** [comment]
I believe this issue is due to a misconfiguration on your end, what's happening is the incoming URL is being double-encoded.

Your `.htaccess` file is not the default that Craft provides: 

https://github.com/craftcms/craft/blob/main/web/.htaccess

```apache
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Send would-be 404 requests to Craft
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
    RewriteRule (.+) index.php?p=$1 [QSA,L]
</IfModule>
```

I'm guessing that the issue is with this block:

```apache
<IfModule mod_rewrite.c>
	RewriteEngine On
	# Remove index.php
	RewriteCond %{THE_REQUEST} ^GET.*index\.php [NC]
	RewriteCond %{REQUEST_URI} !^/index\.php/admin\b [NC] # Don't mess with admin requests
	RewriteRule (.*?)index\.php/*(.*) /$1$2 [R=301,NE,L]
	# remove ?p=
	RewriteCond %{THE_REQUEST} ^GET\ /\?(([^&\s]*&)*)p=([^&\s]+)&?([^\s]*)
	RewriteRule ^(.*)$ /%3?%1%4 [L,R=301]
</IfModule>
```

...or it could be this rule:

```apache
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]

```

...or the order in which they are being applied. I can't test this locally, because I don't have your setup here, but I'd suggest trying removing these blocks to see if the problem goes away. If it does, then you'll need to refactor them.

**Comment by CIPLNitesh** [comment]
Hey @khalwat 
Thank you very much for your help.

We will change this .htaccess change and then check and let you know if anything. But again thanks for your all support.
