### ISSUE TITLE
Custom Delimiter for import not working in the retour-import-dragArea

### ISSUE THREAD

**Issue by maxstrebel** [nystudio107/craft-retour#199]
### Describe the bug
I changed the custom delimiter to `;`. When I import a CSV with `;` as delimiter, the import screen looks as attached.

### To reproduce
Steps to reproduce the behaviour:
1. Set custom delimiter to `;` in the settings
2. Go to "CSV import"
2. Import CSV with `;` separated columns
3. See the attached import screen (where you can't map the fields)

### Expected behaviour
The Mapping List should accept `;` delimited table columns

### Screenshots

![image](https://user-images.githubusercontent.com/910594/130264281-02311530-91db-4d7b-9613-fd712401f991.png)

![image](https://user-images.githubusercontent.com/910594/130264314-8c86a6bf-c373-4954-9ec4-926f74f76f93.png)

### Versions
- Plugin version: 3.1.61
- Craft version: 3.7.10

**Comment by khalwat** [comment]
Can you please attach an example CSV file that fails for you?

**Comment by maxstrebel** [comment]
[000_retour-redirects.csv](https://github.com/nystudio107/craft-retour/files/7022918/000_retour-redirects.csv)

sure, one dummy import. Sorry.

**Comment by maxstrebel** [comment]
If you remove the custom delimiter and change it to commas, it works

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/fe879d184b4d94d3c35785ff209967ed2c8ba3a8

Released as 3.1.61 -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.61
