### ISSUE TITLE
Incorrect path for js and css files in admin panel

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-retour#20]
Tested on windows based xampp, with clean install of latest craft. Retour tries to load css and js files with wrong path. Result is retour pages appearing blank, without any functionality.

This is path retour tries to load use example file:
http://localhost/cpresources/retour/js/dashboard.66dfb269ddbef4138c0a.js

This is what it should look like:
http://localhost/craft_install/web/cpresources/retour/js/dashboard.66dfb269ddbef4138c0a.js

**My system info:**

PHP version	7.2.2
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.2.2
Craft edition & version	Craft Solo 3.0.24
Yii version	2.0.15.1
Twig version	2.5.0
Guzzle version	6.3.3
Imagine version	0.7-dev

**Comment by khalwat** [comment]
So that path that its trying to load things from is actually correct. There is a frontend route set up to redirect `/cpresources/retour` to the correct place for the published Asset Bundle. The question is, why is this not working?

Are you sure there isn't potentially an issue with the local dev setup?

**Comment by piotrpog** [comment]
No, this cannot be problem with my local setup. I just installed retour on shared hosting (linux based, compared to windows on my localhost) and result was the same. 

Can you tell me where would i have to look for this frontend route to verify if it works correctly?

**Comment by khalwat** [comment]
The frontend route is `/cpresources/retour/` -- anything matching that should be caught by Retour, and redirected to the appropriate controller. The route you listed:

```
http://localhost/cpresources/retour/js/dashboard.66dfb269ddbef4138c0a.js
```
...looks correct, except it's lacking the `craft_install/web/`, which is what makes me think that it could be a local dev setup issue. The URL it actually is using is just:

```
/cpresources/retour/js/dashboard.66dfb269ddbef4138c0a.js
```
...which should resolve to the correct host.

Can you show me what it looks like on the Linux host that you set up?

**Comment by piotrpog** [comment]
On linux host, it tries to download for example such file:
`domain.com/cpresources/retour/js/redirects.4e2f56321d5d9ba8af4e.js`
So, it skips 'web' folder.

Side note - when I install retour, when its dashboard opens for first time, i see "Thanks for using Retour!
" - but when i refresh it or open other subpages - its broken, as I described above.

**Comment by khalwat** [comment]
It should be skipping the `web` folder though, that's typically the web root, and not in the URL itself. Perhaps you're not pointing the webserver at the actual web root?

**Comment by khalwat** [comment]
This URL:

```
domain.com/cpresources/retour/js/redirects.4e2f56321d5d9ba8af4e.js
```
...looks entirely correct to me, that's what it should be attempting to load.

**Comment by piotrpog** [comment]
Well in my case, craft install is in subfolder, domain doesnt direct towards /web folder. Do you mean that retour wont work otherwise? I never had problems with any other craft plugins over such issue.

**Comment by khalwat** [comment]
Just I'm clear in understanding how you have it set up, you had the web server root, and the craft is installed in a sub-folder inside of that server root?

I can try to set up a test case to attempt to replicate the issue locally, if you can let me know how you have this all structured?

**Comment by piotrpog** [comment]
This is for example my setup on windows that didnt worked:
`c:/xampp/htdocs/craft_install/`
Domain localhosts is assigned to `c:/xampp/htdocs`, so when i visit `localhost/craft_install/web`, it didnt worked.
Same for remote server, when i visit `domain.com/craft_install/web`, it didnt worked.

Also, i just tested retour on setup when domain `root `directs to `web` folder, and it worked alright.

**Comment by khalwat** [comment]
Great, thanks, I think I know what is going on, and it's a little involved (it's the webpack async JavaScript module loading), but I can try to get a setup working here.

I'm traveling and at the `.all()` conference this week, so it may not be immediately, just FYI.

**Comment by piotrpog** [comment]
Just downloaded latest update, and it seems partially fixed. Static files load OK, but retour still tries to make some kind request using wrong address. These are errors i get in browser console from my xampp setup:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap:114 Uncaught (in promise) Error: Loading chunk 1 failed.
(error: http://localhost/cpresources/retour/js/vendors~confetti~vue.041de3ed3bfe9ec4fdba.js)
    at HTMLScriptElement.u (bootstrap:114)
```

**Comment by khalwat** [comment]
Right, so here's what is going on... Retour uses webpack to build the AdminCP assets. It uses dynamic code splitting and async bundle loading, which basically means that to load JS modules, it's actually webpack that loads them, not my code.

Webpack doesn't know anything about Craft or `/cpresources/` or the like, so I have the script sources set to be `/cpresources/retour/` and then I have a frontend route that handles redirecting to the appropriate published AssetBundle in `/cpresources/`

This all works great when Craft is the root website, but when it's installed in a sub-folder, `/cpresources/retour/` is going to be going to whatever the root website is.

I've still not worked out a good way to handle this "installed in a sub-directory" thing, because webpack doesn't know anything about any of this, but I have to prefix the URLs ahead of time when actually building the assets. So it's a bit of a conundrum.

**Comment by khalwat** [comment]
@piotrpog if you set up a redirect in your base setup such that anything going to `/cpresources` redirects to Craft, that should fix the situation here. I realize it's a bit ironic to set up a redirect for a plugin that handles redirects, though...

**Comment by vieko** [comment]
in case anyone running nginx runs into this issue, adding the directive below to my site's config solved it for me:

```
location ^~ /cpresources {
	try_files $uri $uri/ /index.php?$query_string;
}
```

**Comment by rungta** [comment]
Just ran into this issue myself. I have a bunch of Craft sites installed as subfolders and adding manual redirects for root `/cpresources` requests to one particular Craft install subfolder does not seem like a scalable approach.

Hope you’re able to figure out a native solution for arbitrary base paths in your webpack builds @khalwat.

**Comment by jwmatlock** [comment]
This just started happening to a site we're running yesterday. The Retour pages were working correctly, but then they started to load up empty. Looks like it's getting a 404 looking for those .js files. Not sure what would have changed on our end.

**Comment by khalwat** [comment]
@jwmatlock see if this helps? https://github.com/nystudio107/craft-retour#retour-admincp-pages-are-blank

It is likely a change on your end.

**Comment by jwmatlock** [comment]
@khalwat It was on our end. We made a change to the app.php file and that seemed to have caused the issue.

**Comment by khalwat** [comment]
What was the change, just so that I can understand it @jwmatlock ?

**Comment by jwmatlock** [comment]
@khalwat 
Our original app.php looked like the default:

```
return [
	'modules' => [
			'my-module' => \modules\Module::class,
	],
	//'bootstrap' => ['my-module'],

];
```

but then we changed it to look like:

```
return [
	'bootstrap' => ['debug'],
     'modules' => [
        'debug' => [
            'class' => 'yii\debug\Module',
            // uncomment and adjust the following to add your IP if you are not connecting from localhost.
            'allowedIPs' => ['**.***.**.***'],
        ]
    ]
 ];
```

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/ff770facc29e00eafe938ae6b092a5f80e81ae3f

**Comment by piotrpog** [comment]
@khalwat many thanks!

**Comment by khalwat** [comment]
Glad to have it working for you!
