### ISSUE TITLE
siteId is not shown for captured redirect_stats 

### ISSUE THREAD

**Issue by toyflish** [nystudio107/craft-retour#201]
### Describe the bug
on requesting retour for uri and siteId the uri and siteId are stored in the retour_stats table with correct uri but siteId seems always default to 1

    query Retour {
      retour( uri:"/some_uri", siteId: 4) {
        redirectDestUrl
      }
    }

retour_stats
| redirectSrcUrl | siteId |
| ------ | ------ |
| /some_uri | 1 |

when I click the add button for creating a redirect the Site-selector always shows "All Sites" and not the (falsly stored) site with siteId: 1 or even better the requested site with siteId 4 

### Expected behaviour
- siteId or site-name according to the redirect-stats should be shown in the stats
- on "Add" the corresponding site that the uri was requested with should be preselected in the redirect form

### Versions
- Plugin version: 3.4.7
- Craft version: 3.7.12

**Comment by khalwat** [comment]
Right you are. It was recording it based on the current site ID, which isn't correct for headless requests.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/263a8812b097e6d6a5d5c3bf88e0823789477365

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.62”,
```
Then do a `composer clear-cache && composer update`

**Comment by toyflish** [comment]
thanks @khalwat for jumping on that, that quick.
I upgraded the plugin and the retour_stats table holds the right siteId now, but for the user on the retour dashboard it is invisible what site this uri is having 404 with. So he just can figure it out by doing an csv export. And if I create a redirect directly it defaults to do one not site specific.

**Comment by khalwat** [comment]
I believe the default behavior is to "all" when adding a redirect. I think what I can do, though, is if the siteId is anything _other_ than the primary siteId, I can have it default to adding it for that site.

The default is for it to be set to "all" because in most cases, that's probably what you want.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/ee2f7c9ff1868711952505d5b3d36375fd312f5b

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.62”,
```
Then do a `composer clear-cache && composer update`
