### ISSUE TITLE
UnavailableStream -  failed to open stream: No such file or directory.

### ISSUE THREAD

**Issue by toddpadwick** [nystudio107/craft-retour#204]
I am trying to import a CSV to Retour. I managed fine the first time, but then the second time I uploaded a CSV of a different name, it returns the below stack trace error. I tried the following:
- Run craft gc
- clear all caches
- changed the file name
- changed the temporary files storage location from local files to the S3 volume we're using

Still seeing the same error which was especially surprising after the last fix attempt (s3 temp storage location).
Any ideas how I can solve this? We're due to launch a clients site tomorrow and I need to get all the redirects uploaded from the previous site 😬

```
League\Csv\UnavailableStream: `/srv/app/positive-prod/htdocs/storage/runtime/temp/Pages-Table-5.csv6176a40462a8e1.91133498`: failed to open stream: No such file or directory. in /srv/app/positive-prod/htdocs/vendor/league/csv/src/UnavailableStream.php:25
Stack trace:
#0 /srv/app/positive-prod/htdocs/vendor/league/csv/src/Stream.php(196): League\Csv\UnavailableStream::dueToPathNotFound('/srv/app/positi...')
#1 /srv/app/positive-prod/htdocs/vendor/league/csv/src/AbstractCsv.php(168): League\Csv\Stream::createFromPath('/srv/app/positi...', 'r', NULL)
#2 /srv/app/positive-prod/htdocs/vendor/league/csv/src/Reader.php(75): League\Csv\AbstractCsv::createFromPath('/srv/app/positi...', 'r', NULL)
#3 /srv/app/positive-prod/htdocs/vendor/nystudio107/craft-retour/src/controllers/FileController.php(104): League\Csv\Reader::createFromPath('/srv/app/positi...')
#4 [internal function]: nystudio107\retour\controllers\FileController->actionImportCsvColumns()
#5 /srv/app/positive-prod/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /srv/app/positive-prod/htdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#7 /srv/app/positive-prod/htdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('import-csv-colu...', Array)
#8 /srv/app/positive-prod/htdocs/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('import-csv-colu...', Array)
#9 /srv/app/positive-prod/htdocs/vendor/craftcms/cms/src/web/Application.php(276): yii\base\Module->runAction('retour/file/imp...', Array)
#10 /srv/app/positive-prod/htdocs/vendor/craftcms/cms/src/web/Application.php(585): craft\web\Application->runAction('retour/file/imp...', Array)
#11 /srv/app/positive-prod/htdocs/vendor/craftcms/cms/src/web/Application.php(255): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /srv/app/positive-prod/htdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /srv/app/positive-prod/htdocs/web/index.php(21): yii\base\Application->run()
#14 {main}

```

**Comment by khalwat** [comment]
What is the attached error?

**Comment by toddpadwick** [comment]
oh sorry @khalwat, i forgot to paste in the error 🤦‍♂️. ive updated the post now.

**Comment by khalwat** [comment]
What is your caching method set to, and what is your temporary directory set to?

It looks to me like it is unable (for whatever reason) to upload the file to a temporary directory, which it needs to do before it can read and parse the CSV file.

This is likely due to some kind of local setup issue.

**Comment by toddpadwick** [comment]
it uploaded the first CSV fine. this was set to local directory as default craft does. when i uploaded the second csv the error appeared. nothing was changed in between. 
i now changed the temporary file location to /temp in our S3 bucket which works fine for everything else (asset uploads etc). 
caching is using memcache with Fortrabbit https://help.fortrabbit.com/memcache-pro

**Comment by khalwat** [comment]
Yeah I don't think your S3 bucket is likely the best place for temporary files; I'd set it back to the default (no setting)

**Comment by khalwat** [comment]
Here's what it does when you upload a file: <https://github.com/nystudio107/craft-retour/blob/develop/src/controllers/FileController.php#L208>

- It generates a unique name for the file
- It saves the file into the directory pointed to by `Craft::$app->getPath()->getTempPath()`
- It then also caches the file's contents in the cache using the filename as the key

Then it passes in the full file path into the next controller, which: <https://github.com/nystudio107/craft-retour/blob/develop/src/controllers/FileController.php#L101>
- Tries to read the file contents from the cache
- If that fails, tries to read it from the disk

I'd check your `web.log` for errors, it seems odd to me that neither the file on disk nor the file in the cache would be readable.

**Comment by khalwat** [comment]
Any luck @toddpadwick ?

**Comment by ostark** [comment]
> Tries to read the file contents from the cache
> If that fails, tries to read it from the disk

If I read the code correctly, it does not happen in that order:
https://github.com/nystudio107/craft-retour/blob/develop/src/controllers/FileController.php#L101-L130

In @toddpadwick's report, the error was triggered in line 104 with `Reader::createFromPath($filename);`
-> down the rabbithole: https://github.com/thephpleague/csv/blob/master/src/Stream.php#L195-L198

Assuming the file does not exist (e.g. in a multi-node environment), `League\Csv\Reader` will throw an error and you never reach the point of the cache-fallback.

(correct me if I'm wrong)

**Comment by khalwat** [comment]
@ostark What is the reason it would be unable to create a file in the temporary directories?

**Comment by ostark** [comment]
>  unable to create a file 

This would fail in the first step, right? (not the case)

Todd's scenario is different: Imagine the file system is not shared between the HTTP nodes. That's not uncommon "in the cloud", e.g. with fortrabbit pro stack, heroku or raw load balanced ec2. The first request writes to server A and the second request tries to read from server B.

**Comment by khalwat** [comment]
He's going to run into other problems if some of those directories are not shared amongst the load balanced nodes

Doing otherwise goes against P&Ts recommendations, and certain other things may fail as well

￼ https://craftcms.com/knowledge-base/configuring-load-balanced-environments#storage-folder

**Comment by ostark** [comment]
I'm not aware of other problems :-)

**Comment by khalwat** [comment]
Addressed via PR: https://github.com/nystudio107/craft-retour/pull/205

**Comment by khalwat** [comment]
Released as 3.1.64 -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.64

**Comment by toddpadwick** [comment]
Thanks for sorting that so quick @khalwat

**Comment by khalwat** [comment]
All credit to your hosting partners at ForRabbit on this one! @ostark is the best

**Comment by toddpadwick** [comment]
Agreed @khalwat - @ostark has gone above and beyond many times! We've been using Fortrabbit for years now - they're great.
