### ISSUE TITLE
Redirects index page shows wrong URL

### ISSUE THREAD

**Issue by jimmylorunning** [nystudio107/craft-retour#206]
### Describe the bug
Created a redirect and it works fine. However, on the main redirects index page, under the "Redirect to" column, it shows: /locations/1 instead of /locations/$1

### To reproduce
Create the following redirect

Legacy URL pattern: ^/branches/(.{4})$
Match type: Path Only
Destination URL: /locations/$1
Match type: RegEx Match
Type: 302

Go to redirects index page, and look under the "Redirect to" column.

### Expected behaviour
Should see /locations/$1

### Screenshots
<img width="224" alt="creation_screen" src="https://user-images.githubusercontent.com/6257037/139684035-c53bbe21-2b36-46a5-b8d1-f813a6426a7a.png">

<img width="335" alt="index_screen" src="https://user-images.githubusercontent.com/6257037/139684072-d97d9036-4ad6-40ac-90c3-7cfb37a80aff.png">

### Versions
- Plugin version: 3.1.63
- Craft version: 3.7.17.2

**Comment by jimmylorunning** [comment]
FYI, just updated to Craft 3.7.18.2 and Retour 3.1.65 and still seeing the bug. Thanks,

**Comment by khalwat** [comment]
Confirmed, I see it here as well. It appears to be a cosmetic issue

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/073c3876d3accb0e764b4e2e72adc536d5357dea

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.66”,
```
Then do a `composer clear-cache && composer update`
