### ISSUE TITLE
Possible to block one or more hostname(s) per redirect

### ISSUE THREAD

**Issue by gtettelaar** [nystudio107/craft-retour#21]
Is there a way to block redirects from happening based on user defined host names when editing or adding redirects. 

For example on a multi-site setup if you have two sites setup: 

- myotherdomain.com
- mydomain.com

and a redirect setup as follows

- /vhs redirecting to /netflix

That when hitting mydomain.com/vhs you do redirect but when hitting myotherdomain.com/vhs you don't redirect and it shows the 404. I imagine on more complex multi site setups this might be interesting. 

This issue might coincide with #5  so i don't know if something such as this is already in the pipeline. 

Full disclosure I basically figured out and developed a way to do this for this over at [https://github.com/lemiwinkz/craft-retour/tree/develop](url) so iam just curious if there is a native way for doing this that might be better or something is already being developed. If not i can submit a PR.

**Comment by khalwat** [comment]
Yep, it'll be something that we'll be doing here: https://github.com/nystudio107/craft-retour/issues/12
