### ISSUE TITLE
Automatic redirects not working with multisite

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft-retour#210]
### Describe the bug
Automatically created Entry Redirects matched by path works only on default site

### To reproduce
Steps to reproduce the behaviour:
1. Install fresh Craft and Retour
2. Set `Entry Redirects URL Match Type` Retour option to `Path only`
2. Add a few subsites [/, /nl, /de]
3. Add a new channel for all subsites
4. Add new page
5. Open a new page on Dutch site in browser [site.loc/nl/new-page]
5. Try to change slug of this page
6. Reload browser page [site.loc/nl/new-page] - page should've redirected to new URL, but it's not happens

### Expected behaviour
The page should be redirected to a new url.
P.. Also tried with `Entry Redirects URL Match Type = Full url`. In this case, all work like expected

### Screenshots
![изображение](https://user-images.githubusercontent.com/496132/141329966-6bdda821-4af7-462b-a87b-67a6faef2511.png)
![изображение](https://user-images.githubusercontent.com/496132/141330154-022041af-b0e0-474b-874b-aa31df1ab34c.png)
![изображение](https://user-images.githubusercontent.com/496132/141330312-f96ba2b9-5b4b-4d1a-bba1-d70581913832.png)
![изображение](https://user-images.githubusercontent.com/496132/141330373-381498b5-e82c-464b-920e-821e64a07a29.png)
![изображение](https://user-images.githubusercontent.com/496132/141330452-2b0a8e59-3345-48dc-96f1-101ceb0905e2.png)
![изображение](https://user-images.githubusercontent.com/496132/141330519-edc376af-7040-4969-9d08-ef226651253a.png)
![изображение](https://user-images.githubusercontent.com/496132/141330573-4460b840-c503-45cd-974a-5395f3a49ad2.png)

### Versions
- Plugin version: 3.1.66
- Craft version: 3.7.20

Thanks

**Comment by khalwat** [comment]
Depending on how your sites are set up "path only" won't work for localized sites, because the site name is part of the path.

Switching it to `Entry Redirects URL Match Type = Full url` as you did is the work-around for this.

lmk if you think something isn't right with this behavior.

**Comment by umkasanki** [comment]
@khalwat 
Could you show the working sample of localized sites setup that works with `path only redirect`?
