### ISSUE TITLE
CSV import as a console command?

### ISSUE THREAD

**Issue by teekay** [nystudio107/craft-retour#211]
### Is your feature request related to a problem? Please describe.
I wonder if the CSV redirects import could be automated? We have a number of environments, and would potentially benefit if we don't have to run the import manually on each one of them. If there were a console command, we could make it a part of the deployment setup.

### Describe the solution you would like
A command that can be called from CI/CD that would perform the redirects import from an arbitrary CSV file

### Describe alternatives you have considered
The only other alternative is to import the redirects once, generate a SQL dump of `retour_static_redirects`, and load the SQL import instead. Come to think of it, this solution is also workable.

### Additional context
I realize that specifying the CSV column mapping in the context of a console command might not be ideal

**Comment by khalwat** [comment]
Right, I thought about doing this but not having a decent way to match columns up is the impediment.

You can just do the table dump as you describe, which might actually work out better in some ways (you're able to verify things are working as expected on an environment before pushing to production).
