### ISSUE TITLE
non-ASCII characters stripped from "Redirect To" links in retour’s redirects list

### ISSUE THREAD

**Issue by circa1983** [nystudio107/craft-retour#213]
### Description
Non-ASCII characters are stripped from the href and link text displayed in the "Redirect To" column of the control panel `/admin/retour/redirects`. Both being stripped means the links don’t display correctly, aren’t searchable and the links don’t work. 

This is only an issue with the links in the CP, the redirect saves correctly and redirects any users visiting the legacy url but it’s just confusing for the editor and we’ve had a couple of requests to look into it from our clients.

Links like the example below (the Hungarian word for welcome, üdvözöljük) are just about manageable because they _do_ contain some ASCII characters but langauges made completely from non-ASCII characters, like Korean (환영하다) total fail.

### To reproduce
1. Go to `/admin/retour/redirects`
2. Add a "New Static Redirect"
    - Set Legacy URL Pattern to any url eg: `/legacy-url/üdvözöljük`
    - Set the Destination URL to something with non-ASCII characters eg: `/destination-url/üdvözöljük`
    - Save redirect and return to redirects listing `/admin/retour/redirects`
3. See incorrect link in "Redirect To" column

### Expected behaviour
The "Redirect To" href and text to include the non-ASCII characters added to the "Destination URL" string

### Screenshots

**Example Input**:

<img width="663" alt="non-ASCII characters added to redirect" src="https://user-images.githubusercontent.com/6949584/145232989-b974f375-3eb4-418a-b992-ddb68f37e568.png">

**Example Issue**:

<img width="764" alt="example of missing non-ASCII characters" src="https://user-images.githubusercontent.com/6949584/145235127-7f3cb90c-2a47-4aef-8b15-584d13997591.png">

### Versions
- Plugin version: 3.1.67
- Craft version: Craft Pro 3.7.24

Sorry, I realise this is most likely a pain because the Destination URLs can contain regex, so there is likely a lot of processing to get these links to display and function correctly! Thanks for the plugin, it’s ace and thanks for looking into this for us!

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/ffad7551001752098a08d380d4238b891db959b9

<img width="397" alt="Screen Shot 2021-12-08 at 3 11 00 PM" src="https://user-images.githubusercontent.com/7570798/145277996-ab2e01cc-0460-464e-9819-efd3a9d51911.png">

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.68”,
```
Then do a `composer clear-cache && composer update`

**Comment by circa1983** [comment]
Thank you Andrew, you fixed that far faster than I was expecting and it works perfectly
