### ISSUE TITLE
Dashboard search keywords get reverted when using filter dropdown

### ISSUE THREAD

**Issue by nickdunn** [nystudio107/craft-retour#214]
### Describe the bug
When on the dashboard searching through handled/not-handled redirects, if you use a search keyword and then reset to clear it, the keyword is still used in the background, but not in the UI.

### To reproduce
Steps to reproduce the behaviour:
1. Go to the Dashboard and enter a search term e.g. `jpg`, see the list correctly update
2. Clear the search term using the "Reset" button and see the list correctly update. At this point the object in `retour-dashboard-state...` in localstorage is correct.
3. Change the "All" dropdown to "Handled" and see incorrect results.

At this point, `"filter": "jpg"` has gone back into the state in local storage:

![image](https://user-images.githubusercontent.com/39560/145421815-0646eb19-a2df-4673-952f-b3b015b587f5.png)

But the keyword is still cleared in the UI:

![image](https://user-images.githubusercontent.com/39560/145422007-42365975-dc45-4953-b2c1-3e047834bb81.png)

### Expected behaviour
When clearing the keyword with a Reset, it should be gone gone :-)

### Versions
- Plugin version: 3.1.67

**Comment by nickdunn** [comment]
This can also be replicated by:

* Enter `jpg`, then "Reset"
* Refresh the page. It's back!

**Comment by khalwat** [comment]
Fixed in: https://github.com/nystudio107/craft-retour/commit/61c7a9e975283131c90568fc2302ec283f1fe607

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.68”,
```
Then do a `composer clear-cache && composer update`
