### ISSUE TITLE
Ability to choose a 308 redirect type

### ISSUE THREAD

**Issue by louderthan10** [nystudio107/craft-retour#216]
### Is your feature request related to a problem? Please describe.
308s are similar to 301s, except that [it does not allow changing the request method from POST to GET](https://stackoverflow.com/questions/42136829/whats-the-difference-between-http-301-and-308-status-codes#:~:text=status-code-308-,What's%20the%20difference%20between%20HTTP%20301%20and%20308%20status%20codes,be%20repeated%20using%20another%20URI.). 

### Describe the solution you would like
We would like to be able to choose 308 redirects (and maybe 307 while we're at it?) from the **Redirect Type** dropdown when creating a Redirect:

<img width="442" alt="Screen Shot 2021-12-21 at 11 16 15 AM" src="https://user-images.githubusercontent.com/49751/146986421-b134a3c0-465b-4249-9106-b899cb347269.png">

### Other resources
[308 redirects for SEO – Are they better than 301?](https://www.infidigit.com/news/308-redirects-for-seo-are-they-better-than-301/)

**Comment by khalwat** [comment]
Added in: https://github.com/nystudio107/craft-retour/commit/8e0ea61244ed55a14099d8e10564afa3708c69de

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.68”,
```
Then do a `composer clear-cache && composer update`
