### ISSUE TITLE
CSV Import Reports

### ISSUE THREAD

**Issue by mattsbanner** [nystudio107/craft-retour#219]
### Is your feature request related to a problem? Please describe.
Our client is importing redirects from a CSV, but does not receive any feedback on which lines were skipped when the redirect validation fails.

### Describe the solution you would like
We can see failed imports in the log, but an import report for our client to see would be helpful.

### Describe alternatives you have considered
Gathering data from the logs in a report for them, but would probably be nicer to have a solution within Retour.

**Comment by khalwat** [comment]
Added in: https://github.com/nystudio107/craft-retour/commit/4f0e962b8c6ff025cc5effe9fbde1519332c62ac & https://github.com/nystudio107/craft-retour/commit/aad7a06ed6664e6c9702c237b1d25cdccb35f231

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.0”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.0”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
You get frontend reports of any errors during CSV import now:

<img width="1261" alt="Screen Shot 2022-08-28 at 4 36 24 PM" src="https://user-images.githubusercontent.com/7570798/187093669-304f669e-3b16-4142-830f-14ee0febe451.png">

**Comment by mattsbanner** [comment]
@khalwat Thank you! 🚀
