### ISSUE TITLE
[FR] Select multiple redirects for deletion

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-retour#22]
Just like with entry list, we should have ability to select multiple redirects from list and remove them all.

**Comment by khalwat** [comment]
Ah yeah, that's a nice feature request. Maybe a checkbox next to it?

**Comment by piotrpog** [comment]
@khalwat that's what i had in mind.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-retour/commit/94b08d6c223e0b5a6da30b17e5f543a1d940362e
