### ISSUE TITLE
Retour appears in the sidebar for all users, when permission is unchecked

### ISSUE THREAD

**Issue by darylknight** [nystudio107/craft-retour#220]
### Describe the bug
I'd assume this is a Craft thing, except it's only happening to Retour. On a site where we have a reviewer group, Retour appears in the sidebar even though it's unchecked under permissions:

Testing (using Freeform as a control):
Permissions:
![image](https://user-images.githubusercontent.com/1250017/152136265-b2fc49de-31a8-4ccd-85ad-d08b8fdb79f9.png)
Result:
![image](https://user-images.githubusercontent.com/1250017/152136432-615a347b-3568-4512-90db-c7aa7fa5e6dc.png)

Result after removing both:
Permissions:
![image](https://user-images.githubusercontent.com/1250017/152136347-d331c1bb-136c-4ef0-943f-e8f21d7ab68f.png)
Result:
![image](https://user-images.githubusercontent.com/1250017/152136380-276ee3fb-5688-4b4d-bb9d-3fd34658c5f7.png)

### To reproduce
Steps to reproduce the behaviour:
1. Disable the permission for someone to see Retour in the control panel
2. Login as that user group
3. Retour is still in the sidebar

### Expected behaviour
Retour should not be in the sidebar

### Versions
- Plugin version: 3.1.70
- Craft version: Craft CMS 3.7.30.1

**Comment by khalwat** [comment]
Screenshot of the Retour permission settings for this user group?

**Comment by darylknight** [comment]
![image](https://user-images.githubusercontent.com/1250017/152234458-7d7aba5a-87a4-4871-ba13-74dc0a4c53c4.png)

Also double checked that the test user in question doesn't have user-specific permissions, just the user group inherited ones

**Comment by darylknight** [comment]
False alarm, sorry - looks like Control Panel Nav is the culprit.
