### ISSUE TITLE
Improve translatable strings

### ISSUE THREAD

**Issue by michaelhue** [nystudio107/craft-retour#222]
### Is your feature request related to a problem? Please describe.
I have created a custom German translation for the plugin. However, many parts of the templates cannot be translated. This concerns basically every text on the **Dashboard** and **Redirects** page.

### Describe the solution you would like
I'd love to be able to translate any message used in the plugin.

Thank you for this awesome plugin!

**Comment by ajoliveau** [comment]
I would need this as well !
We have a client that is very serious about having his whole CMS in french, and it's a pity we can't translate this ourselves :)

**Comment by khalwat** [comment]
So the tough part here is that much of that is done via frontend JavaScript, so you can't leverage the Craft translations directly, but I can think of a few ways around that.

**Comment by khalwat** [comment]
I've figured out how to do this in Craft:

```twig
{% do view.registerTranslations('app', [
    'No GraphQL tokens exist yet.',
    'Never',
    'Last Used',
    'Expires',
]) %}
```

So good news! I will let you know when it is set.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/7f7339d052617c251436e04c2281ba8a7c601d22 & https://github.com/nystudio107/craft-retour/commit/11740092482302fc1cefe5fbfd85cc63e8baac36

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.0”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.0”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
I believe I got all of the strings that need localization, but let me know if you find any missing.

Also, if you do end up localizing Retour into your native language, I'd love it if you could get the translation to me (via PR or email) so I can incorporate them in!
