### ISSUE TITLE
Not Redirecting

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-retour#223]
### Describe the bug
Adding a redirect to retour does not result in a redirect on the front end of the site. Site is currently unable to upgrade to latest Craft due to server restrictions. It's on Craft 3.5.19.1 and Retour 3.1.46

### To reproduce
Steps to reproduce the behaviour:
1. Go to "retour/redirects"
2. Click on "new static redirect"
3. add redirect (see screenshot) and save

### Expected behaviour
front end should redirect to indicated page but nothing happens

### Screenshots
![Screenshot 2022-03-16 113155](https://user-images.githubusercontent.com/6899490/158627650-95b9f92f-cdf8-49b4-8959-7d31632bdf9f.png)

### Versions
- Plugin version: 3.1.46
- Craft version: 3.5.19.1

**Comment by khalwat** [comment]
That's because https://www.compugen.com/en/about/green-initiatives does not generate a `404`

Retour only kicks in when Craft CMS has thrown a 404 error: https://nystudio107.com/docs/retour/whyretour.html
