### ISSUE TITLE
Retour causing an error when opening the user page in craft 4 beta.

### ISSUE THREAD

**Issue by aodihis** [nystudio107/craft-retour#224]
### Describe the bug
I have tried the craft cms 4 beta and also installed retour 4.0.0-beta.2, but I found an issue when we open the user detail page I got this error message
`An Error occurred while handling another error:
Twig\Error\RuntimeError: Key "heading" for array with keys "retour:dashboard, retour:redirects, retour:settings" does not exist. in /var/www/html/vendor/craftcms/cms/src/templates/_includes/permissions.twig:77
Stack trace:`

Look likes in craft 4 there are a behaviour change when registering the permission. Please refer to this [link](https://github.com/craftcms/cms/blob/4.0/CHANGELOG.md#:~:text=craft%5Cservices%5CUserPermissions%3A%3AgetAllPermissions()%20and%20getAssignablePermissions()%20now%20return%20permission%20groups%20as%20arrays%20with%20heading%20and%20permission%20sub%2Dkeys%2C%20fixing%20a%20bug%20where%20two%20groups%20with%20the%20same%20heading%20would%20conflict%20with%20each%20other.%20(%237771)).

So instead of registering like this :
`$event->permissions[Craft::t('retour', 'Retour')] = $this->customAdminCpPermissions();` 
We need to changed it into this  : 
`$event->permissions[] = [
                    'heading' => Craft::t('retour', 'Retour'),
                    'permissions' =>  $this->customAdminCpPermissions()
                ];`

### Versions
- Plugin version:4.0.0-beta.2
- Craft version: 4.0.0-beta.2

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/c2c499efc9426e86b20605df7755d0e9e758cc2f

Released as: `4.0.0-beta.3` -> https://github.com/nystudio107/craft-retour/releases/tag/4.0.0-beta.3

related: https://github.com/craftcms/docs/issues/352
