### ISSUE TITLE
Handled URLs showing on Dashboard as unhandled

### ISSUE THREAD

**Issue by mediagirl** [nystudio107/craft-retour#227]
### Question
I'm seeing URLs that should be displaying as "handled" on the Dashboard appearing as "not handled". These are URLs for which I have already added a Retour redirect and the redirect is working. This is on the latest version of Craft and Retour. The redirects are set up as exact matches and everything is correct as far as I can tell. Thoughts?

### Additional context
Add any other context or screenshots about the support request here.

**Comment by khalwat** [comment]
In order for them to be marked as "handled" a request would need to come in that results in a redirect.

I just did a quick test locally, and it's working as expected:

<img width="990" alt="Screen Shot 2022-04-01 at 3 57 40 PM" src="https://user-images.githubusercontent.com/7570798/161332982-7f52b0c8-aad5-44dc-a546-e41a5a68475b.png">
<img width="990" alt="Screen Shot 2022-04-01 at 3 57 49 PM" src="https://user-images.githubusercontent.com/7570798/161332984-ba872f03-1139-483d-b09e-07ba7fa16da3.png">

**Comment by mediagirl** [comment]
Okay… I see the issue and it looks like a small bug. Here’s an example URL.

Both these URL variations are coming through and logged on the dashboard:
/covid-19
/covid-19/

I set up my redirect as an exact match for “/covid-19”  -->  “/filmmaker-resources/set-safety”.

The redirect is working when testing BOTH url variations when clicking the link on the dashboard because the actual href being created/used for the “/covid-19/” link does NOT include the trailing slash even though it’s for the 404 entry with trailing slash. 

Does that make sense? If no, I can set up a quick screenshare to show you. My email is anna@mediagirl.com.

**Comment by khalwat** [comment]
Yep, if you have "Exact Match" selected as the redirect type, then it will have to be an exact match for it to match.

If you want it to match both with and without a `/` you'll either need to make two "Exact Match" redirects, or you'll need to create a single "RegEx Match" redirect.

**Comment by mediagirl** [comment]
I added an htaccess redirect to remove the trailing slash which works for my situation.

However, there is a small bug in the plugin which seems like it should be fixed to avoid confusion by someone else.

Specifically, if the logged URL is "/SEGMENT/", with a trailing slash, the URL that the plugin loads into the href on the dashboard page link does NOT have the slash. So when testing by triggering that dashboard link specifically, it seems like the redirect is indeed working when it actually isn't even loading and thus testing the correct URL.

**Comment by khalwat** [comment]
@mediagirl interesting, I can definitely see how this could be confusing! Let me have a look.

**Comment by mediagirl** [comment]
Thank you for taking a look. Happy to explain in more detail if needed. It does look to be a bug to me.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/a7cc9a117f479fd9f29acff5038d591b171e0336 & https://github.com/nystudio107/craft-retour/commit/a4e56309ea76301482703bba75ae864a7be591ca

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.71”,
```
Then do a `composer clear-cache && composer update`

**Comment by mediagirl** [comment]
Thank you for addressing the bug so quickly!
