### ISSUE TITLE
Redirect not working on specific url path

### ISSUE THREAD

**Issue by davebeeldr** [nystudio107/craft-retour#228]
### Describe the bug
Redirect not working on specific url path. Everything with /onderwijs in the slug will not be redirecting and recognized in the dashboard: 

https://www.itv-hogeschool.nl/onderwijs/
https://www.itv-hogeschool.nl/onderwijs/voor-professionals
https://www.itv-hogeschool.nl/onderwijs/aanschuifonderwijs
https://www.itv-hogeschool.nl/onderwijs/bacheloropleiding
https://www.itv-hogeschool.nl/onderwijs/bacheloropleiding/vertalen

### To reproduce
Steps to reproduce the behaviour:
1. Go to: https://www.itv-hogeschool.nl/onderwijs and get a 404 page
2. 404 not showing up on dashboard in Retour
3. When targeting https://www.itv-hogeschool.nl/onderwijs and wanted to redirect the page, it doesn't work 
4. All the other slugs in this website works fine

### Expected behaviour
1 I want a solution :) 

### Screenshots

![404 showing up in the dashboard](https://user-images.githubusercontent.com/78590032/163177561-d6c9a705-f9a1-474e-8131-0c2f9c43e388.png)
![404 not showing up in the dashboard](https://user-images.githubusercontent.com/78590032/163177571-1fc7870e-d039-42a3-ba00-cc2327a6871d.png)
![dashboard](https://user-images.githubusercontent.com/78590032/163177582-c5d3eed5-4119-4afb-8298-0ff6b4e0a20a.png)

### Versions
- Plugin version: 3.1.71
- Craft version: Craft Pro 3.7.38

**Comment by khalwat** [comment]
So it's a bit hard to tell from the information provided, but if it only happens for that one specific slug/URL, then probably something is going on with it in terms of there being a server rule/redirect in place already or the like?

Any 404 thrown by Craft, Retour should see. I'm not aware of any issues with Retour not seeing certain 404s

**Comment by khalwat** [comment]
Will re-open if more information is provided.

**Comment by davebeeldr** [comment]
He Khalwat, 

Thanks for the reply. Normally all the 404 by craft, you can see in retour. 

But for this example we deleted all retours, clear the cache. And tried just the links i described before. The redirects for this links just didn't work, unfortunately.  

For now i fixed it whit an different redirect plugin, just for this links.

**Comment by khalwat** [comment]
Something doesn't make sense... but glad you have it solved.
