### ISSUE TITLE
Where to enter license key in settings page

### ISSUE THREAD

**Issue by scott-telephonics** [nystudio107/craft-retour#230]
### Question
We recently purchased the key for Retour.  It is linked to our craft key.  i cannot find a place to enter the key into the settings screen.  Whats the proper way to let the plug-in know the License key.

**Comment by khalwat** [comment]
Click on Settings -> Plugins then below the listing for Retour you'll see a spot to enter the license number. Thanks for licensing it!

**Comment by scott-telephonics** [comment]
Found it.  Thank you.
