### ISSUE TITLE
RDS Connection count limit and 5xx errors when there's a spike in traffic to redirects or 404s

### ISSUE THREAD

**Issue by CraigPedleyCF** [nystudio107/craft-retour#231]
Hi there, I was looking to see if you had any recommendations what to do when we a see a spike traffic either redirects or 404s. Currently it's causing us to reach a limit in our RDS connections in AWS and causing us to error out and drop connections.

**Comment by khalwat** [comment]
Can you be more specific in terms of what exactly is happening?

**Comment by CraigPedleyCF** [comment]
When retour records the hit and updates the referrer and last hit time, we think this spike in writes is causing our RDS connection limit to max out.

**Comment by khalwat** [comment]
It's a simple db write that Retour does to record this stat, so if this is overwhelming your RDS instance, it must be getting absolutely pounded by bots.

I'd be very surprised if the recording of this stat from Retour is what is causing the limit to be exceeded, given that the average page loaded by Craft CMS has around 100 or more individual queries associated with it, which are much more intensive than the stats recording Retour is doing.

However, the way forward from here is some actual data to look at. Do you have logs of db transactions? Have you look at the Craft `web.log`, etc.?
