### ISSUE TITLE
One particular Entry URL not redirected

### ISSUE THREAD

**Issue by russback** [nystudio107/craft-retour#232]
I have an issue where a path redirect has been set up for a particular Entry, but it's not getting hit, whilst others (same path format, same Entry type) do get hit as expected.

I have disabled all plugins, checked `.htaccess` and `web/index.php` and the twig template that these paths resolve to (the `templates/index.twig`) and there is nothing in any of those to indicate anything getting in the way.

This isn't a 404 issue = the `entry` variable in the resolved twig template shows the Entry we are trying to redirect away from, and by putting a breakpoint in the event handler that listents to `ErrorHandler::EVENT_BEFORE_HANDLE_EXCEPTION` I can see that a 404 isn't being fired.

I have also added a breakpoint in the `resolve` method of the `RetourResolver` class and that's not being hit.

I have checked for any Exclude Patterns, but there are none. And cache has been cleared.

So a bit lost as to where to look next. 

This is on Craft 3.5.19.1 and Retour 3.1.71.

Any advice would be very much welcomed.

Thanks.

**Comment by khalwat** [comment]
So to clarify... if you go to the URL where you want to redirect from, what happens? Is a 404 thrown?

If not, then Retour will never redirect. By design, it will only kick in _after_ Craft has failed to resolve the route, and thrown a 404.

**Comment by russback** [comment]
That explains it - I hadn't appreciated it will only fire on a 404. I could see that in the event listeners, so should have figured that out!

**Comment by khalwat** [comment]
Right, the idea is if your route actually resolves to something in Craft, you could always put a `{% redirect %}` tag in there if you wanted to.
