### ISSUE TITLE
CSV bulk uploaded imports require a resave before becoming active

### ISSUE THREAD

**Issue by jan-dh** [nystudio107/craft-retour#234]
### Describe the bug
Did an import of a CSV, checked all settings and everything looked ok. 404 gets registered as being hit in Retour, but the redirect doesn't trigger. Only after (manually) resaving the redirect it works. Busting the Retour cache (or all caches for that matter) does not help.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "redirects" `admin/retour/redirects` and click `Import CSV file`
2. Go to "utilities" > "caches"  and clear all caches 
3. Browse to a URL that should have a redirect (will not trigger the redirect)
4. Check Dashboard to see if Retour picks up the Redirect (does pick up the 404 in the dashboard)
5. Open the redirect and save him
6. Repeat 3 and this will work now

### Versions
- Plugin version: 3.1.71
- Craft version: 3.7.39

**Comment by khalwat** [comment]
Can you provide me with a test case? I've been unable to replicate this locally.

Just a minimal CSV file to import or such, which reproduces the issue.

**Comment by jan-dh** [comment]
Don't have access to the DB for this project, so hard to reproduce. Can tell you that the site has 8 sites, so a multi-site setup. Will close this for now until I run into this issue in my own code base.

**Comment by shoored** [comment]
I seem to be having this same issue. I have imported a CSV file with redirects, they all appear in Retour. 
When I visit a URL that should be redirected, it does not happen. When I manually edit that redirect and save (without changing a thing) and then visit that URL again, the redirect works.

Clearing the Retour cache does not seem to have an effect.

**Comment by khalwat** [comment]
@shoored 
Can you provide me with a test case? I've been unable to replicate this locally.

Just a minimal CSV file to import or such, which reproduces the issue.

**Comment by shoored** [comment]
@khalwat Sure thing, will email you an example file.

**Comment by khalwat** [comment]
And you have tested this in multiple environments, especially local development, and are able to reproduce it there?

**Comment by shoored** [comment]
I have only tested this in my local development environment so far. Wanted to make sure the import went well before I tested it on other environments. Will try on a staging server also.

**Comment by shoored** [comment]
Can confirm that I can reproduce the issue on a staging server as well.

**Comment by khalwat** [comment]
And have you narrowed it down to a single redirect that you can import, which does not work?

**Comment by shoored** [comment]
It happens to all imported redirects. 🤷‍♂️ 
I tried to manually create a redirect with similiar properties than that of an imported one and it works right away.

**Comment by shoored** [comment]
@khalwat Meh.. so sorry! Found it. Had the wrong Site ID in the import. Geez 🤦‍♂️
