### ISSUE TITLE
Redirects filtering by site on multisite setup not working correctly

### ISSUE THREAD

**Issue by lexislav** [nystudio107/craft-retour#235]
On multisite setup, filtering redirects to specific site is not working - switching site in site's dropdown do nothing.
However additional search in Search for field above make the site filtering working.
It works even the reset search for is used.
But switching to All sites with sites select dropdown keeps redirects limited to previous site only, instead of showing redirects for all sites.

### To reproduce
1. Go to "Retour / Redirects"
2. Click on "All sites", choose "somesite.com"
3. See list of redirects of allsites
4. Do some search in search for field, reset it.
5. You see the list od redirects of "somesite.com" - finally desired results I wanna get on step 2.
6. Switch to allsites
7. See list of redirects of "somesite.com" instead of redirects for all sites

### Expected behaviour
Switching sites should show redirects for selected site after site is selected

### Versions
- Plugin version: 3.1.71
- Craft version: Craft Pro 3.7.42
- PHP Version | 7.3.33-1

**Comment by khalwat** [comment]
Fixed in 3.1.72 -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.72
