### ISSUE TITLE
Plugin's dashboard 404 overview still shows allites 404's even when site is selected

### ISSUE THREAD

**Issue by lexislav** [nystudio107/craft-retour#236]
### Describe the bug
Retour's dashboard shows allsite's 404s even the specific site is selected.

Other issues is the clicking on 404 File Not Found URL link in 404's list leads to `admindomain.cz/404url`, but it should be heading to `thesitethe404wasgeneratedon.com/404surl`. However, clicking the plus button to handle the redirect, creates redirect on the correct site – so the correct info is there. It is just not used to generate 404 File Not Found URL link.

### To reproduce
Steps to reproduce the behaviour:
1. Change site from allsites to "somesite"
2. See the same 404's as before 

Additional step to test the other mentioned issue on dashboard:
3. click on 404url generated on other then default site 

### Expected behaviour
A 404's list for selected sites should be displayed?

### Other improvement suggestions
The site where the 404 was generated on might be displayed in 404's list? It would be easier to navigate…

### Versions
- Plugin version: 3.1.71
- Craft version: Craft Pro 3.7.42
- PHP Version | 7.3.33-1

**Comment by khalwat** [comment]
Fixed in 3.1.72 -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.72
