### ISSUE TITLE
Redirects stopped working

### ISSUE THREAD

**Issue by Jessicaaashley** [nystudio107/craft-retour#237]
### Question
We launched a site this week. I began creating redirects based off the 404 errors that were being flagged. Yesterday they were all redirecting. Today, nothing is redirecting! Also haven’t had any new 404s logged today, even though I know I was creating some and they had to have been coming in based on the number that came in in the first two days of being live. The pages I’m redirecting are throwing 404 errors, they’re just not being redirected…

two examples:
Reflex:
Www.m-ware.com/categories/ceramics/bistro should redirect to Www.m-ware.com/categories/ceramic/bistro (no s in ceramic)

I believe I have this one created as well:
www.m-ware.com/login.php should redirect to www.m-ware.com/login or else /contact.php should direct to /contact

### Additional context
Our trial did lapse for 24 hours and I assume this is why it stopped but we purchased it today and the issue is still happening.

**Comment by khalwat** [comment]
The trial elapsing is unlikely to be the issue here.

Can you show me a screenshot of one of the redirects in Retour that is not working as intended?

**Comment by Jessicaaashley** [comment]
*Exact Match Example*
Expecting www.m-ware.com/products/dayton-endeavour to redirect to
www.m-ware.com/products/dayton-endeavor (spelling, removed the u)
[image: Screen Shot 2022-05-24 at 11.32.08 AM.png]

*RegEx Match Example*
Difficult to spot the difference, but we need to remove the s from ceramics
in the middle of the path.
You can use www.m-ware.com/categories/ceramics/bistro to test...

[image: Screen Shot 2022-05-24 at 11.28.07 AM.png]

Neither work. And I don't think any other redirects work either.

Jessica

**Comment by khalwat** [comment]
Your screenshot attachment did not work @Jessicaaashley

**Comment by Jessicaaashley** [comment]
Let me know if you don't get these.

**Comment by khalwat** [comment]
They are not getting there @Jessicaaashley -- maybe you can try via the GitHub website rather than email?

**Comment by Jessicaaashley** [comment]
<img width="1440" alt="Screen Shot 2022-05-24 at 11 28 07 AM" src="https://user-images.githubusercontent.com/105958189/170081072-7f5a98eb-9aa5-4e78-b56e-ae1e19246aeb.png">
<img width="1440" alt="Screen Shot 2022-05-24 at 11 32 08 AM" src="https://user-images.githubusercontent.com/105958189/170081083-07aaee82-1781-4c98-b187-6071a04ea140.png">

**Comment by khalwat** [comment]
@Jessicaaashley are you able to reproduce this in your local development environment? If so, let's do a screen share to have a look at it:

https://savvycal.com/nystudio107/chat

If you _can't_ reproduce it in your local development environment, very likely it is something environmental on your production server that has changed or is interfering in some manner.

**Comment by Jessicaaashley** [comment]
I don't know how to look at this in a local environment. I'm not the main
developer of the site, just a PM trying to get something fixed for the
client.

**Comment by khalwat** [comment]
Okay @Jessicaaashley do you have a developer who could look at this in local development?

Essentially, I'm trying to help you narrow down what is causing this to not work for you.

I'm not aware of any issues in Retour that could cause it to just stop working, so I'm trying to rule out changes to the server or website that could potentially be the cause.

If we can't reproduce this in a local development environment, then very likely the issue is something on your production server.

If we can reproduce this in a local development environment, then we can debug it to see what is going wrong, without it affecting your live production server.

**Comment by khalwat** [comment]
Will reopen if more information is provided
