### ISSUE TITLE
[4.0.0] GraphQL api retour edge producess an internal server error

### ISSUE THREAD

**Issue by CompleteBaltics** [nystudio107/craft-retour#238]
### Describe the bug
When using the GraphQL API the retour edge produces an internal server error.

### To reproduce
1. Open GraphiQL in Craft CMS and select Full Schema
2. Try running this query:
```
query Redirect($uri: String) {
  retour(uri: $uri) {
    redirectDestUrl
  }
}
```

with query variables:
```
{
  "uri": "test"
}
```
3. This produces an internal server error:
```
{
  "errors": [
    {
      "debugMessage": "Typed static property nystudio107\\retour\\Retour::$currentException must not be accessed before initialization",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "file": "/app/backend/vendor/nystudio107/craft-retour/src/services/Statistics.php",
      "line": 168,
```

### Expected behaviour
Should return redirectDestUrl if matched with an existing redirect or an empty array

### Screenshots
![image](https://user-images.githubusercontent.com/6626293/169841394-22f87282-5225-486f-9d4a-4a6d88c0cfcc.png)

### Versions
- Plugin version: 4.0.0
- Craft version: 4.0.3

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/86d423684bf2af47f72040fb64303d2df0d5f5d5

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.0.1”,
```
Then do a `composer clear-cache && composer update`
