### ISSUE TITLE
[FR] Record the IP address of the client that caused the 404

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-retour#24]
It would be useful to have the IP address of the client that caused the 404 in some cases

**Comment by riasvdv** [comment]
Would put this behind a setting, because of GDPR 💩

**Comment by khalwat** [comment]
I'd tagged the release and was about to post it here when I saw your comment @Rias500 -- I think given that there is zero personal information recorded (it's an anonymous ip address that caused the 404), it likely doesn't matter.

But still, you're right, there should be an option to disable it.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-retour/releases/tag/3.0.11
