### ISSUE TITLE
[FR] Keep current params in the URL & append new ones in your target URL

### ISSUE THREAD

**Issue by jan-dh** [nystudio107/craft-retour#242]
Alright, so a situation I run into sometimes is the following:

I want to redirect: `https://test.com` to a url with a UTM tag `https://test.com/landing-page?utm-source=web`, so I add the UTM tag in my target URL and have the option `Preserve Query String`.

However, sometimes the input url already contains another UTM tag:

`https://test.com?utm_campaign=summer-campaign` would ideally go to `https://test.com/landing-page?utm_campaign=summer-campaign&utm-source=web`

but the result I get is `https://test.com/landing-page?utm_campaign=summer-campaign?utm-source=web`, which is invalid because of the double question marks.

It would be nice if the Preserve Query String options would append the existing query string to maybe other params in the target URL.

**Comment by khalwat** [comment]
What is the expected result if a query param already exists with the same name?

- Preserve the original query string param?
- Overwrite the original query string param?

**Comment by jan-dh** [comment]
I think overwrite the original param, but maybe this could be set as an option or a clear disclaimer, just my 2 cents.

**Comment by khalwat** [comment]
Almost feels like this is something that would be better solved with a RegEx?

**Comment by jan-dh** [comment]
To me, but again, personal opinion, RegEx solving this is pretty hard to get it right and my RegEx knowledge is very limited. I can imagine some other people out there would love an easy to manage solution. Might be that this is sth super easy to handle with RegEx, in which case I'd love an example in the docs 😅.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/edcb7f65a20b8789f7586f87b34f850bc45c1932 & https://github.com/nystudio107/craft-retour/commit/5d676b45679c2bb55bc23ec0b3bb4112ec1c64dc

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.0”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.0”,
```
Then do a `composer clear-cache && composer update`

**Comment by jan-dh** [comment]
Works like a charm, thanks!
