### ISSUE TITLE
Static redirect not working when checking for a null entry slug value

### ISSUE THREAD

**Issue by ejaedesign** [nystudio107/craft-retour#243]
Hey there,

When we manually set a static redirect:

https://craft.ejaedesign.com/the-high-calling/daily-reflection/god-not-watching-us-distance-0

to go a working entry:

https://craft.ejaedesign.com/the-high-calling/daily-reflection/god-not-watching-us-distance

The redirect does not work. I have the following at the top of the embed:

`{# _embeds/_entry #}
{% set entrySlug = craft.app.request.segments|last %}
{% set entry = craft.entries.slug(entrySlug).one() %}
{% if entry != "" %}
	 *** CODE ***
{% endif %}`

What could I be missing? Thanks for the support!

**Comment by khalwat** [comment]
Retour does nothing until Craft throws a 404 exception. The URL you're trying to redirect from:

https://craft.ejaedesign.com/the-high-calling/daily-reflection/god-not-watching-us-distance-0

Returns a `200` result code, so Craft is not throwing a 404 exception, and Retour never activates.

You can fix this by deleting that entry so a 404 is thrown.

**Comment by ejaedesign** [comment]
Thanks!

Actually, that entry does not exist. However, I'll adjust the code so that it throws a 404 exception per your suggestion. 

Much appreciated!
