### ISSUE TITLE
cachedRegExRedirects/cachedExactMatchRedirects  is never null in 4.1.0

### ISSUE THREAD

**Issue by okolvik-avento** [nystudio107/craft-retour#245]
### Describe the bug
cachedRegExRedirects and cachedExactMatchRedirects in the redirect service is never set to null (initialized as an empty array).
This causes the getAllRegExRedirects/getAllExactMatchRedirects functions to always return the empty array.
This in turn causes redirects with regexes or exact match to never work.

https://github.com/nystudio107/craft-retour/blob/7c8c63340815e1a7c72806a61821946638d4673e/src/services/Redirects.php#L161
https://github.com/nystudio107/craft-retour/blob/7c8c63340815e1a7c72806a61821946638d4673e/src/services/Redirects.php#L166

You have fixed this in develop
https://github.com/nystudio107/craft-retour/blob/3b6795dd4f116794d3c194d0aadf0e9f981da4e7/src/services/Redirects.php#L159

Please do a new release with the fix asap.

### Expected behaviour
Fetching regex redirects from database.
Successfull redirect

### Versions
- Plugin version: 4.1.0
- Craft version: 4

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/a1bcedb1e68b7fdb573eb44cc80d664479bf412d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.1”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Fix released as 4.1.1: https://github.com/nystudio107/craft-retour/releases/tag/4.1.1
