### ISSUE TITLE
Regex redirects not working

### ISSUE THREAD

**Issue by ishetnogferre** [nystudio107/craft-retour#246]
### Describe the bug
We input a Legacy url with RegEx and it doesn't redirect.

### To reproduce
Steps to reproduce the behaviour:
Our primary website is https://www.bmileisure.com/en/ 
These are the settings we're using to redirect the blog items behind **https://www.bmileisure.com/ru/blog/<slug>**
<img width="634" alt="Screenshot 2022-09-02 at 16 46 11" src="https://user-images.githubusercontent.com/6649706/188175263-0b540e00-8183-467c-bd7f-0c21fea1f884.png">

### Versions
- Plugin version: 4.1.0
- Craft version: Craft Pro 4.2.3

**Comment by khalwat** [comment]
RegEx redirects work; but you're trying to redirect on a multi-site that has a sub-directory in the path. So you will need to do a full URL redirect, something like:

Legacy URL Pattern:
https://www.bmileisure.com/ru/blog/(.*)

Legacy URL Match Type:
Full URL

Destination URL:
https://www.bmileisure.com/en/

**Comment by stephanieschroe** [comment]
@khalwat 

That is also not working. 

<img width="837" alt="Screenshot 2022-09-05 at 09 52 00" src="https://user-images.githubusercontent.com/112854189/188397215-fd009960-0ecc-49e3-8fbd-f294dfaec763.png">

**Comment by khalwat** [comment]
Please update to version 4.1.1
