### ISSUE TITLE
Redirects not created upon updateElementSlugsAndUris()

### ISSUE THREAD

**Issue by yoannisj** [nystudio107/craft-retour#248]
### Describe the bug
Retour does not automatically create redirects for element types handling their `uriFormat` changes via `Craft::$app->getElements()->updateElementSlugAndUri($element)`.

This method updates the `elements_sites` table directly instead of resaving the element. Resaving the element manually after the `uriFormat` change does not resolve the issue, as by then the new URI has already been saved in the DB and Retour can not detect the change anymore via the `EVENT_BEFORE_SAVE_ELEMENT` and `EVENT_AFTER_SAVE_ELEMENT` events.

I bumped into this issue with [Commerce Products](https://github.com/craftcms/commerce/blob/develop/src/services/ProductTypes.php#L643-L655) for example.

### To reproduce
Steps to reproduce the behaviour:
1. Enable Retour's `createUriChangeRedirects` setting
2. Install the Craft Commerce plugin
3. Create a product type with `uriFormat` set to `/products/{slug}`
4. Create a dummy product
5. Backup the database and keep a copy of the resulting `.sql` file
6. Change the product type's `uriFormat` to `/shop/products/{slug}`
7. Drop all DB tables and restore the `.sql` dump created in step 4
8. Run `./craft project-config/apply` so Commerce applies the uriFormat change
9. Go to /admin/commerce/products and verify that the dummy product's URI has changed
10. Go to /admin/retour/redirects and verify that there is *no redirect* for the dummy product

### Expected behaviour
I realise this may be a feature request, but one could expect that Retour's `createUriChangeRedirects` setting would automatically create redirects for all element types, or at least those that update their URIs and slugs using the Craft's appropriate internal APIs.

I believe this should be achievable by listening to the [`EVENT_BEFORE_UPDATE_SLUG_AND_URI`](https://github.com/craftcms/cms/blob/develop/src/services/Elements.php#L1409-L1413) and [`EVENT_AFTER_UPDATE_SLUG_AND_URI`](https://github.com/craftcms/cms/blob/develop/src/services/Elements.php#L1424-L1428) events, similarly to how Retour currently handles the `EVENT_BEFORE_SAVE_ELEMENT` and `EVENT_AFTER_SAVE_ELEMENT` events.

### Versions
- Plugin version: 3.2.1
- Commerce version: 3.4.15
- Craft version: 3.7.43

**Comment by khalwat** [comment]
Strange I haven't encountered this yet.

**Comment by khalwat** [comment]
Addressed!

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.2”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
@yoannisj lmk how this works for you

**Comment by yoannisj** [comment]
@khalwat, we had worked around the issue back then but I finally (gosh: literally one year later 😳!) could run a proper isolated test on one of our projects with this fix and it's workly very well! thanks again 🙂
