### ISSUE TITLE
Retour widget available for users without Retour-permissions

### ISSUE THREAD

**Issue by FrDH** [nystudio107/craft-retour#251]
### Describe the bug
Users that can't do any retour stuff due to not having those permissions, can add the retour widget in the dashboard.
According to the craftcms team, each plugin is supposed to manage the permissions of their own widgets.

### To reproduce
Steps to reproduce the behaviour:
Create a user without any permissions and log in as that user
Go to the dashboard and find yourself able to add the retour widget.

### Versions
- Plugin version: 
- Craft version: 3

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/81324ea8f58f091aa663178742667c063c352113 & https://github.com/nystudio107/craft-retour/commit/6ac6fc6875cab08fe2865b5a600c782872f9861a

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.3”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.4”,
```
Then do a `composer clear-cache && composer update`
