### ISSUE TITLE
Error install 4.1.3 "Cannot assign null to property nystudio107\retour\migrations\Install::$driver of type string"

### ISSUE THREAD

**Issue by timmyomahony** [nystudio107/craft-retour#252]
### Describe the bug

I'm getting the error installing the plugin via the admin interface:

```
An error occurred while executing the "nystudio107\retour\migrations\Install migration: Cannot assign null to property nystudio107\retour\migrations\Install::$driver of type string
Cannot assign null to property nystudio107\retour\migrations\Install::$driver of type string
in /var/www/html/vendor/nystudio107/craft-retour/src/migrations/Install.php at line 41
````

See [the full stacktrace  here.](https://files.timmyomahony.com/note-qW2YAQOidA-9oQki7.txt)

Issue seems to be with the `Install.php` migration, specifically here:

https://github.com/nystudio107/craft-retour/blob/4.1.3/src/migrations/Install.php#L41

I'm running Craft 4.2.5 on PHP 8.1.0 on DDEV. I notice [a similar issue on `seomatic` here.](https://github.com/nystudio107/craft-seomatic/issues/1102)

I'm a bit confused as to why the ` $this->driver = Craft::$app->getConfig()->getDb()->driver;` would be causing issues in the migration? Could be a local environment issue with DDEV? I should mention that the website (and database) is working fine otherwise. 

### To reproduce

Steps to reproduce the behaviour:

1. Install plugin via `composer require`
2. Go to "plugins" in the "settings"
3. Click "install" on Retour
4. Get error message

### Expected behaviour

Plugin should install

### Screenshots

![CleanShot 2022-10-03 at 16 15 12@2x](https://user-images.githubusercontent.com/615149/193613470-e8a3ed11-e5c6-4821-a3fe-233c74ae96ee.jpg)

### Versions

- Plugin version: 4.1.3
- Craft version: 4.2.5

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/f3eaff55dc47a478d726f5375291f350b417291c

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.4”,
```
Then do a `composer clear-cache && composer update`

**Comment by timmyomahony** [comment]
Thanks, that seems to have fixed it
