### ISSUE TITLE
Use Retour to Redirect control panel links in multi-site setup

### ISSUE THREAD

**Issue by sm9** [nystudio107/craft-retour#254]
I'm using Retour (3.1.71) in a Craft 3 (3.7.52) multi-site setup (using PHP 7.4). All the sites share the same document root (using cPanel). The setup looks like this:

https://www.mydomain.com (main site)
https://www.mydomain1.com
https://www.mydomain2.com
https://www.mydomain3.com

The main site's control panel is at https://www.mydomain.com/admin, but as the domains share the same document root, users can access the same control panel using their individual domains at /admin, e.g. at https://www.mydomain1.com/admin

Is it possible to use Retour to stop users from logging into the Craft control panel at their individual domains, and to redirect them to the main domain when they try to access the control panel?

So I want to redirect www.mydomain1.com/admin to https://www.mydomain.com/admin

I tried adding redirects for /admin and https://www.mydomain1.com/admin to redirect to https://www.mydomain.com/admin, using Exact Match redirects, but I can't get it to work.

Thanks in advance for any advice about this.

**Comment by khalwat** [comment]
Retour only kicks in when Craft throws a 404 error.

It does this for performance reasons, because you really don't want every request to match a possibly very long list of redirects.

It would slow down every request, instead of only invoking in exceptional cases where a 404 is thrown.

It sounds like what you want is a server redirect (in Nginx or Apache).

**Comment by sm9** [comment]
Hi Andrew, thanks for your reply. I feel like I should have known that already! 🙃

For info, I've just hacked together a .htaccess rule based on various similar examples that I found. I'm not sure if this is the best way of doing this but it _seems_ to work:

```
  # Redirect child site control panel links to main site's control panel
  RewriteCond %{REQUEST_URI} ^/admin
  RewriteCond %{HTTP_HOST} !^(www\.)?mydomain\.com$
  RewriteRule (.*)$ https://www.mydomain\.com/$1 [R=301,L]
```

Thanks.
