### ISSUE TITLE
Redirect Http Code is invalid, when creating new static redirect

### ISSUE THREAD

**Issue by TGriffiths88** [nystudio107/craft-retour#255]
Describe the bug
When creating a new static redirect, it shows an error beneath the 'Redirect Type' field. Redirect Http Code is invalid.

To reproduce
Steps to reproduce the behaviour:

Open Retour > Redirects
Click ' New Static Redirect'
You will see the error below the Redirect type dropdown
Expected behaviour
I expect it to not show the error, since we only have the choice of the options within the dropdown.

Screenshots
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/85160908/199476700-81a33281-2f8e-4e41-8899-dd2c1d32087b.png">

Versions
Plugin version: 4.1.4
Craft version: Craft Pro 4.3.1

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/43694f457e88a0f588a9f15fe3cd4bdc719781d0

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.5”,
```
Then do a `composer clear-cache && composer update`

**Comment by TGriffiths88** [comment]
Thanks @khalwat. That's awesome.
