### ISSUE TITLE
Add an event when fires when a redirection is deleted

### ISSUE THREAD

**Issue by tremby** [nystudio107/craft-retour#259]
### Is your feature request related to a problem? Please describe.
I need an action to take place when redirections change; so when they are added, edited, or deleted.

There's an event when a redirection is saved (which covers new and edit), but as far as I can tell there's none when a redirection is deleted.

### Describe the solution you would like
An event which occurs when a redirection is deleted.

### Describe alternatives you have considered
- Educate client to open and save a redirection after deleting one
- Run the logic regardless on some schedule

**Comment by khalwat** [comment]
So I can certainly add this event for you if you like, but it sounds like you're building some kind of system the sync the redirects in Retour with a build system or backend.

I'd suggest another architectural route that might work better, which is when a route comes in that is not handled by whatever frontend/backend architecture you're using, you use the `retourResolveRedirect()` GraphQL query to try to resolve the route for you.

https://nystudio107.com/docs/retour/using.html#resolving-redirects

This would keep all of the logic and data in one place.

If this doesn't work for you, let me know!

**Comment by tremby** [comment]
I was given some very specific rules on how to handle extra query parameters etc, so I'm running my own resolution logic. That means I can't go the route you suggested.

It means I need the list of redirections on my end, and I want to keep that cached so I don't need to grab it on every request, but I want to be able to invalidate that cache automatically if the configuration changes.

Thanks for being open to a new event.

**Comment by khalwat** [comment]
Well, Retour throws a number of events that would allow you to use whatever resolution logic you need in PHP-land already, check out the Resolve Redirect events:

https://nystudio107.com/docs/retour/advanced.html#resolve-redirect-events

But if you're already down the road of implementing it on your own, it's not a big deal to add that additional event for when a redirect is deleted, too. I think for completeness, it probably should be there anyway.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/49edf133442d936ddc19720ae46c9ee332ebc84e & https://github.com/nystudio107/craft-retour/commit/1ef2251b2a05751d30303be33896071175b2462b

Added to docs in: https://github.com/nystudio107/craft-retour/commit/320249f70e62856282671343249ae3d74c9d9e73

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.4”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.6”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Released:

Craft 3: Version 3.2.4 -> https://github.com/nystudio107/craft-retour/releases/tag/3.2.4

Craft 4: Version 4.1.6 -> https://github.com/nystudio107/craft-retour/releases/tag/4.1.6

**Comment by tremby** [comment]
Thank you!
