### ISSUE TITLE
Users can't add redirects without Settings enabled in permissions

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-retour#26]
When trying to add a redirect on a user who doesn't have access to settings, they're directed to a page with the following error.

![screen shot 2018-10-11 at 10 13 59 am](https://user-images.githubusercontent.com/1007191/46822359-2197d600-cd40-11e8-9128-31cfa2221d37.png)

Enabling settings for all users fixes the issue, but we don't want users to edit any settings.

![screen shot 2018-10-11 at 10 22 51 am](https://user-images.githubusercontent.com/1007191/46822397-3bd1b400-cd40-11e8-8909-d74b45cd2500.png)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/31ccc561158ea91d0c7efcc4160a03eb196aec35
