### ISSUE TITLE
Static redirects does not respect "enabled" flag?

### ISSUE THREAD

**Issue by martinstarecek** [nystudio107/craft-retour#260]
### Question
Hi, I would like to ask if it is ok that the method to retrieve all "exactmatch" redirects: https://github.com/nystudio107/craft-retour/blob/67e22cbb742eaf20b46f9e2bfe538617e315f36b/src/services/Redirects.php#L694 does not use the "enabled" flag, but load all static redirects. Is this a bug or feature and I missed something? :)

Thanks for your work and feedback.

**Comment by khalwat** [comment]
Ah yes, I think that should be fixed

**Comment by martinstarecek** [comment]
Thank you and fingers crossed

**Comment by khalwat** [comment]
This has been addressed.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.5”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.7”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Released as:

Craft 3: Version 3.2.5 -> https://github.com/nystudio107/craft-retour/releases/tag/3.2.5

Craft 4: Version 4.1.7 -> https://github.com/nystudio107/craft-retour/releases/tag/4.1.7

**Comment by martinstarecek** [comment]
:+1: Great. Sorry, for late response. I had no time.
