### ISSUE TITLE
Http - https

### ISSUE THREAD

**Issue by driesbonte** [nystudio107/craft-retour#263]
### Describe the bug
When adding redirects to for a certain string
https://public.nodalview.com/pt/foto
The redirect first goes to http instead of https (in craft it self the url has https and is also have been setuped liked that in the env.

```
Status Code,Scheme,Host,Path
301,https://,public.nodalview.com,/pt/foto
301,http://,public.nodalview.com,/pt/fotografia-imobiliaria-hdr
200,https://,public.nodalview.com,/pt/fotografia-imobiliaria-hdr
```

### Screenshots
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/56576739/209162910-35f38aba-51e7-48fc-add9-7134a60fb1f0.png">

### Versions
- Plugin version: 4.1.5
- Craft version: ^4.1.0.2

**Comment by khalwat** [comment]
So Retour just uses whatever your Craft setup is set to use for a site URL. Double-check that your `siteUrl` is properly set to `https`
