### ISSUE TITLE
Adding Expires headers breaks retour

### ISSUE THREAD

**Issue by jhealey5** [nystudio107/craft-retour#27]
We've enabled nginx header expires via the conf, and it seems to break retour. All js/css 404s, I assume because they're created dynamically or something?

![image](https://user-images.githubusercontent.com/1771431/47154488-5f65a300-d2da-11e8-8671-749aa47b931f.png)

The nginx conf we're using for expires:
```
  location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp3|mp4|ogg|ogv|webm|htc|webp)$ {
        etag off;
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
```

**Comment by khalwat** [comment]
So this is an Nginx specific thing; Nginx doesn't work like Apache, in that once a found ruleset is matched, no other rules are processed. You should have rules like this:

https://github.com/nystudio107/nginx-craft/blob/master/sites-available/somedomain.com.conf#L112

```    # Craft-specific location handlers to ensure AdminCP requests route through index.php
    # If you change your `cpTrigger`, change it here as well
    location ^~ /admin {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ^~ /cpresources {
        try_files $uri $uri/ /index.php?$query_string;
    }
```

To ensure that things will flow through to the AdminCP as needed.
