### ISSUE TITLE
Manually Added Redirect not working

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-retour#276]
### Describe the bug
Redirect not working as expected.

Cannot upgrade craft or plugin due to server limitations.

### To reproduce
Steps to reproduce the behaviour:
1. add the redirect in the attached screenshot and it doesn't redirect
2. tried full url and path (changed the corresponding dropdown) and still doesn't work.
3. also tried locally, with local domain,  but doesn't work

### Expected behaviour
expect the page to redirect to the target url

### Screenshots
![image](https://user-images.githubusercontent.com/6899490/222224808-2aca6006-67af-4aeb-b551-95cd9442c9ee.png)

### Versions
- Plugin version: 3.1.46
- Craft version: 3..5.19.1

**Comment by khalwat** [comment]
If you visit the Legacy URL, does a valid webpage load? Retour only redirects if Craft throws a 404 error:

https://nystudio107.com/docs/retour/whyretour.html
