### ISSUE TITLE
[FR] When changing a slug of an entry, add full url as a redirect

### ISSUE THREAD

**Issue by GewoonRoy** [nystudio107/craft-retour#28]
When i'm changing the slug of an entry it will save the path as a redirect. (e.g. **/foo** to **/foo/bar** with **Path only**)

The redirects aren't working because i have a site specific website and i'm missing my prefix in the path. What i expect to have is **/a/foo** to **/a/foo/bar** with **Path only** or the full url as a redirect.

**Comment by khalwat** [comment]
I'll have to try to figure out how to do this so that it doesn't affect case where you're _not_ redirecting from domain to domain.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-retour/releases/tag/3.1.0

**Comment by khalwat** [comment]
So in actuality, this is fixed in https://github.com/nystudio107/craft-retour/commit/2e0090fcd6e9bf3b0034b42d3c419e990c196bec which will be part of the 3.1.1 release
