### ISSUE TITLE
Non admin users aren't able to edit a shortlink

### ISSUE THREAD

**Issue by belkin** [nystudio107/craft-retour#280]
### Describe the bug
Non admin users with rights to Access Retour, Dashboard, Redirects and Short Links aren't able to edit a short. They're getting following error: `User is not permitted to perform this action`.

### To reproduce
Steps to reproduce the behaviour:
1. Sign in as user which has rights to Access Retour, Dashboard, Redirects and Short Links.
2. Create a shortlink via shortlink field in een entry.
3. Go to Retour plugin -> Short Links
4. See error message "User is not permitted to perform this action" 

### Expected behaviour
Users with rights to Short links have to be able to edit a short link like they're able to edit a redirect.

### Screenshots
User group permissions: 
<img width="149" alt="image" src="https://github.com/nystudio107/craft-retour/assets/3419659/c4217097-a693-4030-bba3-fe14e9734c0f">
<img width="169" alt="image" src="https://github.com/nystudio107/craft-retour/assets/3419659/5937b889-b244-41c9-b6b8-c6e332dff33c">

Short link field: 
<img width="906" alt="image" src="https://github.com/nystudio107/craft-retour/assets/3419659/8c9613a8-de5f-42fe-a637-1e1247cf2073">

Error message after clicking on a short link via de Retour -> Short links:
<img width="461" alt="image" src="https://github.com/nystudio107/craft-retour/assets/3419659/688da5d9-cd45-4648-b136-0b8db2db26cd">

### Versions
- Plugin version: 4.1.11 but I have also tested it with 4.1.12 the issue is still there.
- Craft version: 4.4.4

**Comment by khalwat** [comment]
I'm unable to replicate this issue.

I set up a user group with the permissions above, and am able to access Short Links without an issue.

Perhaps there is another CP permission that is missing from this user group?

<img width="413" alt="Screenshot 2023-06-27 at 10 43 46" src="https://github.com/nystudio107/craft-retour/assets/7570798/abfaa3a2-3c2f-4235-944b-9488c084fe24">
<img width="286" alt="Screenshot 2023-06-27 at 10 43 18" src="https://github.com/nystudio107/craft-retour/assets/7570798/8e85cee8-2975-45ba-bb20-7a2789946f9d">
<img width="1535" alt="Screenshot 2023-06-27 at 10 42 32" src="https://github.com/nystudio107/craft-retour/assets/7570798/7fba91d6-c555-4980-9a5a-671a2cca831d">
