### ISSUE TITLE
Regex Redirect not working as expected

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-retour#283]
Craft CMS 4.4.15.6
Retour 

### Question
I'm trying to redirect anything with a url pattern of `/glossary-terms/any-slug/` and have set up the legacy pattern like this `\/glossary-terms\/[a-zA-Z0-9\-]+\/` with match type of path only and regex match.

but it's not working as expected. Please advise. I suspect this is user error on my part but cannot figure it out.

### Additional context
Add any other context or screenshots about the support request here.

**Comment by khalwat** [comment]
Can you tell me what is not working as expected?

Did you test the RegEx here:

https://regexr.com/

Retour isn't doing anything special or custom here, it's just a standard PHP regex match.

**Comment by CreateSean** [comment]
@khalwat 
New validated and confirmed working from regexr you provided is ```^glossary-terms\/[a-z0-9]+(?:(?:-|_)+[a-z0-9]+)*$```

but when I add that to retour and visit a url that I expect to redirect to the homepage it still returns a 404

![image](https://github.com/nystudio107/craft-retour/assets/6899490/4bf52c1c-ad68-4323-ac3c-6811d1112378)

**Comment by khalwat** [comment]
Give me an example of a URL that you think should work, but does not.

Also, I think you might be overcomplicating your RegEx a bit there

**Comment by CreateSean** [comment]
/glossary-terms/any-slug

**Comment by khalwat** [comment]
https://regexr.com/7k1bt
