### ISSUE TITLE
Redirect appending query param after update

### ISSUE THREAD

**Issue by joshparylak** [nystudio107/craft-retour#285]
I just updated a site to craft 4 and update the plugin accordingly. After the update, some of my redirects are behaving oddly. They are redirecting to the new correct url, but appending `?p={originalURL}` to the end of the url, making the new redirect url not work. seems to only happen when the original url was a single segment.

### Versions
- Plugin version: 4.1.13
- Craft version: 4.5.6.1

**Comment by khalwat** [comment]
This is not something Retour is doing, it is most likely being done by your server config, which is adding that as a parameter.
