### ISSUE TITLE
Is it possible to disable all redirects temporarily?

### ISSUE THREAD

**Issue by robzor** [nystudio107/craft-retour#289]
### Question
Hi there, 

Is there an option to disable all redirects without losing any of the existing stats/data? 

I've set up a staging site for the client and I want to temporarily disable the redirects set up by a legacy developer on the site (there are 2555 of them so it's unfortunately not a case of just deleting 1 or 2). I know I can hit 'Disable' in the Plugin page but I assume that deletes all the stats/redirects currently there?

### Additional context
Craft: 3.9.10
Retour: 3.2.12

**Comment by khalwat** [comment]
That's a pretty crazy number of redirects.

But you should be able to **Disable** the plugin without any data loss. Uninstalling the plugin is what would cause data loss.

**Comment by robzor** [comment]
Great, thanks for getting back to me! And yes, I am getting them to audit those redirects :D
