### ISSUE TITLE
[FR] True Multisite

### ISSUE THREAD

**Issue by spAnser** [nystudio107/craft-retour#29]
It would be nice to handle site redirects on a multisite in a craft 3 multisite way.

This would mean that in the header there is a dropdown to switch which site is being worked on. Each site would have its own set of redirects. Currently Retour can only have multisite redirect by prefixing the redirect with the multisite folder prefix or full domain.

**Comment by GewoonRoy** [comment]
Actually this would be a great solution for #28

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-retour/releases/tag/3.1.0
