### ISSUE TITLE
Wrong `fileNotFoundUrl`in Dashboard

### ISSUE THREAD

**Issue by vandres** [nystudio107/craft-retour#290]
### Question
We are having a multi-site setup. We have 6 different sites, with 2 different domains and 2 languages.

![image](https://user-images.githubusercontent.com/1436383/183157589-77671d45-3149-489c-81d2-4175aa94545d.png)

Now our editors reported some wrong urls. I am not even sure, if it was always like this (since #241) or came with one of the updates.

One example url is "http://zs.test/shop/ch/reinigung-der-inneren-organe123.html" This creates a new entry in the Dashboard.

![grafik](https://github.com/nystudio107/craft-retour/assets/1436383/f0276c83-a20a-4c04-b807-dd1c43bf7dfe)

But when you click on it in the Dashboard, it actually adds the complete `baseUrl` to the link.

![Bildschirmfoto 2024-02-07 um 18 26 58](https://github.com/nystudio107/craft-retour/assets/1436383/65f62fb9-9a3a-41b5-be0d-de067e1eb9ee)

Right now, when the editors click onto the link, they directly generate a new 404 because of the wrong url "http://zs.test/shop/shop/ch/reinigung-der-inneren-organe123.html"

**Comment by vandres** [comment]
I think, it comes from this change: https://github.com/nystudio107/craft-retour/blame/728fd728405f68c8ba105e7767743f16d958d744/buildchain/src/vue/FileNotFoundUrl.vue#L32

**Comment by khalwat** [comment]
Same as: https://github.com/nystudio107/craft-retour/issues/294

**Comment by vandres** [comment]
@khalwat Is there any ETA on this?

**Comment by khalwat** [comment]
I'm in the midst of getting plugins ported to Craft 5, but it's on the list!

**Comment by khalwat** [comment]
Addressed in the above commits

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.16”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.17”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v5 as 5.0.1”,
```
Then do a `composer clear-cache && composer update`
