### ISSUE TITLE
410 Gone twig template

### ISSUE THREAD

**Issue by gmonseur** [nystudio107/craft-retour#295]
Hello,

I have configured a 410 redirect using the plugin.
First of all, the redirection to the destination doesn't work. 
I suppose this is normal since 410 is a page status just like a 404, not a redirect.
So I get a blank page with a 410 status.  
Is it possible to assign a twig 410 template to explain the error?

![Screenshot 08-03-2024 at 14 07(1)](https://github.com/nystudio107/craft-retour/assets/1887613/8f624c67-2764-410d-850e-4e20808f9aff)

![Capture d’écran du 2024-03-08 14-13-09](https://github.com/nystudio107/craft-retour/assets/1887613/e4b7ee0e-0d32-45d6-b456-2b3262508398)

**Craft CMS 4.5.11.1**
**Retour 4.1.15**

**Comment by khalwat** [comment]
You _might_ be able to do this if you set up your webserver to redirect `410` status codes to Craft (the way you have it set up to do that for `404` status codes) and you set up the appropriate Twig template for that status code (again, like you did for `404`)

More here: https://nystudio107.com/blog/handling-errors-gracefully-in-craft-cms#handling-exceptions-on-the-frontend

**Comment by gmonseur** [comment]
Hi @khalwat 

Thanks for your help.

In the [documentation](https://craftcms.com/docs/5.x/system/routing.html#error-templates), it is indicated to create a template with the status code. I've created these:
- 410.twig
- error.twig
- (gone.twig)

But I still get the same blank page
The 404.twig works correctly...
The server seems to be well configured:
```
HTTP/1.1 410 Gone
Date: Mon, 11 Mar 2024 08:49:26 GMT
Server: Apache/2.4.52 (Ubuntu)
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Cache-Control: no-cache, no-store, must-revalidate
X-Robots-Tag: none
X-Powered-By: Craft CMS
X-Debug-Tag: 65eec596750af
X-Debug-Duration: 97
X-Debug-Link: http://***.local/actions/debug/default/view?tag=65eec596750af
Set-Cookie: 0f76a97cf0214b90e8cddfdfd24c9509_identity=6a84e2d681f2e8519080cf7f534c5adb97072562b53036651841fcaf2e9e61a3a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%220f76a97cf0214b90e8cddfdfd24c9509_identity%22%3Bi%3A1%3Bs%3A159%3A%22%5B1%2C%22%5B%5C%22F216pVZwW2YaaMu28Rd2dAIwAUsgEozA_4lKDybDxKtoGskn2ekItCq6xLzX_srzamVIM14m19Y2cGcUAv6jgii4sSBVQKEa5UgI%5C%22%2Cnull%2C%5C%22f7ec762ae3fce466b0ef48556c80eefd%5C%22%5D%22%2C3600%5D%22%3B%7D; expires=Mon, 11 Mar 2024 09:49:26 GMT; Max-Age=3600; path=/; HttpOnly
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization
Access-Control-Allow-Methods: GET
Access-Control-Expose-Headers: Content-Security-Policy, Location
Access-Control-Max-Age: 600
Location: http://***.local/410
X-Frame-Options: SAMEORIGIN
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
```
I don't know.

**Comment by gmonseur** [comment]
Further information

In vendor/craftcms/cms/src/controllers/TemplatesController.php in actionRenderError fct in line 240
```
dump($template);
dump($variables);
dump($this->renderTemplate($template, $variables));
exit();
```

And results

```
"_errors/410"

array:5 [▼
  "message" => "Page non trouvée."
  "code" => 0
  "file" => "/media/DATA/www/***/vendor/craftcms/cms/src/web/Request.php"
  "line" => 1350
  "statusCode" => 410
]

craft\web\Response {[#442 ▼](http://www.***.local/accessoire/agrafe-a-piquer-#sf-dump-1909957779-ref2442)
  -_events: array:1 [▶]
  -_eventWildcards: []
  -_behaviors: array:1 [▼
    "template" => craft\web\TemplateResponseBehavior {#999 ▼
      +owner: craft\web\Response {[#442](http://www.***.local/accessoire/agrafe-a-piquer-#sf-dump-1909957779-ref2442)}
      -_attachedEvents: []
      +template: "_errors/410"
      +variables: array:5 [▼
        "message" => "Page non trouvée."
        "code" => 0
        "file" => "/media/DATA/www/***/vendor/craftcms/cms/src/web/Request.php"
        "line" => 1350
        "statusCode" => 410
      ]
      +templateMode: null
    }
  ]
  +exitStatus: 0
  +format: "template"
  +acceptMimeType: null
  +acceptParams: []
  +formatters: array:6 [▶]
  +data: null
  +content: null
  +stream: null
  +charset: "UTF-8"
  +statusText: "OK"
  +version: "1.1"
  +isSent: false
  -_statusCode: 200
  -_headers: yii\web\HeaderCollection {#441 ▶}
  -_cookies: yii\web\CookieCollection {#850 ▶}
  +defaultFormatters: []
  -_isPrepared: false
}
```

**Comment by khalwat** [comment]
Did you set up your webserver to route 410 errors through Craft?

**Comment by gmonseur** [comment]
It's an Apache server. What do I need to configure?

**Server: Apache/2.4.52 (Ubuntu)**

**Comment by khalwat** [comment]
I haven't used Apache in a long time, so I don't know off of the top of my head... but you'd want something in your `.htaccess` to ensure that the webserver itself doesn't handle the `410` error, but rather it should be passed along to Craft so that it can then route it to the correct template.

Maybe this helps: https://stackoverflow.com/questions/65388979/properly-set-redirect-410-gone

**Comment by terryupton** [comment]
Did you manage to solve this @gmonseur ?
