### ISSUE TITLE
Add logging of excluded patterns, and disallow empty patterns

### ISSUE THREAD

**Issue by uandco** [nystudio107/craft-retour#297]
### Is your feature request related to a problem? Please describe.

I noticed Retour was not working anymore, in all my environments. 
Initially I thought something had gone wrong in a previous Craft 4.5.9 to 4.5.10 update as that was the major change I traced back in my repo...

Turns out I missed this change in project.yaml:

<img width="564" alt="image" src="https://github.com/nystudio107/craft-retour/assets/26996169/b2231988-453f-4890-9fc7-75b483011432">

I didn't look close enough and I should have seen the empty exclusion pattern.

Took me a while to figure what was really going on, till I debugged the `excludeUri` method and figure, indeed, it was not doing anything (not even storing the 404s in stats) because there was an exclusion pattern I was unaware of.

### Describe the solution you would like

Imho, empty exclusion patterns should trigger an error when saving the settings, it's easy to click "add row" by mistake while changing other settings then save them (that's the only explanation I have as to why this whole block of settings, including the empty pattern, has been added to my config file).

In addition to not allowing empty patterns, the `excludeUri` method should log the matched pattern to make debugging easier.
I was lost debugging this as the web log only had 2 lines such as :

```
2024-03-22 12:03:25 [web.INFO] [nystudio107\retour\services\Redirects::handle404] A 404 exception occurred {"memory":2992568} 
2024-03-22 12:03:25 [web.INFO] [nystudio107\retour\services\Redirects::handle404] 404 full URL: https://saslab.docker.amazee.io/blah2, 404 path only: /blah2 {"memory":2992992} 
```

Then nothing else explaining why Retour was done doing its job.

### Describe alternatives you have considered

Nothing I can think of, I think the validation of patterns and logging are pretty straightforward.

### Additional context

See screenshots / logs above

**Comment by khalwat** [comment]
Fixed via the above commits.

Added logging if a URL is excluded due to the `excludePatterns`, and it also will now skip any empty `excludePatterns`
