### ISSUE TITLE
Sort arrow is upside-down

### ISSUE THREAD

**Issue by Mosnar** [nystudio107/craft-retour#299]
### Describe the bug

The dashboard table's arrows are inverted - pointing up should be low-to-high, not high-to-low.

![image](https://github.com/nystudio107/craft-retour/assets/3810939/efa8eafa-395c-4c53-a5ef-76982d5f18e8)

### Versions
- Plugin version: 4.1.16

**Comment by khalwat** [comment]
I guess I'm sorting dyslexic, as this looks right to me. But a _down_ array should be with the highest number first?

**Comment by Mosnar** [comment]
I’m just sayin’ that’s how Craft has it in the element index 🤷‍♂️

**Comment by khalwat** [comment]
I guess I can't argue with Microsoft UX https://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header

**Comment by khalwat** [comment]
Fixed in the above commits
