### ISSUE TITLE
Short link fields not working for external assets

### ISSUE THREAD

**Issue by turnstylerj** [nystudio107/craft-retour#300]
### Describe the bug
With a Short Link field on an asset volume (using Servd Asset Storage CDN in this case), the entered short link just redirects to the homepage of the site rather than the asset URL. Creating a new static redirect to the file's full URL works as expected.

### To reproduce
Steps to reproduce the behaviour:
1. Create an asset volume using an external filesystem (i.e. Servd Asset Storage)
2. Add a Short Link field to the asset volume field layout
3. Go to short link

### Expected behaviour
Short link redirects to file external URL.

### Versions
- Plugin version: 4.1.15
- Craft version: 4.8.4

**Comment by khalwat** [comment]
Retour only works when the request goes through Craft. It's very likely that your Nginx setup does not route requests for static assets like images through Craft. This is pretty common for performance reasons, but it also means that your intended use-case will not work.

**Comment by turnstylerj** [comment]
Would it be possible to detect if the asset the field is on isn't using local storage and, if so, set the redirect destination to the external asset URL? I only ask because setting up a static redirect from /path to <full-external-url> works fine as a redirect.

**Comment by khalwat** [comment]
Wait, you're saying the same exact thing works when _not_ in a Short Link field? So the short link "alias" is the only thing not working in this case?

**Comment by turnstylerj** [comment]
Yes, that's correct. If I'm on `https://my-site.com` and  go to Retour > Redirects and choose "New Static Redirect", I can set a path `/my-path`, and a destination to the full URL of an external asset `https://my-cdn.com/my-asset.pdf`, and then `https://my-site.com/my-path` will correctly redirect to the external asset. 

But if I have a Short Link field on the asset where I set `/my-path` as the value, then `https://my-site.com/my-path` will just redirect to `https://my-site.com`.

**Comment by khalwat** [comment]
Fixed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.16”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.17”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v5 as 5.0.1”,
```
Then do a `composer clear-cache && composer update`
