### ISSUE TITLE
Template Error When installing on Craft 3

### ISSUE THREAD

**Issue by bfjare** [nystudio107/craft-retour#304]
Running craft 3.9.13

Getting this error right after install.

URL: /admin/retour/dashboard

<img width="1930" alt="Screenshot 2024-05-23 at 12 55 02 PM" src="https://github.com/nystudio107/craft-retour/assets/11744681/5ff64e98-94d6-4169-a57b-cd1e2a3a6b23">

**Comment by khalwat** [comment]
Same as: https://github.com/nystudio107/craft-retour/issues/302

Please continue the discussion on that issue @bfjare
