### ISSUE TITLE
URL gives 404 but is not logged in dashboard

### ISSUE THREAD

**Issue by svondervoort** [nystudio107/craft-retour#308]
### Question
I'm not sure if this is a bug so I'm currently reporting this as a support request.
We have a site setup with a lot of working redirects except for what it looks like one URL which is not being captured by Retour.
The URL does show the 404 page but don't see it coming up in the dashboard.

I'm not sure what may be causing this since any suffix to the URL is not logged in Retour, but removing a few characters is.

```
http://ctouch-website.test/nl/oplossingen/educatie-hoger-onderwij // logged
http://ctouch-website.test/nl/oplossingen/educatie-hoger-onderwijs // not logged
http://ctouch-website.test/nl/oplossingen/educatie-hoger-onderwijs-test // not logged
```

### Additional context
![image](https://github.com/nystudio107/craft-retour/assets/5063372/52f87997-2baf-4132-b802-1dcff5d889a2)
![image](https://github.com/nystudio107/craft-retour/assets/5063372/c719850f-021b-4f09-a210-2790f13814d2)

**Comment by khalwat** [comment]
I tried to replicate the issue in my test environment, and was unable to. Which makes me think it is something specific to your local development, devops, or browser setup.

<img width="1042" alt="Screenshot 2024-06-25 at 10 35 45" src="https://github.com/nystudio107/craft-retour/assets/7570798/71910365-90d7-4cb6-b027-c45e83db4fa2">


My only guess here would be that the 404 is cached by your browser?

Also please provide the Craft version, Retour version, and any other additional information that might be helpful.

**Comment by svondervoort** [comment]
Yeah for some reason it only seems to happening for this specifiek (disabled and even deleted) entry and URL. I also created a new entry, disabled it and deleted it and Retour just registers the 404 hit and if I set a redirect on the 404 URL it just works.

Do you have any clue what could bypass Retour since it is showing up a 404 page?

Here are the versions if it helps:
- Craft CMS Pro:
- Retour: 4.1.18

It is happening on the server and also locally.
Both environments run on NGINX so it isn't anything .htaccess related. Locally we work with Valet.
`CRAFT_ENVIRONMENT=production` and `CRAFT_DEV_MODE=false`.

**Comment by khalwat** [comment]
Can you show me the Retour redirect you've created that might be capturing this URL? Is it possible it's using a regular expression that is capturing the redirect?

Are you able to reproduce it in another project, or is it specific to this project somehow?

**Comment by svondervoort** [comment]
We have the Sites set to `Netherlands` of which the Base URL is set to `@web/nl`.
The Legacy Url Pattern is set to `/oplossingen/educatie-hoger-onderwijs` with the Legacy URL Match Type set to `Path only`.

We've also tried setting Sites the `All` and use `Full URL` with the complete URL but still we see the 404 instead of the page set in the redirect.

It also happens to other entries in a different section.

Is there any way to debug the 404 page? I tried other existing redirects which do work.

**Comment by svondervoort** [comment]
Just checking, is there any way to debug the 404 logic?
Or should can we only debug using the [advanced events](https://nystudio107.com/docs/retour/advanced.html#resolve-redirect-events)?

**Comment by khalwat** [comment]
Yes, if `devMode` is enabled there should be extensive logging of 404 errors, and the general flow of things.

I'd suggest deleting all of your logs, ensuring that `devMode` is enabled, then recreate the problem, and then search the `web.log` for messages from Retour.

I'm also happy to look at said log if you like -- send it to `info@nystudio107.com`

**Comment by khalwat** [comment]
Closing this issue out -- happy to continue to help you figure out what's going on here tho.
