### ISSUE TITLE
Make redirects available in elements-api

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [nystudio107/craft-retour#31]
Is it possible to user or access redirects from the elements-api? I'm using the elements-api to fetch Entries by uri, for example:
```php
return [
	'elementType' => Entry::class,
	'criteria' => [
		'uri' => 'page/' . $entrySlug,
		'site' => $siteHandle,
	],
	...
```
Somewhere I'd expect the retour plugin to jump in here and 'fix' the uri when an old uri is used. But on the other hand I understand that it might be difficult to support a plugin within a plugin.

Is there some way I can fix this manually by using the stored redirects?

**Comment by khalwat** [comment]
So you can definitely do this... in your Element API you'd need to add some code to check the URLs to see if there are redirects.

Something like `Retour::$plugin->redirects->findRedirectMatch()` -- here's the method signature:

```
    /**
     * @param string $fullUrl
     * @param string $pathOnly
     *
     * @return array|null
     */
    public function findRedirectMatch(string $fullUrl, string $pathOnly)
```

If it finds a redirect for the given `$fullUrl`, it will return an array to you with the information on the redirect.

**Comment by SanderVanLeeuwen** [comment]
Thanks for the push in the right direction! I'm relatively new to Craft so still figuring out where to find what. Got it figured out now how to use `findRedirectMatch()` in my API configuration 👍🏻
