### ISSUE TITLE
Wrong URLs in dashboard

### ISSUE THREAD

**Issue by samuel-clara** [nystudio107/craft-retour#310]
### Describe the bug
The URLS of the <a> href attribute in the "404 File Not Found URL" column are wrong. Site slug is applied two times.
The text shows the right URL

### To reproduce
Steps to reproduce the behaviour:
1. Go to Dashboard
2. Hover one of the links of the "404 File Not Found URL" column
3. URL differs from text

### Screenshots
![meteorit 2024-08-02 at 17 13 56@2x](https://github.com/user-attachments/assets/bfa0282e-4701-4ed3-adc9-ef6e27a2eb51)

### Versions
- Plugin version: 4.1.18
- Craft version: 4.10.7

**Comment by khalwat** [comment]
hmmmm. This is an issue that should have been fixed in a recent release of the plugin:

https://github.com/nystudio107/craft-retour/releases/tag/4.1.17

See this issue:

https://github.com/nystudio107/craft-retour/issues/290

Is there anything you can provide me to help narrow down the issue?

**Comment by white-lukas** [comment]
Bumping into the same thing running `5.0.2` and craft `5.3.1`

**Comment by khalwat** [comment]
Can you give me some more information so I can attempt to replicate this here?

How are your sites set up in terms of URL structure, and what URLs are you seeing vs. what you're expecting to see? And are you seeing this in the Dashboard, or in the Redirects views?

**Comment by white-lukas** [comment]
Sites are set up with urls
`@web`
`@web/fr`
...

It's showing in the dashboard view, and then the 2 subpaths are both added

**Comment by francoislevesque** [comment]
Hey there, we have the same issue on our end.

Sites are set up like that :
@web
@web/en

On my dashboard I see this :
<img width="452" alt="image" src="https://github.com/user-attachments/assets/e1d93e5d-8a9a-4966-8eb0-f119dc701818">

When clicking on /en/immep5/blog379/, it opens /en/en/immep5/blog379.

The site slug is doubled for some reason 🤔

Thank you for your time and support !

**Comment by khalwat** [comment]
Okay, I figured out why this was "fixed" already, but I was unable to replicate it. I was testing it in an environment where the "main" site had no path prefix at all, e.g.: `http://example.com/`, in which case, it would indeed work as expected.

However if the primary site had a prefix, it would fail. I've addressed it in the above commits.

Please try it out as indicated below, to ensure that it has fixed it for your particular setup, and let me know:

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.19”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.19”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v5 as 5.0.3”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
@samuel-clara @francoislevesque @white-lukas let me know how you go with the above ^

**Comment by francoislevesque** [comment]
@khalwat On my end, it seems to do the trick. 
The URLs are now fixed, thank you Andrew !

**Comment by samuel-clara** [comment]
@khalwat "dev-develop-v4 as 4.1.19" fixed this on my end. Thank you so much!
