### ISSUE TITLE
410 Error page not loading when issuing a 410 error through Retour

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-retour#311]
### Describe the bug
I am using Retour and I am removing a load of old news pages (section) for a client.
I have added regex and I have set the error to a 410 (gone).
I have created a bespoke template (my 404 and 503 error templates load and show).
However, the 410 page is just getting the default chrome message and not the bespoke template.
![image](https://github.com/user-attachments/assets/5aee7c44-5e76-42a7-bcf5-ad4b94d3c905)

If I add a simple `{% exit 410 %}` to a craft template, then I do get the custom 410 error page loading
https://github.com/craftcms/cms/issues/15644

Is this an issue/bug with Retour?
Or am I missing a step?

The fact that an `{% exit 410 %}` works would indicate here is no additional config on the server required.

I have tried both a Exact match and a RegEx match.
Some examples:
**Exact Match**
/contact/job-vacancies/contracts-manager-commercial-landscape-construction

**RegEx match**
/news/(.*)

Any ideas?

### To reproduce
Steps to reproduce the behaviour:
1. Create a redirect wither Exact or RegEx Match with a 410 erorr.
2. Hit the old URL and see the native browser default 410 error template. 
--

### Expected behaviour
1. Create a redirect wither Exact or RegEx Match with a 410 erorr.
2. Hit the old URL and see the customer Craft 410 error template load. 

### Screenshots
![image](https://github.com/user-attachments/assets/5aee7c44-5e76-42a7-bcf5-ad4b94d3c905)
<img width="1143" alt="Screenshot 2024-09-03 at 15 48 51" src="https://github.com/user-attachments/assets/9363e13f-c07c-41fb-b4dc-8ef4321b3224">
<img width="1652" alt="Screenshot 2024-09-03 at 15 58 48" src="https://github.com/user-attachments/assets/6bd62a09-d994-45e2-b6ea-1d434fbba068">
<img width="1636" alt="Screenshot 2024-09-03 at 15 58 35" src="https://github.com/user-attachments/assets/2ec6675e-d4ba-4486-a980-9bebdfaa6f9e">
<img width="1531" alt="Screenshot 2024-09-03 at 15 57 56" src="https://github.com/user-attachments/assets/d74a50f1-31ca-4b3a-a127-ab4af9fe9dc5">
<img width="1079" alt="Screenshot 2024-09-03 at 15 59 22" src="https://github.com/user-attachments/assets/5cbcb7eb-b306-44f7-9972-50fd200df532">

### Versions
- Plugin version: 4.1.19
- Craft version: Craft Pro 4.11.5

**Comment by khalwat** [comment]
If you try the analogous thing in Craft:

```twig
{% redirect "/" 410 %}
```

...you'll get the same generic browser error page. I think this is just how some browsers handle an incoming response with a `Location` and the response code set to `410`.

I'm not sure there is anything I can actually do about this, except _maybe_ special-case for a `410` and route through Craft in that case, but that feels icky.

I'm pretty sure this is just a result of Nginx not being configured to send `410` errors to Craft the way it is typically configured to send `404` errors through to Craft.

Ensure that your webserver is set up to redirect not just `404` errors but also `410` errors through Craft like this:

https://github.com/nystudio107/nginx-craft/blob/master/sites-available/basic_localdev.com.conf#L33

```
    # 410 error handler
    error_page 410 /index.php?$query_string;
```

**Comment by khalwat** [comment]
So as it turns out, there was already code in there special-casing for > 400 errors, because we need to render them directly rather than return them... but the issue is it wasn't then just returning the response, it was _redirecting_ the response, which we don't want for a > 400 status code.

This actually _does_ work without having to modify the Nginx config, because Retour is rendering the response itself and returning it, so it isn't then routed through Nginx.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.20”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.20”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v5 as 5.0.4”,
```
Then do a `composer clear-cache && composer update`

**Comment by terryupton** [comment]
Thanks @khalwat - I can confirm this is working as expected now. 👍🏻

**Comment by lejoe** [comment]
Thanks that fixed it for us too!
Any chance we could get a release for this?

**Comment by khalwat** [comment]
Yes, I plan to cut a release soon. I've been a little considered about it because it contains some other changes that I want to make sure I got right before releasing it, but it should be this week.

**Comment by lejoe** [comment]
> Yes, I plan to cut a release soon. I've been a little considered about it because it contains some other changes that I want to make sure I got right before releasing it, but it should be this week.

Cheers for your work and support!
