### ISSUE TITLE
Add Check for Enabled/Disabled Status in Retour Function.

### ISSUE THREAD

**Issue by FabioDiCeglie** [nystudio107/craft-retour#315]
**Description:** 
In the current implementation of the Retour function, there is only a check for draft/revision statuses, but no check for whether the function is enabled/disabled. This could lead to unintended behavior, as disabled entries may still be processed in certain cases.

**Proposed Solution:** 
Update the code to include an additional check for the enabled/disabled status, alongside the existing draft/revision checks. This ensures that only active entries are processed by the Retour function.

**Observation:**
The current code does not filter based on enabled/disabled status.

**Expected Outcome:** 
The Retour function should only consider entries that are both not in draft/revision status and are enabled.

**Comment by khalwat** [comment]
Unless I'm misunderstanding, it's already checking for whether it's enabled or not before creating an automatic redirect:

https://github.com/nystudio107/craft-retour/blob/develop-v5/src/Retour.php#L315

...or are you meaning something else?
