### ISSUE TITLE
str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated

### ISSUE THREAD

**Issue by eeeeeeeeeve** [nystudio107/craft-retour#317]
### Describe the bug
When attempting to save a Craft Commerce Product, the internal Variants are also saved. Variants can have URLs but don't have URIs. This causes a deprecation error [here](https://github.com/nystudio107/craft-retour/blob/v4/src/Retour.php#L324).

### To reproduce
Steps to reproduce the behaviour:
1. Attempt to save a Craft Commerce variant with deprecation error reporting on.

### Versions
- Plugin version: 4.1.19
- Craft version: Craft Pro 4.13.3

**Comment by daniellelecomte** [comment]
Also seeing this! +1 😄

**Comment by khalwat** [comment]
Can someone show me the actual deprecation error that you're seeing?

Oh I see, it's in the title -- never mind.

**Comment by khalwat** [comment]
Addressed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.20”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.20”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v5 as 5.0.4”,
```
Then do a `composer clear-cache && composer update`

**Comment by eeeeeeeeeve** [comment]
Thanks so much for the fix! Wondering if you have a planned date for the official release for this?

**Comment by khalwat** [comment]
Should be this week or early next. It contains some other changes that I need to vette & document
