### ISSUE TITLE
Event for extending redirect types (additional HTTP status codes)

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-retour#319]
### Is your feature request related to a problem? Please describe.

We get various requests from scripts/scanning tools which probe paths like /wp-login.php. These show up in the redirect statistics often as unhandled. To "handle" such requests I could send 410 gone, but this path never actually existed in the first place. Feeling a bit juvenile, I could send 418 I am a teapot (A sort of legitimate HTTP code, but kind of not) because these requests are junk traffic and deserve similar treatment.

However, I wouldn't expect Retour to just add this in the core plugin, but the potential option of being able to extend the available options through an event seemed like a potential use case which aside from my potentially not so professional example above, could be used in more sane scenarios, if there is a need to send a different HTTP status code beyond the one's provided by the core plugin.

### Describe the solution you would like

An event that can be used in a plugin/module that can extend additional HTTP redirect options from the default ones provided, making them available in the dropdown field for creating/managing redirects

### Describe alternatives you have considered

It could be added into the core plugin, but I don't think that's really an option :)

The existing events around redirects might be able to do this through a plugin/module as an alternative, just without management through the Retour CP or a general Craft CMS SITE_URL event to match on request paths.

### Additional context

I have absolutely no life I know.

**Comment by khalwat** [comment]
So the best way to handle this is probably actually a server-side redirect. Here's an example of doing just that with Nginx:

```
    # For WordPress bots/users
    location ~ ^/(wp-login|wp-admin|wp-config|wp-content|wp-includes|xmlrpc) {
        return 301 https://wordpress.com/wp-login.php;
    }
```

I'm just sending them to `wordpress.com` since that's apparently what they are looking for :)

ref: https://github.com/nystudio107/nginx-craft/blob/master/sites-available/somedomain.com.conf#L72

**Comment by jamesmacwhite** [comment]
@khalwat Fair point, in the case of us we are on Craft Cloud which is serverless, so no NGINX or Apache config to do that traditionally. However the alternative I went with was setting up a site route with regex rules to match on the various paths and then return the 418 template on that.

**Comment by khalwat** [comment]
@jamesmacwhite do they have the facility to add a CloudFlare redirect?

**Comment by jamesmacwhite** [comment]
@khalwat No, redirect handling is pretty limited currently, e.g. to do apex to www redirection, it's hooking into on before request in app.web.php, it is on the roadmap for improving though. Something like Retour is very much welcome for handling the day to day stuff.

We have basically created a site URL route which is a honey pot to catch the dodgy requests using regex patterns and return a _teapot.twig template which throws the 418 HTTP error through `{% exit 418 %}` leveraging the configured error template path to achieve it.

We could of course just use Retour to catch them and serve something like 410 Gone, but I fancied serving a teapot instead. We could also send them to anywhere else not us, but a teapot is fine.

**Comment by khalwat** [comment]
Well, you could just set up a redirect in Retour like the one in the Nginx config... do a regex match and redirect people to Wordpress.com rather than returning `418` or whatever :)

**Comment by jamesmacwhite** [comment]
Very true, but serving a teapot was just too funny not to do it :D

**Comment by khalwat** [comment]
Also if you _really_ wanted the `418` you should be able to do that by hooking into the events that Retour provides in a little custom PHP module class:

https://nystudio107.com/docs/retour/advanced.html#resolve-redirect-events

You can match however you like, and set the `redirectHttpCode` to whatever you want.

**Comment by jamesmacwhite** [comment]
Thanks, I did look into the events and may revisit.
