### ISSUE TITLE
Using global variables in redirect rules

### ISSUE THREAD

**Issue by Djive** [nystudio107/craft-retour#32]
We have 130 sites (city portals) in a multi-site configuration.
We did some URL changes to them and need to find a simple way of redirecting those.
We have parts of URLs for cities saved as Global Variables.

Can we use Global Variables in the plugin? (Tried with parameters but it didn't work.)
That would enable us to only have 1 redirect for something, instead of 130.

Thanks!

**Comment by khalwat** [comment]
This is something that will be coming when https://github.com/nystudio107/craft-retour/issues/6 is implemented
