### ISSUE TITLE
Fatal Error preg_match on unhandled 404s

### ISSUE THREAD

**Issue by matt-adigital** [nystudio107/craft-retour#33]
Recently upgraded a site from Craft 2 to Craft 3, all worked on Craft 2 but Craft 3 version shows an error on an unhandled 404 page if it hasn't had a specific rule set up. On Craft 2 the 404 page would be shown by default instead of the internal server error page.

404 template: https://www.windermere-lakecruises.co.uk/404
unhandled 404: https://www.windermere-lakecruises.co.uk/testing
handled 404 redirected: https://www.windermere-lakecruises.co.uk/hire.php

A full stack trace of the error can be seen here: https://dev.windermere-lakecruises.co.uk/testing
Working Craft 2 functionality can be found here: https://old.windermere-lakecruises.co.uk/testing

PHP version | 7.1.22
Craft edition & version | Craft Pro 3.0.35
Retour version | 3.0.18

Please let me know if you need any further info. Thanks.

**Comment by khalwat** [comment]
So I'm a little unclear on what error you're reporting here?

If a 404 isn't handled by Retour, it should just degrade properly to whatever page handler you have in place; for instance, this is a Craft 3 website with Retour installed:

https://nystudio107.com/this-does-not-exist

...and it redirects to the normal 404 page you'd expect.

The error you're referring to seems to be related to the PHP version you're using along with the RegEx you're using?

https://stackoverflow.com/questions/3538293/php-regular-expression-pcre-does-not-support-l-l-n-p

**Comment by matt-adigital** [comment]
All environments are running PHP 7.1.22

As for the regex, it is also unchanged between old, dev, and live.

The regex was indeed the issue though. Although it worked fine on Craft 2 it seems that Craft 3 must be stricter with the syntax checking. Instead of silently failing and allowing the 404 to still occur it throws a server error instead now. I had 5 static redirects in place which had incorrect regex syntax and I've now editted these and the issue is resolved. Thank you for you help in suggesting that it was the regex causing this issue.
