### ISSUE TITLE
Data not available in Chrome browser after 6 pages of redirects

### ISSUE THREAD

**Issue by bsmall512** [nystudio107/craft-retour#34]
Hello, 
I am on a project redoing a large website. Yesterday I was on the 6th page of redirects and after saving a new static redirect, I was unable to see any of my previously saved redirects. The table says "No Data Available." When I open up the admin panel in incognito mode, I am sometimes able to see the data and sometimes not. I have rebooted the admin panel, the chrome browser, and the whole computer. Any help would be appreciated.

**Comment by adamhenretty** [comment]
Might be a related issue to this that I am having. When you click on a different page in the pagination, after about 2 or 3 seconds you get taken back to the first page, so you can never view any of the other pages.

**Comment by martyspain** [comment]
I've been experiencing the same issue as @adamhenretty. Clicking on any page in the pagination other than '1' results in the chosen page flashing up briefly, and then the first page reloads.

**Comment by khalwat** [comment]
ooooooooh, I know what this is. It's the errantly done "live data" which reloads the data every 3 seconds. I bet you that means it is incorrectly reloading the wrong page.

I actually think the issue that @adamhenretty & @martyspain mention is entirely unrelated to the issue that @bsmall512 has reported.

**Comment by khalwat** [comment]
@bsmall512 what version of Retour are you using?  Also if you have the Chrome JavaScript console open, do you see any errors logged?

Also are you seeing any errors from Retour logged in your `storage/logs/web.log`?

**Comment by khalwat** [comment]
@martyspain @adamhenretty your issue has been fixed in 3.1.3: https://github.com/nystudio107/craft-retour/releases/tag/3.1.3

@bsmall512 I'm going to need some additional information from you to help diagnose what could be going wrong with your separate issue

**Comment by bsmall512** [comment]
@khalwat Sorry I forgot to include error messages! 

We are using 3.1.1

This shows up in the chrome console:
Mixed Content: The page at 'https://mysite.com/admin/retour/redirects' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mysite.com/japan/?redirected=%E2%9C%93'. This request has been blocked; the content must be served over HTTPS.

The 'http://mysite.com/japan/?redirected=%E2%9C%93' url is something I entered and then erased. Somehow it is still choking on that deleted address.

**Comment by martyspain** [comment]
@khalwat Confirmed the pagination issue is fixed this morning - thank you very much for the fast response! Apologies for diverting this issue with a different one.

**Comment by khalwat** [comment]
@bsmall512 where did you enter and erase that address? Do you mean you set up a redirect in Retour?

**Comment by bsmall512** [comment]
@khalwat Yes, I set up a redirect in retour.

**Comment by bsmall512** [comment]
@khalwat For example this is a url that has a checkmark in it that would be added to the url if someone in japan chose the japanese version of our site:
http://mysite.com//japan/terms-of-service?selected-locale=✓

**Comment by khalwat** [comment]
hmmm @bsmall512 can you check the database in the `retour_static_redirects` table to see if it's still listed there? Also can you try clearing Retour's caches?

If it works sometimes in an incognito browser, it's making me think it could also be some kind of weird local cache. Can you perhaps also try from a different machine/account?

**Comment by bsmall512** [comment]
@khalwat I think clearing the cache's worked. I'm not having a problem so far today.

**Comment by bsmall512** [comment]
@khalwat I haven't had a problem since I cleared the cache. Thanks for your help!

**Comment by khalwat** [comment]
Great!
