### ISSUE TITLE
Upgrade league/csv to 9.x

### ISSUE THREAD

**Issue by sjelfull** [nystudio107/craft-retour#36]
The 8.x version isn't supported anymore, and I hope to upgrade Beam to 9.x at some point. Will have to downgrade it for now because it clashes with Retour and Feed Me.

**Comment by khalwat** [comment]
Done in https://github.com/nystudio107/craft-retour/releases/tag/3.1.5

**Comment by timkelty** [comment]
@khalwat please reopen, it seems the change got reverted: https://github.com/nystudio107/craft-retour/commit/112b0b77515befe1dbc4678d8b42d827c5ef6595

**Comment by khalwat** [comment]
We discussed this via Discord ya?

**Comment by timkelty** [comment]
If by discussed, you mean Tim whined, yes :)

Not an active problem for me anymore though, so keep it closed until it is, I suppose.
