### ISSUE TITLE
CSV Import Errors

### ISSUE THREAD

**Issue by nateiler** [nystudio107/craft-retour#38]
Getting an exception when trying to import redirects via .csv:
Exception: BadMethodCallException
Method: League\Csv\Reader::setOffset()
Ref: src/controllers/FileController.php:99

The installed CSV package has `setHeaderOffset` not `setOffset`.   Tested that change, success .... however

src/controllers/FileController.php:101
`$csv->each` will begin to scream...

Waving the white flag...

Package information installed
Retour: "version": "3.1.5",
            "source": {
                "type": "git",
                "url": "https://github.com/nystudio107/craft-retour.git",
                "reference": "f31956852508fe8c37d354527d5b605403f8f1a8"
            }

League CSV: "version": "9.1.4",
            "source": {
                "type": "git",
                "url": "https://github.com/thephpleague/csv.git",
                "reference": "9c8ad06fb5d747c149875beb6133566c00eaa481"
            }

**Comment by khalwat** [comment]
ugh. Alright. This stems from trying to support more than one version of the library, for compatibility with a few other plugins.

I'm going to have to roll it back down to 8.x

This means, however, that you will have issues trying to install it with another plugin that requires 9.x

**Comment by khalwat** [comment]
Fixed in 3.1.6 -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.6
