### ISSUE TITLE
[FR] Feature Request: Redirects from File/Config

### ISSUE THREAD

**Issue by kmgdevelopment** [nystudio107/craft-retour#39]
I'd love to see a way of configuring the redirects in a file instead of through the database. Since the plugin already uses CSV for importing, maybe a setting to point to a CSV file with pre-populated redirects? Alternately assigning redirects via a Craft config file would work too.

**Comment by khalwat** [comment]
So you're saying you want a file to be the source of truth for redirects?

I'll leave it open as a FR, but I'd be interested in hearing more about the use case?

**Comment by kmgdevelopment** [comment]
Hi Andrew,

For one thing it would allow me to save my redirects within my Git filesystem so I can track changes as well as have a static backup if the database is corrupted. 

It would also be nice just to have all of the redirects on one page where I can group similar redirects together. It's harder to get a big-picture view of the redirects by paging through the control panel UI.

**Comment by khalwat** [comment]
So given that you can export all of the redirects to a CSV (and then also re-import them if you like), I'm going to hope that's enough for this use case.
