### ISSUE TITLE
Imported routes don't appear in CP (but they exist!)

### ISSUE THREAD

**Issue by lindseydiloreto** [nystudio107/craft-retour#42]
**Retour v3.1.6**

The client imported a CSV file of redirects... They told me "it didn't work," because the redirects were not showing up in the control panel.

But here's the catch... it _did_ work. Turns out those redirects were stored in the database, they just weren't showing up in the CP for whatever reason! The redirects were still functioning properly, despite being invisible to us.

**Database:**

<img width="988" alt="2019-02-15 at 5 09 32 pm" src="https://user-images.githubusercontent.com/5309692/52892119-95aa1680-3144-11e9-9b79-947389477852.png">

**Control Panel:**

<img width="1196" alt="2019-02-15 at 5 09 58 pm" src="https://user-images.githubusercontent.com/5309692/52892123-9e025180-3144-11e9-94f6-3250cd1cc613.png">

Disabling the plugin disables the redirects. Enabling the plugin enables the redirects (though they still don't show up in the CP).

**Comment by khalwat** [comment]
So if they aren't showing up in the CP, exactly what _is_ displayed in the CP?

Did you check for JavaScript errors in the console?

**Comment by khalwat** [comment]
I think I remember someone saying that if the Dolphiq Redirect Manager is installed, it somehow interferes (likely inadvertently) with that display in Retour. Why? I've no idea. But it's weird to have both installed anyway so....

**Comment by lindseydiloreto** [comment]
Turns out, this one was all our fault...

We had a custom route that was aggressively matching _any_ three-segmented URL. This was inadvertently catching one of the AJAX calls that Retour was making, and serving up a 404 instead of the intended response.

We'll adjust our routes to be a bit stricter. Cheers to @khalwat for helping me troubleshoot this. 🍺
