### ISSUE TITLE
[FR] Ignore specific redirects/patterns on 404s list

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-retour#43]
Some of my js plugins require specific files that i dont have on page. These 404s just clutter my redirect list. It would be good if i could blacklist them from being displayed.

**Comment by khalwat** [comment]
You have js plugins that are constantly generating 404s? Can you give me some more detail on this, I'd think you'd want to be aware of it or fix it...?

**Comment by piotrpog** [comment]
For example, some .map file that map compiled css to scss. I am aware that it should be developer responsibility to avoid such situations. But we dont always have full control over frontend code that might be handled by different people.

**Comment by khalwat** [comment]
Seems reasonable to me that we could have a list of RegEx's for excluding certain URLs.

If we also had the same thing, but for referrers, that'd also address your other issue:

https://github.com/nystudio107/craft-retour/issues/44

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-retour/commit/01ae9a842ae373278a15dd050f0ae59cd7f76c9c
