### ISSUE TITLE
Dont add admin/retour/dashboard to "Last Referrer url"

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-retour#44]
If i click missing URL address from within retour dashbourd, `website.com/admin/retour/dashboard` appears in "last referrer URL column". 
This infomation is not really usefull, I would rather know original referrer url :)

**Comment by khalwat** [comment]
When you click on the link to open up that URL you mean? Technically that's creating a new page load, and the referrer would be the page it's coming from... I could have it not have any referrer at all, but I'm not sure how I'd have it preserve whatever the last referrer was.

**Comment by piotrpog** [comment]
> When you click on the link to open up that URL you mean?

Yes. I just thought that having "website.com/admin/retour/dashboard" saved as last referrer is not really usefull for anything.

**Comment by khalwat** [comment]
So realistically, you're right that it isn't useful for anything... but Retour doesn't do anything special when opening up that link, it just opens it. Special-casing this in some manner to try to let Retour know that the link is coming from Retour might be a little weird?

I'm not sure. Part of my doesn't like secret hidden things. Another part understands that it's fairly pointless to have this as a referrer.

**Comment by khalwat** [comment]
Can be solved via https://github.com/nystudio107/craft-retour/issues/43
