### ISSUE TITLE
[FR] Option to not have a "live" dashboard

### ISSUE THREAD

**Issue by aelvan** [nystudio107/craft-retour#45]
The dashboard currently refreshes (three requests) every couple of seconds, which puts a toll on the server and makes the UX on the list of 404s terrible (because items move). Although I hate the whole idea of it, I can see how some people could find this interesting. But could we at least get a config setting to turn this off?

**Comment by khalwat** [comment]
Sounds reasonable.

**Comment by khalwat** [comment]
Drats. I should have gotten to this one in 3.1.8 -- will do so in the next version, sorry @aelvan

**Comment by khalwat** [comment]
Removed in https://github.com/nystudio107/craft-retour/commit/6e36f3c57c9f6a4cb1d04abb3b250a7fb1d641db

**Comment by khalwat** [comment]
Decided to do this in a better/more flexible way: 

* Added a **Dashboard Refresh Interval** control to let people choose the refresh interval (or disable it)

https://github.com/nystudio107/craft-retour/commit/83fa048f537a40e67cb7f9bad96662761953a62f
