### ISSUE TITLE
Disable "Redirect To" link when there is a token in the destination url

### ISSUE THREAD

**Issue by elivz** [nystudio107/craft-retour#47]
I just got a frantic email from a client, concerned that when they clicked on the "redirect to" link in the Redirects list, it took them to a 404 page. As I eventually discovered, the problem is that it's a RegEx redirect, with a token in the destination URL. Of course, going to `http://example.com/blog/$1` won't actually work. I figure it might be relatively simple to check for `/\$\d+/` in the destination of a RegEx Match-type redirect, and in that case *not* create a link out of the destination to avoid confusion.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/c972aa7aae8951723f51dffe2943a92aae8fe3dd

**Comment by elivz** [comment]
Thanks Andrew!
