### ISSUE TITLE
[FR] Add global as well as localized per-site redirects

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-retour#5]
Currently all of the redirects are global in Retour; add the ability to have site-specific redirects via a migration and additional code support.

**Comment by ademers** [comment]
Will this allow for redirecting to sites other than the primary one in multisite?

For example: `/old-stuff` --> `secondary.example.com/new-stuff`

**Comment by khalwat** [comment]
Yes @ademers -- that actually should work already, if you're going from a URI to a full URL.

The reverse is now also true. I was over-thinking it, and going to come up with a site-selector and such, but that's really not needed.

We just need to be able to redirect by full URL (which is what I've added) or path only (which is what it does now).

That way you can do:

`http://somesite.com/woof` -> 

Implemented in https://github.com/nystudio107/craft-retour/commit/77e1edcc3225a6019a469ef043bd647106266d8c
