### ISSUE TITLE
Multisite - Permissions

### ISSUE THREAD

**Issue by limesquare-nl** [nystudio107/craft-retour#50]
On the dashboard and redirect page the multi site select box shows 'All sites' for user who have only access to 1 site. Another problem is when adding a redirect a user can see/select all sites from the select box. In both cases only the site the user have permissions for should be visible.

**Comment by khalwat** [comment]
hmmmmmm. Is this how Craft works as well?

**Comment by khalwat** [comment]
Can you give me some more information on how you have things configured? I'm looking at the code, and it appears that it should only list sites that the current user can edit.

**Comment by khalwat** [comment]
Addressed the sites listed when editing a redirect in https://github.com/nystudio107/craft-retour/commit/50c90fa0158ad14a7d4448a3485a5a1a6a66ca62

Waiting for confirmation on the first issue

**Comment by limesquare-nl** [comment]
Thank you for changing the way sites are listed when editing. 

When you have access for one multisite you can view redirects from other sites through the "All sites" selection. You want to isolate users so that they cannot view and / or edit other sites redirects.

**Comment by khalwat** [comment]
Ahhh thank you for that clarification.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/aa1c8edd0b51147d534b058f2deeb029423e7eb4
