### ISSUE TITLE
Retour capabilities

### ISSUE THREAD

**Issue by jdozierezell** [nystudio107/craft-retour#52]
These are more questions than issues, so apologies if this isn't the right place to address them, but I'm considering moving from Wordpress to Craft and am wondering how the transition will affect the way we handle redirects.

1. Is it possible to redirect to external urls? My company uses an external event platform that has really ugly urls, so we're in the habit of creating a shorter url that hits our Wordpress install and then sends users to the external event platform. I don't see any examples of this in your screenshots, so I wanted to confirm that this is/isn't a possibility.

2. Would Retour be effective in a headless implementation of Craft? I'd love to implement Craft as a Vue application, but I'd need the same functionality mentioned above. My guess is the answer is no here, but I thought I'd ask. 

Again, if this isn't the right place to ask these questions, my apologies. I just didn't see anywhere else on your site to do so. Thanks!

**Comment by khalwat** [comment]
So I think there's a little confusion here, let's see if we can't clear it up.

> 1. Is it possible to redirect to external urls? My company uses an external event platform that has really ugly urls, so we're in the habit of creating a shorter url that hits our Wordpress install and then sends users to the external event platform. I don't see any examples of this in your screenshots, so I wanted to confirm that this is/isn't a possibility.

Yes, Retour can redirect to any external URL.

> 2. Would Retour be effective in a headless implementation of Craft? I'd love to implement Craft as a Vue application, but I'd need the same functionality mentioned above. My guess is the answer is no here, but I thought I'd ask. 

If it's a headless Craft implementation, then Craft itself won't be handling the incoming URLs for routing; this is something you give up when you go with a headless CMS. So for the Vue SPA site you're discussing, Craft will never see the incoming routes, and therefor Retour will never see them either.

So no, this won't work _unless_ you have Craft handling the routing. Which typically you would not do for an SPA.
