### ISSUE TITLE
Migration for Craft 2 retour widget

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-retour#53]
Really minor thing, but the Retour widget type is not migrated from Craft 2. I wrote a quick content migration, but maybe if you wouldn't mind adding it to the plugin's migrations, that would be great! It's a simple update query on the widget type:

https://gist.github.com/jamesmacwhite/bbce570b02ac4e83cf1c98fad7fde600

Thanks!

**Comment by khalwat** [comment]
Ah this is great...

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-retour/commit/3c13c93ad5217e0372ac0622fb28f743b9d8057f

**Comment by jamesmacwhite** [comment]
@khalwat Thanks for implementing!
