### ISSUE TITLE
Retour widget icon not loading in widget menu

### ISSUE THREAD

**Issue by jamesmacwhite** [nystudio107/craft-retour#54]
Just a minor thing, but the widget icon doesn't seem to load when selecting from the widget menu:

https://github.com/nystudio107/craft-retour/blob/v3/src/widgets/RetourWidget.php#L58

Rather than it being a path problem, it does look like the specified SVG file is loaded, but it doesn't display properly. If I point the iconPath to the version at the root `nystudio107/retour/icon-mask.svg` it displays OK.

I think this occurred a few days ago when the assets were updated, potentially looks like an issue with the SVG itself.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/294c616bcfa6f26fd245eae00d37ac39486ea046
