### ISSUE TITLE
Retour randomly deletes static redirects when a new redirect for a specific site is added

### ISSUE THREAD

**Issue by aelvan** [nystudio107/craft-retour#55]
*Steps to reproduce:*

1) Create some static redirects that are not tied to a specific site.
2) Create one static redirect that _is_ for a specific site.

*Result:*

One of the static redirects that was not tied to a specific site is deleted.

Tested with Retour 3.1.9 and 3.1.10 on three different Craft installs.

Needless to say, pretty painful.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/releases/tag/3.1.12
