### ISSUE TITLE
Redirect only those that don't exist

### ISSUE THREAD

**Issue by hatzipanis** [nystudio107/craft-retour#60]
I'm having a little trouble creating a single rule that redirects entries that don't exist while leaving those entries that do exist alone. Is this possible?

I want a rule to something like this:

- `/news/article-1` does exist so do not redirect
- `/news/article-2` does not exist so redirect to `/news`
- `/news/article-3` does not exist so redirect to `/news`
- `/news/article-4` does exist so do not redirect

Etc. 

Is it possible to do this as a single rule? The use case is that we've only moved some of the news, events, etc to the new website.

**Comment by khalwat** [comment]
Since Retour doesn't do anything until a 404 is thrown, you don't have to worry about the case where something exists. Retour will just never handle it.
