### ISSUE TITLE
[FR] Add filter to hide handled 404s

### ISSUE THREAD

**Issue by neokoenig** [nystudio107/craft-retour#61]
When you've got 1000's of 404s to deal with, having the ones which are handled in the list is a little annoying - would be great to have a seperate view or filter which only shows unhandled 404s.

**Comment by khalwat** [comment]
Right so this ties in with https://github.com/nystudio107/craft-retour/issues/62 in that there would need to be some kind of UI widget that lets people show:

  1. All 404s
  2. Unhandled 404s
  3. Non-"crap" 404s

**Comment by darylknight** [comment]
+1 for this. We have a site generating hundreds of line items per month; seeing the ones that have already been dealt with takes up a lot of space.

**Comment by johndwells** [comment]
I came here looking for this issue, knew that surely someone else had already requested it. :)

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-retour/commit/6dbe611dcf07c4f1878d0d3b10cfd42105d41d0e

<img width="479" alt="Screen Shot 2019-11-11 at 6 25 28 PM" src="https://user-images.githubusercontent.com/7570798/68629305-4e716c00-04b1-11ea-9e95-3bec0c6a0567.png">

**Comment by darylknight** [comment]
Awesome, thanks!
