### ISSUE TITLE
[FR] Allow modules to register custom match functions

### ISSUE THREAD

**Issue by dlindberg** [nystudio107/craft-retour#63]
Allow modules to register custom match functions in addition to plugins, for cases where that makes sense if a developer is following [Craft's guidelines](https://docs.craftcms.com/v3/extend/#modules-vs-plugins) for what's a module and what's a plugin.

Perhaps with a documentation update for those that don't work directly with creating modules and plugins that often, that they can register custom controllers directly with the CMS and that those controllers can be the redirect endpoint as well. It's one of those things that is totally obvious when you stop and thing about it but not necessarily completely clear if you don't. Retour's ability to handle a massive number of redirects while not needing a massive look up table to do it is one of its best but not super obvious features, using [FeedMe](https://github.com/nystudio107/craft-retour#custom-match-functions-via-plugin) and the right field setup you can literally migrate your redirects right along with your content, which has the potential to save an awful lot of time.

**Comment by khalwat** [comment]
Yeah this is something I need to overhaul for Craft 3. I should be throwing an event to allow plugins to register handlers, rather than looking for a function in a specific plugin.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-retour/commit/4b73a5f74e6d8e7e87abfdfeb4e4490a53619a28
