### ISSUE TITLE
Source paths with `.html` have invalid server response

### ISSUE THREAD

**Issue by benjamin-smith** [nystudio107/craft-retour#64]
Craft CMS 3.1.20.1
Retour 3.1.5
PHP 7.2.19
nginx 1.14.0

---

For any redirects with a source URL that ends in `.html`, the server response includes a `Location` header, but it still returns a 404 response, and the user is not redirected.

```bash
curl --head http://somedomain.com/static/about_us.html
```

Returns the following headers:

```
HTTP/1.1 404 Not Found   <----- note this is 404
Server: nginx
Date: Tue, 11 Jun 2019 19:06:25 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: Craft CMS
Location: http://somedomain.com/our-story   <----- but there is a Location header
```

Here is how the redirect is configured in the `retour_static_redirects` table:

```
INSERT INTO `retour_static_redirects` (`id`, `dateCreated`, `dateUpdated`, `uid`, `siteId`, `associatedElementId`, `enabled`, `redirectSrcUrl`, `redirectSrcUrlParsed`, `redirectSrcMatch`, `redirectMatchType`, `redirectDestUrl`, `redirectHttpCode`, `hitCount`, `hitLastTime`)
VALUES
	(8, '2019-05-08 18:43:06', '2019-06-11 18:47:12', '9d405c15-a8c8-40a4-9791-09901769c84a', NULL, 0, 1, '/static/about_us.html', '/static/about_us.html', 'pathonly', 'exactmatch', '/our-story', 301, 53, '2019-06-11 18:47:12');
```

**Comment by benjamin-smith** [comment]
For what it's worth, the proper status code of `301` is being transmitted all the way to the yii2 response object in `Response::redirect()`: https://github.com/yiisoft/yii2/blob/2.0.17/framework/web/Response.php#L869

Yet 404 is what the server is responding with for some reason.

**Comment by benjamin-smith** [comment]
Further info - this is only an issue on nginx, apache 2.4 is fine.

**Comment by khalwat** [comment]
Yeah this is going to be an issue with your server config. Probably what is happening is you have an Nginx `location` block that matches `.html` somewhere, yes?

**Comment by khalwat** [comment]
btw @benjamin-smith feel free to ping me on Discord if realtime chat on this will be more helpful to you. I'm fairly sure this is going to end up being a server config issue tho.

**Comment by benjamin-smith** [comment]
Thanks @khalwat ! I thought the same thing that the Nginx config was the issue here (it may be still!). The only reason I am hesitant is that the 404 response does include a `X-Powered-By: Craft CMS` response header and has the proper `Location` header, meaning the request is processed by Craft for sure. Ngnix may be overriding the response code for some reason, but it's not something I've seen before. I reverted my Nginx config to something very stock/basic and the issue persisted.

In the meantime, we just move to Apache, as there was no compelling reason that forced us to use Nginx.

I'll ping you on Discord next time - although I do like GH issues for the sake of sharing with a broader audience and ability to search these issues via Google!

**Comment by khalwat** [comment]
I've seen this before -- share your Nginx config?

**Comment by khalwat** [comment]
Will re-open if we get more information.
