### ISSUE TITLE
Permmission Issue

### ISSUE THREAD

**Issue by stevepsharpe** [nystudio107/craft-retour#66]
We have version 3.1.16 installed on Craft 3.1.28.

We have an "editor" user group and we want them to only access dashboard/redirects. However they can't see retour in the sidebar, and if they try and access it directly they get "Unauthorised". I also enabled the settings permission too, still no joy.

Let me know if you need anymore info to help?

Cheers

**Comment by stevepsharpe** [comment]
Just to add, I can a Retour widget just fine.

**Comment by khalwat** [comment]
I think you probably also need to give them access to the Retour plugin in Craft's permissions?

**Comment by stevepsharpe** [comment]
@khalwat Yes that worked, sorry I missed that.
