### ISSUE TITLE
Pagination and search not working

### ISSUE THREAD

**Issue by garethwatson** [nystudio107/craft-retour#67]
We have an installation of Retour in place. Pagination and search do not work. 

https://streamable.com/p2r9x

We have almost 600 redirects created via a CSV import and can see that these are working but cannot navigate to or otherwise view redirects not found on the first page of the admin section in Craft.

**Comment by khalwat** [comment]
Someone else ran into something very similar, and it ended up being an issue with their `.htaccess` file.

Their SEO company asked them to add some code to the `.htaccess` that ended up causing issues. Can you show me your `.htaccess` file?

For the record, this is the Craft CMS default `.htaccess`:

```
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Send would-be 404 requests to Craft
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
    RewriteRule (.+) index.php?p=$1 [QSA,L]
</IfModule>
```

https://github.com/craftcms/craft/blob/master/web/.htaccess

**Comment by khalwat** [comment]
Will re-open the discussion if you return with more info.

**Comment by lukasNo1** [comment]
I got the same problem.

Htaccess is just

```
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
```

Doesn't work with the craft default either.

Craft 3.2.9
Retour 3.1.22

182 Redirects imported via csv.

**Comment by lukasNo1** [comment]
Nevermind the error was with our language redirect.

The base url is set to /
We have a multi site setup, so we redirect / to the users preferred locale (f.ex /de/)

Even the admin panel gets redirected to /de/admin

So the request:

`http://localhost:8000/retour/tables/redirects?sort=hitCount%7Cdesc&page=4&per_page=20&siteId=0`

Got redirected to :
`http://localhost:8000/de/retour/tables/redirects`

(Query string removed).
Fixed this now.

Maybe this can be considered for future development.

**Comment by khalwat** [comment]
This probably is fixed via https://github.com/nystudio107/craft-retour/commit/8536be863d498543782a6cba537e702975907c7b
