### ISSUE TITLE
Unable to upload a new asset in Craft 3.2 with Retour enabled

### ISSUE THREAD

**Issue by martinleveille** [nystudio107/craft-retour#68]
### Description

When Retour is enabled, we're unable to upload a new asset in Craft 3.2.

### Steps to reproduce

1. Install Craft using the composer create project
2. Create a new asset volume
3. Upload a new asset in that volume
4. The upload works perfectly :)
5. Install the Retour plugin
6. Upload a new asset in the volume
7. The upload fail with the error : Upload failed. The error message was: “Asset is missing its folder ID”

### Additional info

- Retour version: 3.1.20
- Craft version: 3.2.4.1
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Only Retour installed

**Comment by zizther** [comment]
Same issue my end.

**Comment by petertindemans** [comment]
Same here, and same steps to reproduce

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/8600c31157cc20b38cfe04f400f4ac770e06a978
