### ISSUE TITLE
Automatic redirects not including site specific prefix

### ISSUE THREAD

**Issue by dbusck** [nystudio107/craft-retour#69]
The automatic redirects does not seem to work properly for sites with its own base url – I have sites set up using the language code as a path prefix, like such: `https://example.com/fr/`.

However the automatic redirects always end up as `/entry-url` (not including the language code), where they need to be `/fr/entry-url`.

Thought this was supported after [2e0090f](https://github.com/nystudio107/craft-retour/commit/2e0090fcd6e9bf3b0034b42d3c419e990c196bec) but I still have this issue.

Craft 3.1.21.1
Retour 3.1.22

**Comment by chasegiunta** [comment]
Looks like we're also seeing this or something similar. The legacy URL is taking the site prefix into account in it's matching when it shouldn't - the temporary workaround of course has been to prepend the site prefixes in the legacy URL in redirect rule, but not ideal.

**Comment by dbusck** [comment]
Thanks for sharing you also have the issue. Do you mean manually editing the redirects in the dashboard? Not really an option for me with 1000+ entries with multiple editors unfortunately.

I'm now looking if I can do some trickery in the `ResolveRedirectEvent` until it's fixed, although I feel a bit tricked since the sole reason I bought the plugin was to manage automatic redirects in case of slug edits by editors – there are other free plugins for just creating redirects.

**Comment by khalwat** [comment]
@dbusck there are other free plugins for just creating redirects, but they do it in such a manner than you absolutely would not want to add 1,000 redirects. They add each redirect to the Yii2 rules that are evaluated on every request.

This is fine for a couple of redirects, but when you get up into hundreds or thousands, it will negatively impact the site performance for all requests.

**Comment by khalwat** [comment]
Regarding your issue @dbusck since the prefix is part of the `siteUrl` probably it makes the most sense to change the **Legacy URL Match Type** to **Full URL** so that it includes the full URL rather than just the URI segment in the matching.

I'm going to have a look to see if it makes sense to have it just do this by default, or whether it should be an option (I'm leaning towards the latter).

**Comment by khalwat** [comment]
@chasegiunta that sounds different, can you file a separate issue please?

**Comment by dbusck** [comment]
Hey, thanks for getting back! Did not mean sound rude – it's a great plugin. I need the automatic slug redirect though, but after buying the plugin it doesn't work for me.

Alright, yes being able to set the default for auto-created redirects in 'Settings' would be fantastic!

**Comment by khalwat** [comment]
@dbusck nope not rude at all, I was just explaining a use-case beyond this one!

Implemented this in https://github.com/nystudio107/craft-retour/commit/18dc2c507ee9cb6f118b541e4dce52992c79a347

If you want to test it, you can set your semver to `dev-develop` and you should be able to `composer update` and give it a whirl.

Let me know!

**Comment by khalwat** [comment]
![Screen Shot 2019-08-09 at 10 40 54 AM](https://user-images.githubusercontent.com/7570798/62787222-40ffac80-ba92-11e9-8a5c-1341d58eaaae.png)

**Comment by khalwat** [comment]
Able to give it a whirl @dbusck ?

**Comment by dbusck** [comment]
That does the trick! Thanks @khalwat.
My queue get stuck with 'pending' status now when resaving an entry though, no idea if it's related to this update (already tried clearing the queue and retrying).

**Comment by khalwat** [comment]
@dbusck can you  look in your `queue.log` for errors?

**Comment by khalwat** [comment]
Actually @dbusck if you are able to find any errors in your `queue.log`, please post them in a new issue?
