### ISSUE TITLE
CORS policy issue when using it over https

### ISSUE THREAD

**Issue by jondialpad** [nystudio107/craft-retour#70]
Recently decided to switch to Retour plugin and it seems to be working great on an http environment however it throws a CORS policy error when running on https. 

The plugin installs fine, but the redirects neither show up in the Redirects table in dashboard nor works. However, I can see the redirects stored in the DB `dp_retour_static_redirects` table.

Would you be able to shed some light on it? 

System details and the error is as follows:

System:
Craft Pro 3.1.33
PHP version 7.1.29
Linux 4.9.0-9-amd64
PostgreSQL 9.6.10
Craft Pro 3.1.33

Error:
`Mixed Content: The page at 'https://[SITEURL]/retour/redirects/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://[SITEURL]/retour/tables/redirects/?sort=hitCount%7Cdesc&page=1&per_page=20&siteId=0'. This content should also be served over HTTPS.`

`Access to XMLHttpRequest at 'http://[SITEURL]/retour/tables/redirects/?sort=hitCount%7Cdesc&page=1&per_page=20&siteId=0' (redirected from 'https://[SITEURL]/retour/tables/redirects?sort=hitCount%7Cdesc&page=1&per_page=20&siteId=0') from origin 'https://[SITEURL]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`load-error Error: Network Error
    at t.exports (createError.js:15)
    at XMLHttpRequest.f.onerror (xhr.js:87)`

**Comment by khalwat** [comment]
Can you show me how you're declaring your `baseUrl` and `siteUrl` in `genera.php` please?

I think one of these may not be set correctly.

**Comment by khalwat** [comment]
The API URL is declared as a relative URL:

https://github.com/nystudio107/craft-retour/blob/v3/src/assetbundles/retour/src/vue/RedirectsTable.vue#L12

**something** is causing this to resolve to `http`

**Comment by jondialpad** [comment]
@khalwat 
Here is the `baseUrl` and `siteUrl`:

```
    'local' => [
        'baseUrl' => [
            'en_us' => 'http://local.dialpad.com',
            'ja_jp' => 'http://local.dialpad.com/jp',
            'en_gb' => 'http://local.dialpad.com/uk',
        ],
        'siteUrl' => [
            'en_us' => 'http://local.dialpad.com',
            'ja_jp' => 'http://local.dialpad.com/jp',
            'en_gb' => 'http://local.dialpad.com/uk',
        ]
    ]
```

```
    'production' => [
        'baseUrl' => [
            'en_us' => 'https://www.dialpad.com',
            'ja_jp' => 'https://www.dialpad.com/jp',
            'en_gb' => 'https://www.dialpad.com/uk',
        ],
        'siteUrl' => [
            'en_us' => 'https://www.dialpad.com',
            'ja_jp' => 'https://www.dialpad.com/jp',
            'en_gb' => 'https://www.dialpad.com/uk',
        ]
    ]
```

**Comment by khalwat** [comment]
Are you using Project Config?

Do you have a `DEFAULT_SITE_URL` in your `.env` file?

I'm thinking there is probably some kind of setting in in Google App Engine setting, but I'm not familiar with it. Does this help? https://stackoverflow.com/questions/5367974/https-only-in-google-app-engine

**Comment by jondialpad** [comment]
No, we are not using Project Config, and there is no `DEFAULT_SITE_URL` set in the `.env` files. 
I've added the https options to the `app.yaml` as below but still having the same issue. I'll keep looking into it with this direction though. It seems like some sort of setting is forcing it to use `http` initially I think.

```
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
```

**Comment by khalwat** [comment]
Let me know if you figure anything out @jondialpad -- I'm reasonably sure this is a devops issue, and not a Retour issue. But I'd be happy to assist if you find otherwise.

**Comment by khalwat** [comment]
Will re-open if additional information is made available.

**Comment by jondialpad** [comment]
Still looking into it but, couldn't find anything obvious, putting it on backlog for now.

**Comment by khalwat** [comment]
So I had a lightbulb moment @jondialpad  -- let me know if this fixes it for you:

https://github.com/nystudio107/craft-retour/commit/8536be863d498543782a6cba537e702975907c7b

Set your semVer in your `composer.json` to `"dev-develop"` and do a `composer update`

**Comment by khalwat** [comment]
Should be fixed in https://github.com/nystudio107/craft-retour/releases/tag/3.1.24

**Comment by jondialpad** [comment]
That is awesome, it seems to be fixed and working with the instance I am working on as well. Thank you!

**Comment by khalwat** [comment]
yay! Thanks for letting me know @jondialpad
