### ISSUE TITLE
[FR] Add more customization options in redirect events (save, resolve)

### ISSUE THREAD

**Issue by dbusck** [nystudio107/craft-retour#71]
When listening to events (for example `EVENT_BEFORE_SAVE_REDIRECT`), almost nothing can be manipulated before the redirect is saved.

The events would be more useful if both the `legacyUrl` and `destinationUrl` can be manipulated before the redirect is saved. Is this something you have in the pipeline? Or can this already be done in another way?

**Comment by khalwat** [comment]
What's the use-case here?

**Comment by khalwat** [comment]
Ah, it's likely you were trying to do this:

https://github.com/nystudio107/craft-retour/issues/69
