### ISSUE TITLE
ipaddressguide lookup no longer works

### ISSUE THREAD

**Issue by wihodges** [nystudio107/craft-retour#72]
So for some reason the https://www.ipaddressguide.com/ip-geolocation?ip={{{ip address goes here}} always says that "You have exceed your daily query limit."

Wondering if anybody else gets this error? If so maybe use Whatismyipaddrss.com instead: https://whatismyipaddress.com/ip/000.00.00.00 

<img width="926" alt="Screenshot 2019-08-12 17 27 12" src="https://user-images.githubusercontent.com/286956/62902998-f5196580-bd26-11e9-812a-51cad6f904b8.png">

**Comment by khalwat** [comment]
fixed in https://github.com/nystudio107/craft-retour/commit/450153dbd4f427e3f0eaa71ca50e35ec033a0022
