### ISSUE TITLE
[FR] Give regex redirects a priority

### ISSUE THREAD

**Issue by hiasl** [nystudio107/craft-retour#74]
It would be very handy to be able to assign priorities to regex redirects. It would be sufficient to have an additional field where you can enter integers. This field/db column should then be the third sort order criteria, before hits.

Use case: This makes regexes less complex and more easy to maintain, because more general regexes not need rules to prevent matching more detailed ones.

**Comment by khalwat** [comment]
I see, so you want to essentially be able to drag them to re-order the priority?

**Comment by hiasl** [comment]
Not sure if dragging is the solution because with larger amounts of redirects (paging???) this could be inconvenient. I think a simple integer field is straight forward and sufficient.

**Comment by hiasl** [comment]
an example: it makes a big difference which of the following regexes is matched first:
`/articles/.*`
`/articles/science/.*`
So I believe a simple solution it to give them a priority
`/articles/.*` => Prio 100 (handled last)
`/articles/science/.*`  => Prio 10 (handled first)

_Sidenote: maybe escaping / in my example would be necessary ... please ignore this_

**Comment by ilicmarko** [comment]
How would you implement this looking at the UX/UI side. Because this would need to be a sortable list. Because using inputs (numbers) for priorities is never a good solution, they are going to overlap at some point.

**Comment by hiasl** [comment]
I think this is more a "pro" feature than a normal editor feature, therefore from my point of view using input would be ok (maybe the field is only shown when a special config is set). And overlapping is not an issue if the person doing it is aware of it. 

Drag'n'Drop is not an option as rules might have paging.

So maybe providing a pulldown is better where the possible values are either predefined or configurable. Could be "First", "Middle", "Last". Or Prio A - Prio F. Of course this still has the overlapping issue.

**Comment by evanwarner** [comment]
Adding my +1 use case. Currently migrating a site with a HUGE section. Only a handful of the subpages are surviving on the new site, and the rest are being archived on a legacy subdomain. I need to be able to create redirects for the survivors then do a catchall rule for the rest, and obviously the catchall needs to be checked last.

At the moment it looks like the solution is do the individual redirects at the server level so they run before it ever gets to Retour, then put the catchall in Retour.

From a UI perspective, this feature would exist to resolve match collisions, which usually deals with small groups of related rules. The priorities don't need to be global, just constrained to a group. So a way to "group" rules together, or maybe even make them a tree-like structure (where each parent is a higher priority than its children) could be a way to solve it.

**Comment by benjamin-smith** [comment]
UI wise, could be a dropdown with each redirect with Priority 1, 2, or 3. Maybe the range of input is a config var (for 1 through 10, for example). Agreed that a flag to turn this off if not in use would simplify the UI.

Once that is set and stored with each static redirect record, would need to adjust this query to sort the redirects by priority when fetching: https://github.com/nystudio107/craft-retour/blob/22980b2caec171c86ccbdb6641f822d4e711999a/src/services/Redirects.php#L555

**Comment by khalwat** [comment]
UX-wise, I think probably the nicest way to do it might be to just allow people to order them by dragging them in the order they want them to be processed.

The only time I could see this not being great UX, though, is if you're managing a whole lot of redirects.

**Comment by hiasl** [comment]
Just an assumption: But maybe the users with the need for a priority have a whole lot of redirects :-)
and I wrote that before: don't we have paging here?

**Comment by khalwat** [comment]
Sure, but it's possible that something could be done to allow dragging between pages. Probably not very easy, but possible.

Though you're right, for a large number of redirects, I think it might not be ideal anyway... and that's probably who would want it.

**Comment by sgtpenguin** [comment]
Running up against a similar need.  In my case, prioritizing exact matches over regex generally would solve the problem, without the need for ranking and the ux challenges it presents.

example:
Site structure went from /items/some-thing to /work/some-thing

Regex can generally catch most of these, however some slugs have also been modified.  The changed slugs have been input as exact matches, however the regex takes priority and redirects these to the "wrong" slug, ignoring that there is an exact match.

**Comment by khalwat** [comment]
I'm thinking that in general, I agree -- the most specific matches should go first.

**Comment by sgtpenguin** [comment]
Perhaps @hiasl 's case can be solved too
`/articles/.*`
`/articles/science/.*`

By sorting the regex matches (And exact matches) internally and letting ones with more segments to go first?

**Comment by khalwat** [comment]
Trying to effectively determine "segments" in a regex could be dicey, I think. Ultimately the best solution is to allow for manual re-ordering. 

But in the interim, allowing the more specific things to run first (exact matches) I think is probably best.

**Comment by khalwat** [comment]
@sgtpenguin it looks like it is already resolving exact match redirects first: https://github.com/nystudio107/craft-retour/blob/develop/src/services/Redirects.php#L453

We can start another issue to discuss this further if you like

**Comment by khalwat** [comment]
Sorry @sgtpenguin The statement above is pointing to the wrong code. Here's the query which sorts the redirects by `matchtype` which will cause the `exactmatch` redirects to be processed before the `regexmatch` redirects: https://github.com/nystudio107/craft-retour/blob/develop/src/services/Redirects.php#L639

**Comment by sgtpenguin** [comment]
@khalwat Thanks for taking a look.  After playing with it more this morning, it appears the issue was the inclusion of a trailing `/` in the Legacy Url Pattern, which was not matching the uri supplied (using graphql), which does not have a trailing `/`.  The order of events made it seem like the regex was taking priority.  Sorry for the false alarm.

**Comment by khalwat** [comment]
Related: https://github.com/nystudio107/craft-retour/issues/258

**Comment by khalwat** [comment]
This feature has been implemented.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.5”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.7”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Released as:

Craft 3: Version 3.2.5 -> https://github.com/nystudio107/craft-retour/releases/tag/3.2.5

Craft 4: Version 4.1.7 -> https://github.com/nystudio107/craft-retour/releases/tag/4.1.7
