### ISSUE TITLE
[FR] There should be a way to filter sites by redirects that are specifically active on "All Sites"

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-retour#75]
Currently, this doesn't filter out anything, and simply shows you all redirects that are active for `All Sites`, `Site A`, and `Site B`.

Perhaps there could be an `All Redirects` view, then `All Sites` becomes a specific view that only shows redirects with `Sites` set to `All Sites`.

**Comment by khalwat** [comment]
Added a "Sites" column in the listing that you can sort by in https://github.com/nystudio107/craft-retour/commit/bf4d9387008eebd4017812073fba760c2406fb0d
