### ISSUE TITLE
Redirect status marker not working

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft-retour#76]
The color of the redirect marker does not change even if you disable this redirect.

![Аннотация 2019-09-25 185621](https://user-images.githubusercontent.com/496132/65618231-9d794580-dfc6-11e9-995b-c871875816d9.jpg)
![Аннотация 2019-09-25 185645](https://user-images.githubusercontent.com/496132/65618252-a66a1700-dfc6-11e9-9ce4-09e68c0fdf6f.jpg)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/5b3de494c36105692bc00d6a6dd889952e58dcf1
