### ISSUE TITLE
[FR] Import field for "Legacy URL Match Type"

### ISSUE THREAD

**Issue by maxcoe** [nystudio107/craft-retour#78]
Hey Andrew! For our project we need to batch-import redirects from a csv regularly and I was missing the field "Legacy URL Match Type" allowing to choose between full url and path only. So I decided to patch your plugin by myself and hopefully this addition will also appear in some next release ;-)

craft-retour/src/controllers/FileController.php:**65**
```php
    const IMPORT_REDIRECTS_CSV_FIELDS = [
        'redirectSrcUrl',
+++     'redirectSrcMatch', // pathonly vs. fullurl
        'redirectDestUrl',
        'redirectMatchType',
        'redirectHttpCode',
        'siteId',
    ];
```
craft-retour/src/assetbundles/retour/src/vue/ImportDraggable.vue:**91**
```js
                fieldsArray: [
                    'Legacy URL Pattern',
+++                 'Legacy URL Match Type',
                    'Redirect To',
                    'Match Type',
                    'HTTP Status',
                    'Site ID',
                ]
```

<img width="1215" alt="Bildschirmfoto 2019-10-08 um 02 19 57" src="https://user-images.githubusercontent.com/44701746/66359003-90206b80-e975-11e9-98c6-ea68a9012992.png">

**Comment by khalwat** [comment]
Awesome! Do you want to submit a PR or should I just do it manually? Either is cool w/me!

**Comment by maxcoe** [comment]
Oh yes, you can do it manually, thank you! I still haven't learnt how to do PRs on GitHub yet lol!

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-retour/commit/b31d0224dbe147eb9cf6a10d665d303c25b17d81

If you ever want me to walk you through doing a PR, I'd be happy to do so @maxcoe !

Thx!
