### ISSUE TITLE
redirect deleted but still redirecting

### ISSUE THREAD

**Issue by Melisssa** [nystudio107/craft-retour#80]
Hello,

I added a redirect and deleted it and the redirect is still active. I cleared the Craft cache and my browser cache as well. Is there anything else I can check or do to fix this?

Thanks
Mel

**Comment by khalwat** [comment]
Can you try clearing the Retour caches via Utilities -> Clear Caches -> Retour redirect caches ? I'll double-check the code, it should be clearing this when a redirect is deleted, too.

**Comment by khalwat** [comment]
I just double-checked the code, and it does indeed clear the caches when you delete a redirect:

https://github.com/nystudio107/craft-retour/blob/v3/src/controllers/RedirectsController.php#L218

**Comment by Melisssa** [comment]
Thanks for the reply. I've cleared all of the cache including Retour. I also checked the database and did not see the redirect. Is there anywhere else it would be stored?

**Comment by khalwat** [comment]
Is it possible that _something else_ is doing this redirect? Perhaps something in your `.htaccess` or elsewhere?

**Comment by Melisssa** [comment]
I've checked .htaccess and there is nothing. I've asked the client if they changed anything in the domain settings and they did not. I don't know what else to check. Thanks for your help.

**Comment by khalwat** [comment]
Well, if Retour is actually handling the redirect, there will be a record of it on the Retour -> Statistics page

When you go to that URL on the frontend, are you seeing the stats for the redirect increment on the Retour -> Statistics page

If not, then Retour isn't handling it, something else is...

**Comment by Melisssa** [comment]
Thanks! That definitely helps. I can go back to the server admins and have them check their settings again for anything that might be causing this. I appreciate the help.
