### ISSUE TITLE
Redirects not working

### ISSUE THREAD

**Issue by peteralewis** [nystudio107/craft-retour#81]
Can't work out what I'm doing wrong :( Added redirects are simply not working - the redirected page is still appearing as if the Craft Hook that it uses is not kicking in.

Fresh install on local, added page redirect, all basic settings. Nothing happens. Clear cache, checked log files and error logs - nothing.

Deployed to staging, tested the same there, still nothing. Tried both Path Only and Full URL matches. Both servers are Nginx.

<img width="1014" alt="Screenshot 2019-11-06 09 14 43" src="https://user-images.githubusercontent.com/134265/68285359-0993a280-0077-11ea-8dcf-b7d367a44e7a.png">

Was using Redirect Plugin from Dolphiq but that stopped working, so hence buying yours. Assume something to do with the 2 environments (local/staging)...?!? There are no relevant Nginx settings that would appear to be conflicting, or any routing config that might explain conflict.

**Comment by khalwat** [comment]
Retour only kicks in if Craft CMS throws a 404. I'm going to guess that the `/competition` URL is an active page.

SEOmatic intentionally does not work in this instance: https://nystudio107.com/docs/retour/Overview.html

> Retour is written to be performant. There is no impact on your website's performance until a 404 exception happens; and even then the resulting matching happens with minimal impact.

So either remove the `/competition` page/template so a 404 will be thrown, or put a `{% redirect %}` tag in your template. https://docs.craftcms.com/v3/dev/tags/redirect.html

**Comment by peteralewis** [comment]
Ha, ha - lol. oh boy - sorry! yes, setting the page to disabled solves the problem.

Thanks - much appreciated.
