### ISSUE TITLE
[FR] Bulk delete on redirects

### ISSUE THREAD

**Issue by jakebiesinger-onduo** [nystudio107/craft-retour#82]
Hi!

We recently migrated to Craft and now use Retour for our marketing redirects.  I recently bulk-imported ~200 such links, only to find a systematic error in the CSV.

Guess what feature really would have helped clean those up? Yep. Bulk delete.

Currently, Retour offers no way to select multiple links (e.g., "select all", "select this page", etc). If you want to delete the links, you have to click. every. single. one. and wait for the page refresh.  It's awful awful awful.

I did discover a partial workaround: cmd+click the little x button opens a new tab and removes the link. It was still very painful and a bulk-edit interface would be much appreciated.

**Comment by khalwat** [comment]
This was implemented in Retour 3.1.28 -- please update to the latest version -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.28
