### ISSUE TITLE
Security BUG: Don't use GET operations to delete links

### ISSUE THREAD

**Issue by jakebiesinger-onduo** [nystudio107/craft-retour#84]
Was recently working on a big import of links and noticed that the delete page is a simple `GET` request, e.g., `.../retour/delete-redirect/446`

This goes against best practices for the web and may be insecure (much easier to attack via XSRF). Can we make this a POST or something?

**Comment by jakebiesinger-onduo** [comment]
Just to demonstrate why this is bad... so long as I'm logged in to craft on `mysite.com`, any rogue site can cause my redirects to be deleted by just including `<img>` tags in their page:

```
<img src="https://mysite.com/admin/retour/delete-redirect/1">
<img src="https://mysite.com/admin/retour/delete-redirect/2">
<img src="https://mysite.com/admin/retour/delete-redirect/3">
...
<img src="https://mysite.com/admin/retour/delete-redirect/9999999">
```

I don't even have to click anything... so long as I'm logged in to Craft when visiting this site, all my retour links will be immediately deleted.

The Craft CSRF token will be happily sent along with the <img> requests since **GET is not supposed to mutate state**!

Craft doesn't even use `SameSite` cookies for its CSRF so you can do the same trick with click targets from a malicious site.

---

To test this out:
1) grab an incognito window and log in to Craft
2) create a retour redirect and take note of its ID
3) make a page (local `file://` will do fine) with the contents:
```
<html><body>
  <img src="https://<YOUR_SITE>/admin/retour/delete-redirect/<YOUR_ID>">
</body></html>
```
4) open the page in your incognito session
5) weep as your redirect silently disappears 😢 


See also, the [DailyWTF](http://thedailywtf.com/articles/WellIntentioned-Destruction)

**Comment by jakebiesinger-onduo** [comment]
I was about to turn on a web security scanner on our site, but this bug will cause that scanner to delete literally every retour link we have 😿

**Comment by khalwat** [comment]
So two things... 

1. This route is a CP route only, so you'd need to be logged in with an account that has the proper permissions for the deletion of the route to work. It's not a frontend route, but your point is taken regarding a malicious site _and_ you are logged into the CP.

2. For other reasons, this route has been removed entirely from the latest Retour anyway; update to Retour 3.1.28 and the route is entirely gone: https://github.com/nystudio107/craft-retour/blob/v3/src/Retour.php#L630 -- the deletions are now done in bulk, via `POST`

This should allay your concerns.

**Comment by jakebiesinger-onduo** [comment]
Great, glad to hear the issues is fixed. Seeing a `GET` to mutate data had me very worried about this and the other plugins we use from nystudio107. 

It's not crazy to think that you'd be logged in to the the CP when visiting the malicious site... folks in marketing work in Craft all the time and are likely logged in more of the time. This is the stuff that spear-phishing attempts are made of.
