### ISSUE TITLE
No Data Available Available

### ISSUE THREAD

**Issue by matthewmrotter** [nystudio107/craft-retour#87]
Craft Version:  3.3.8

Retour Version:  3.1.31

We are unable to see redirects in the dashboard because of this warning: 

```
Vuetable.vue:800 vuetable: pagination-path "links.pagination" not found. It looks like the data returned from the sever does not have pagination information or you may have set it incorrectly.
You can explicitly suppress this warning by setting pagination-path="".
```

When you open in an incognito window the redirects will show up but if you continue to use the plugin long enough, they'll disappear again. Clearing out the cpresources also doesn't work. We've had this issue across browsers as well and have tried the fix from [this post](https://github.com/nystudio107/craft-seomatic/issues/476) with no success. 

Thanks!

**Comment by matthewmrotter** [comment]
Just found out you can fix this by clearing the Retour Cache. Might be helpful to leave a comment on the "No data available" text to clear it out if it's stuck

**Comment by khalwat** [comment]
Clearing the Retour cache shouldn't change anything with this, that cache just helps make resolving 404s quicker. But I'm glad you got it working?
