### ISSUE TITLE
Multi Site Redirects Not Working

### ISSUE THREAD

**Issue by matthewmrotter** [nystudio107/craft-retour#88]
Craft Version: 3.3.8

Retour Version: 3.1.31

We have created global redirects using Retour but they do not redirect. 

We'll create a redirect using "Path Only" match and Match Type "Exact Match" then it'll work on our home site but none of the others. (/product works but /de/product does not) 

We can create a ReGex expression to make it work for the rest of the languages (^/.*/product will redirect /de/product) but we'll have to add 2 redirects for every page we want to have a 301 on

Thanks!

**Comment by matthewmrotter** [comment]
We just updated to the latest versions and still no luck. 

Craft Version: 3.3.19

Retour Version: 3.2.37


Additionally, we're able to make it work for all of our sites by creating 2 redirects, one with regex: 
ex: 

/webinar => /events?eventType=webinars-only

and

\/(de|pt|japan|es|fr)\/webinar\/ => /events?eventType=webinars-only

**Comment by masonry47** [comment]
Hey Andrew, 

Just following up on this issue.  Perhaps we are not understanding, but for a multi-site setup, when we create, for example, a redirect with the following settings

Sites: All Sites
Legacy URL Pattern: /contact-us/
Legacy URL Match Type: Path Only
Destination URL: /contact/
Match Type: Exact Match
Redirect Type: 301 - Permanent

For our default english site we would expect:

domain.com/contact-us/ redirects to domain.com/contact/ (this works) 

but for our other sites, for example:

domain.com/es/contact-us/ 

does not redirect, nor do any of our other language sites.

I know we could go in and add separate redirects for each site, but we understood that the setting "All Sites" would achieve this. 

We are on 
Craft 3.3.19
Retour 3.1.31

Thanks for any info  you can provide on this!

**Comment by khalwat** [comment]
Yeah that's not going to work for sites with a URL segment suffix unless you set the **Legacy URL Match Type** to **Full URL**

(this setting was added to solve the issue you're running into)

> Should the legacy URL be matched by path (e.g. /new-recipes/) or by full URL (e.g.: http://example.com/de/new-recipes/)?
