### ISSUE TITLE
Performance concerns

### ISSUE THREAD

**Issue by dreadfullyposh** [nystudio107/craft-retour#89]
I've recently been using Retour on a site that required a large number of redirects to be added (currently over 9000, don't ask why).

I noticed some performance issues going on that seemed to be related to the heavy usage of Retour:

1) There's no index on the `redirectSrcUrl` field on stats table. Since that table is queried by that field on every redirect that's handled, it seems like that would be a helpful addition.

2) It seemed like the dashboard page was getting quite heavy to load. I didn't dig through what all it was doing, but combined with the default of reloading itself every 5 seconds, that was enough to impact our servers. (An option to turn off the auto refresh would probably be ideal as well)

3) It seems like maybe there should be an option to turn off the stats altogether. At some point, the number of writes involved to keep the stats is going to become an issue regardless of how tuned it is.

**Comment by dreadfullyposh** [comment]
Ping on this.

**Comment by khalwat** [comment]
> There's no index on the redirectSrcUrl field on stats table. Since that table is queried by that field on every redirect that's handled, it seems like that would be a helpful addition.

Yep, that sounds like a good addition.

> It seemed like the dashboard page was getting quite heavy to load. I didn't dig through what all it was doing, but combined with the default of reloading itself every 5 seconds, that was enough to impact our servers. (An option to turn off the auto refresh would probably be ideal as well)

There is an option to turn auto-refresh off. Go to Retour -> Plugin Settings and set **Dashboard Refresh Interval** to **Never**

But the number of redirects shouldn't really be relevant, the table only fetches 20 at a time regardless of how many are there... and 9600 isn't that many rows for an SQL database to deal with.

> It seems like maybe there should be an option to turn off the stats altogether. At some point, the number of writes involved to keep the stats is going to become an issue regardless of how tuned it is.

I would set **Automatically Trim Statistics** to **Off** and then use the console command to trim them once per day at 4am or something via a cron job.

**Comment by khalwat** [comment]
If you could quantify the performance issues, that'd be really helpful -- 9600 redirects shouldn't be a big deal though, especially for the CP on the backend.

**Comment by dreadfullyposh** [comment]
> There is an option to turn auto-refresh off. Go to Retour -> Plugin Settings and set Dashboard Refresh Interval to Never

Weird. Definitely didn't have that option when I was debugging this before the holidays. And we were having an issues even getting an updated setting to save. It's possible that the settings update was never making it back at the time. Eventually I ended up overriding it via a retour.php file and that calmed everything down.

> If you could quantify the performance issues, that'd be really helpful -- 9600 redirects shouldn't be a big deal though, especially for the CP on the backend.

Not sure how to quantify it per se, but this site is running loadbalanced on two m5.large EC2 instances (8GB memory, 2 VCPUs) and the database is on a separate RDS instance of the same size. Caching is setup with Blitz using a separate ElastiCache Redis instance. The site itself is very heavy on content relationships, so it's definitely more DB-heavy than many sites. 

We had launched the site on December the 16th and everything was running more or less fine, until I imported several sets of redirects. With the last import on Friday the 20th, which brought the total redirects to close to 10k, the site basically just started timing out entirely. We saw spikes in the writes and CPU on the monitoring for the DB instance.

I tried adjusting the settings to refresh less frequently, but I couldn't get that save. I eventually added the config file to set it manually which did work. And I added the index I described above. We were still seeing issues, so it seemed like the client had left for the weekend with 14 tabs of the dashboard open when it was still refreshing every 5 seconds. 

In the end it was the Friday before holiday break and so I just quickly went in and yanked access to Retour to the client's user groups, and within a minute or two everything died down again.  Hard to say. But it was a nearly immediately impact.

It's all pretty strange. There are many redirects, but really this site doesn't get a ton of traffic.

**Comment by khalwat** [comment]
It looks like the Refresh Interval was added in [3.1.10](https://github.com/nystudio107/craft-retour/blob/v3/CHANGELOG.md#3110---20190418)

> We saw spikes in the writes and CPU on the monitoring for the DB instance.

Can you correlate those spikes with CPU usage or db accesses attributable to Retour?

I ask because the CP should be pretty agnostic about how many redirects you have. For instance, the redirect display fetches only 20 redirects for display, no matter how many you actually have in your database.

So it should be a fairly efficient thing. Same with storing the statistics for a hit.

> We were still seeing issues, so it seemed like the client had left for the weekend with 14 tabs of the dashboard open when it was still refreshing every 5 seconds.

yeah, I suppose if you're live-refreshing from a massive number of pages that could be a problem, but even 14 doesn't sound like too much (even if it'd be pinging it every 5 seconds).

I would turn the refresh interval OFF entirely, give the client back access, and see what happens.

**Comment by dreadfullyposh** [comment]
> Can you correlate those spikes with CPU usage or db accesses attributable to Retour?
Not exactly no. We weren't setup to do really specific monitoring at the time.

> yeah, I suppose if you're live-refreshing from a massive number of pages that could be a problem, but even 14 doesn't sound like too much (even if it'd be pinging it every 5 seconds).

Yeah 14 wasn't a real number. But one of the IT team members was obsessing over redirects, so it's possible he had.. "many"

> I would turn the refresh interval OFF entirely, give the client back access, and see what happens.

I gave back access to a few team members there yesterday, and it hasn't gone down yet. Will turn off the refresh entirely and then re-enable access and see what happens.

Thanks for the help! Can close out unless you want to keep this open as a FR for a new index.

**Comment by khalwat** [comment]
Added indexes in https://github.com/nystudio107/craft-retour/commit/9ae0ab4be89eaf021965fd6627e6c3cb25a222cf
