### ISSUE TITLE
More filtering options

### ISSUE THREAD

**Issue by kaspar-allenbach** [nystudio107/craft-retour#90]
It would be great to have a little more filtering options in the Dashboard to keep up with current redirects:

- Not handled hits since last login (So I can see as an admin what has been going on since I last logged into the cp).
- Not handled hits in the last 24h or so
- Not handled hits older than 1 week (To see if something slipped trough my attention)

I regularly check retour when having a site with major redirects but sometimes I get lost and I'm not sure did I already added a redirect for this unhanded entry? Am I creating duplicate redirects now? Or is it age-old and I've overseen it.

**Comment by khalwat** [comment]
I agree more filtering options would be nice -- but you can sort them by date to get a decent idea of what the new 404s are, no?

**Comment by kaspar-allenbach** [comment]
Yeah thats true. After a while the 404 errors are constantly reduced and the 302 are increased so the date is sufficient.
