### ISSUE TITLE
Header may not contain more than a single header, new line detected

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-retour#91]
We are seeing intermittent 500 errors on our site which appear to be caused by Retour as shown in the below log output. 

We are running Craft 3.3.17 and Retour 3.1.30. 

I suspect this is caused by our vunerability scanner but would expect this to be handled with a 4XX error rather than 5XX as it is intitated from the client. 

`[06-Jan-2020 06:03:54 Europe/London] PHP Fatal error:  Uncaught yii\base\ErrorException: Header may not contain more than a single header, new line detected in /var/app/current/vendor/yiisoft/yii2/web/Response.php:374
Stack trace:
#0 /var/app/current/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(2, 'Header may not ...', '/var/app/curren...', 374)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'Header may not ...', '/var/app/curren...', 374, Array)
#2 /var/app/current/vendor/yiisoft/yii2/web/Response.php(374): header('Location: https...', true)
#3 /var/app/current/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#4 /var/app/current/vendor/nystudio107/craft-retour/src/services/Redirects.php(261): yii\web\Response->send()
#5 /var/app/current/vendor/nystudio107/craft-retour/src/services/Redirects.php(178): nystudio107\retour\services\Redirects->doRedirect('https://...', '/en/\r\nx', Array)
#6 /var/app/current/vendor/nystudio107/craft-retour/src/Retour.php(514): nystudio107\retour\ in /var/app/current/vendor/yiisoft/yii2/web/Response.php on line 374
[06-Jan-2020 06:03:54 Europe/London] PHP Fatal error:  Uncaught yii\base\ErrorException: Header may not contain more than a single header, new line detected in /var/app/current/vendor/yiisoft/yii2/web/Response.php:374
Stack trace:
#0 /var/app/current/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(2, 'Header may not ...', '/var/app/curren...', 374)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'Header may not ...', '/var/app/curren...', 374, Array)
#2 /var/app/current/vendor/yiisoft/yii2/web/Response.php(374): header('Location: https...', true)
#3 /var/app/current/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#4 /var/app/current/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#5 /var/app/current/vendor/craftcms/cms/src/web/ErrorHandler.php(137): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#6 /var/app/current/vendor/yiisoft/yii2/base/ErrorHandler.php(262): craft\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#7 [ in /var/app/current/vendor/yiisoft/yii2/web/Response.php on line 374`

**Comment by khalwat** [comment]
> I suspect this is caused by our vunerability scanner but would expect this to be handled with a 4XX error rather than 5XX as it is intitated from the client.

Can you give me some more information on why you believe this is from the vulnerability scanner? Is it possible that your vulnerability scanner is passing in malformed URLs in an attempt to find vulnerabilities?

Because [from the sound of it](https://stackoverflow.com/questions/16320403/getting-warning-header-may-not-contain-more-than-a-single-header-new-line-dete) it might be passing in a malformed URL.

Anyway, this should fix it: https://github.com/nystudio107/craft-retour/commit/4f79d96ec25b3846d4d7450b7f2503b60b5404f5

**Comment by baileydoestech** [comment]
Yes exactly, sorry if that wasn’t clear. Thanks for the quick fix

**Comment by brandonkelly** [comment]
We’re seeing this same error in phperrors.log. The actual `Location` header is being stripped out unfortunately, so not sure what the culprit is.

```
[11-May-2020 23:58:35 America/Los_Angeles] PHP Fatal error:  Uncaught yii\base\ErrorException: Header may not contain more than a single header, new line detected in /var/app/current/vendor/yiisoft/yii2/web/Response.php:374
Stack trace:
#0 /var/app/current/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(2, 'Header may not ...', '/var/app/curren...', 374)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'Header may not ...', '/var/app/curren...', 374, Array)
#2 /var/app/current/vendor/yiisoft/yii2/web/Response.php(374): header('Location: https...', true)
#3 /var/app/current/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#4 /var/app/current/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#5 /var/app/current/vendor/craftcms/cms/src/web/ErrorHandler.php(128): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#6 /var/app/current/vendor/yiisoft/yii2/base/ErrorHandler.php(276): craft\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#7 [ in /var/app/current/vendor/yiisoft/yii2/web/Response.php on line 374
```

I just ran this query to see if we had any redirects in `retour_static_redirects` that contained unexpected characters like newlines, but the query came back with 0 results:

```sql
select * from retour_static_redirects
where "redirectDestUrl" !~* '^[\w/\-:/\.#$]+$'
```

	
Retour 3.1.37

**Comment by khalwat** [comment]
@brandonkelly That should be fixed if you update to the latest version of Retour
