### ISSUE TITLE
[FR] Option to enforce trailing slashes on destination url when adding redirects

### ISSUE THREAD

**Issue by EpocSquadron** [nystudio107/craft-retour#92]
We have a site-wide redirect to enforce trailing slash at the end of all urls on the site. We give our client access to add additional redirects from legacy urls to their new ones, however due to human error a destination without a trailing slash ends up getting added from time to time. This is an issue because it results in a redirect chain, first from the legacy url to the new url, then to the new url with trailing slash.

It's trivial enough to run a SQL replace on the table to put them back in for existing redirects, but going forward we would like to prevent more instances from cropping up without having to remember to rerun the query periodically.

We wanted to use the event that is fired before the redirect is saved to do a regex replace on the destination, but we cannot effect the values to be saved to the database in that event. Is it possible to add an option to Retour which will check if the destination url is to the site and normalize the trailing slashes on or off?

**Comment by khalwat** [comment]
Seems reasonable. I assume you have the `addTrailingSlashesToUrls` set to `true` in `general.php`?

What I could do is if they are saving the Redirect and `addTrailingSlashesToUrls` is `true` and the destination is a relative URL, I could ask Craft for the `siteUrl()` for it (which should add trailing slashes if that options is on).

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-retour/commit/48bc8d509f376dbcdf3bdf5615b99c2f40b38428
