### ISSUE TITLE
Can't add, edit or delete redirects

### ISSUE THREAD

**Issue by dgrigg** [nystudio107/craft-retour#93]
I have a site setup using project config. On the local server 'allowAdminChanges' is set to true, I can add/edit/delete redirects. On the production server, 'allowAdminChanges' is set to false. I can't  add, edit or delete redirects on the production server. I tried changing the 'allowAdminChanges' to true but still no luck. Any ideas?

**Comment by dgrigg** [comment]
To add to this, it almost seems like the retour entries are getting cached somehow. I just added on the production site, it appears to have saved, no warning message but I don't see it in the list in the control panel. If I check the database table I do see it though.

**Comment by khalwat** [comment]
So `allowAdminChanges` shouldn't have anything to do with it, Retour doesn't limit anything based on that setting.

You say "I can't add, edit or delete redirects on the production server. " -- what does it look like? What happens when you try to do these things?

Any errors in your JavaScript console? Or in `web.log`?

**Comment by dgrigg** [comment]
No errors in the logs. I think it might be a cloudflare issue. The person who setup cloudflare set it to only ignore '/admin/(*)' but it looks like the Retour plugin calls 'index.php?p=admin/actions ......

Going to get that fixed first to see what happens.

**Comment by khalwat** [comment]
So that's just a CP Action URL -- so other plugins/Craft CP functionality might not work, too.

But yes, if you get this sorted, that'll fix the issue. CloudFront shouldn't be active for any part of the CP, including action URLs. If they whitelist `/index.php` URLs that should do it.

**Comment by dgrigg** [comment]
Yes, I just realized that's what they setup, which explains a few weird things that were going on.
