### ISSUE TITLE
Question: custom routes

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-retour#96]
Hi Andrew @khalwat ,

We are dealing with a website that has custom routes. We defined some re-directs that are also matching custom routes. So when we visit the legacy URL of the redirect it's not responding.

Does retour take in account custom routes? Or is it able to?

**Comment by khalwat** [comment]
Retour only redirects when Craft has finished trying to resolve a route, and fails to, throwing a 404.

Retour will never redirect anything that matches a route in Craft.

Either have the route in question no longer be handled by Craft, or do the redirect via Template:

```twig
{% redirect %}
```

...or via Apache/Nginx server config.
