### ISSUE TITLE
Redirect to file

### ISSUE THREAD

**Issue by zakrzk** [nystudio107/craft-retour#98]
Hey, 

is it possible to set a redirection to a file? 
Setting `/assets/myFile.pdf` in the _Destination URL_ field doesn't work.

**Comment by khalwat** [comment]
What you say it doesn't work, what goes wrong?

I wouldn't think it'd matter, Retour just sends the redirect URL to Craft to do the redirect.

Does this redirect work if you change it to a directory?

My guess is that the redirect is never happening to begin with. Retour only does a redirect once Craft throws a 404 error, so if the existing route matching something in Craft, the redirect will never happen:

https://nystudio107.com/docs/retour/WhyRetour.html#why-use-a-plugin-for-redirects

**Comment by zakrzk** [comment]
> Retour only does a redirect once Craft throws a 404 error

Ahh ok, good to know! I disabled the page and it's working fine now. 

Thanks! 👍
