### ISSUE TITLE
Dashboard widget link to Retour dashboard error

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-retour#99]
Hi,

The link at the bottom of Retour's widget that redirect to the Retour dashboard is not working.
The link is pointing to `https://www.domain.fr/admin/dashboard/retour/dashboard`

It's happening only on my prod servers, so I presume it's related to NGINX config. I'm using [your config](https://github.com/nystudio107/nginx-craft)

Do you have any clue ?

**Comment by khalwat** [comment]
So you're saying the issue happens when you click on the widget?

**Comment by LouisCuvelier** [comment]
Yes, on the "Dashboard" link.

![image](https://user-images.githubusercontent.com/34551650/74666968-c6cb8580-51a2-11ea-8601-6d46ca365aa8.png)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/fc8408c63413c8d57ff6838f15c2d8b1c7b9a359
